//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGColorSpace;

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct ColorComponents {
    int _field1;
    double _field2[5];
};

struct FFTextSearchResult;

struct GL {
    struct _CGLContextObject *_field1;
    _Bool _field2;
    struct MatrixState *_field3;
    _Bool _field4;
};

struct GLRenderer;

struct HGCVBitmap;

struct HGComputeDevice;

struct HGGPUComputeDevice;

struct HGMetalTexture;

struct HGRef<HGCVBitmap> {
    struct HGCVBitmap *_field1;
};

struct HGRef<HGMetalTexture> {
    struct HGMetalTexture *_field1;
};

struct LiCamera;

struct LiLight;

struct LiLightSet {
    struct PCArray<LiLight, PCArray_Traits<LiLight>> _field1;
    _Bool _field2;
};

struct LiRenderingTechnology {
    unsigned int _field1;
    int _field2;
    int _field3;
    int _field4;
    _Bool _field5;
    _Bool _field6;
    _Bool _field7;
    _Bool _field8;
    _Bool _field9;
    int _field10;
    int _field11;
    _Bool _field12;
    _Bool _field13;
    _Bool _field14;
    int _field15;
    int _field16;
    _Bool _field17;
    _Bool _field18;
};

struct MatrixState;

struct OZ3DExtrusionProperties {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    struct OZChannelDouble _field18;
    struct OZChannelEnum _field19;
    struct OZChannelEnum _field20;
    struct OZChannelDouble _field21;
    struct OZChannelEnum _field22;
    struct OZChannel2D _field23;
    struct OZChannelEnum _field24;
    struct OZChannel2D _field25;
    struct OZChannelEnum _field26;
    struct OZChannelFolder _field27;
    struct OZChannelEnum _field28;
    struct OZChannelPercent _field29;
    struct OZChannelFolder _field30;
    struct OZChannelPercent _field31;
    struct OZChannelDouble _field32;
    struct OZChannelFolder _field33;
    struct OZChannelEnum _field34;
    struct OZChannelEnum _field35;
    struct OZChannelStringEnum _field36;
    struct OZChannelEnum _field37;
    struct OZChannelGradient _field38;
    struct OZChannelPercent _field39;
    struct OZChannelDouble _field40;
    struct OZChannelRotation3D _field41;
    struct OZChannelDouble _field42;
    struct OZChannelDouble _field43;
    struct OZChannelDouble _field44;
    struct OZChannelBool _field45;
    struct OZChannelFolder _field46;
    struct OZChannelFolder _field47;
    struct OZChannelEnum _field48;
    struct OZChannelEnum _field49;
    struct OZChannelDouble _field50;
    struct OZChannelBool _field51;
};

struct OZBehavior {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    struct PCSafeHandle *_field4;
    struct PCHash128 _field5;
    CDUnknownFunctionPointerType *_field6;
    struct OZChannelBehaviorRoot _field7;
    _Bool _field8;
    _Bool _field9;
    struct OZSceneNode *_field10;
};

struct OZCanvasState;

struct OZChanFootageRef {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
    _Bool _field20;
    _Bool _field21;
    _Bool _field22;
    _Bool _field23;
    _Bool _field24;
    _Bool _field25;
    _Bool _field26;
};

struct OZChanRotoshapeRefWithPicker {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
    _Bool _field20;
    _Bool _field21;
    _Bool _field22;
    _Bool _field23;
    struct list<PCUUID, std::__1::allocator<PCUUID>> *_field24;
    struct list<PCUUID, std::__1::allocator<PCUUID>> _field25;
    _Bool _field26;
    _Bool _field27;
    _Bool _field28;
    _Bool _field29;
    _Bool _field30;
    _Bool _field31;
    _Bool _field32;
    _Bool _field33;
    _Bool _field34;
    _Bool _field35;
};

struct OZChannel {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
};

struct OZChannel2D {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelDouble _field19;
    struct OZChannelDouble _field20;
};

struct OZChannel3D {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelDouble _field19;
    struct OZChannelDouble _field20;
    struct OZChannelDouble _field21;
};

struct OZChannelAngle {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
};

struct OZChannelBase {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
};

struct OZChannelBehaviorRoot {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    CDStruct_198678f7 _field18;
    struct PCTimeRange _field19;
    _Bool _field20;
    _Bool _field21;
    struct OZObjectManipulator *_field22;
    struct OZTimeMarkerSet *_field23;
    struct list<OZSimulationBehavior *, std::__1::allocator<OZSimulationBehavior *>> _field24;
    struct PCString _field25;
    struct OZBehavior *_field26;
};

struct OZChannelBlendMode {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
    struct __map_iterator<std::__1::__tree_iterator<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, std::__1::__tree_node<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, void *>*, long>> _field20;
    struct PCString _field21;
    struct vector<int, std::__1::allocator<int>> _field22;
    unsigned int _field23;
    struct PCString _field24;
    struct vector<PCString, std::__1::allocator<PCString>> _field25;
};

struct OZChannelBool {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
};

struct OZChannelColorNoAlpha {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelDouble _field19;
    struct OZChannelDouble _field20;
    struct OZChannelDouble _field21;
    struct OZChannelDouble _field22;
    struct OZChannelEnum _field23;
};

struct OZChannelCrop {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelDouble _field19;
    struct OZChannelDouble _field20;
    struct OZChannelDouble _field21;
    struct OZChannelDouble _field22;
};

struct OZChannelDouble {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
};

struct OZChannelEnum {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
    struct __map_iterator<std::__1::__tree_iterator<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, std::__1::__tree_node<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, void *>*, long>> _field20;
    struct PCString _field21;
    struct vector<int, std::__1::allocator<int>> _field22;
    unsigned int _field23;
    struct PCString _field24;
    struct vector<PCString, std::__1::allocator<PCString>> _field25;
};

struct OZChannelEnumInterpMode {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
    struct __map_iterator<std::__1::__tree_iterator<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, std::__1::__tree_node<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, void *>*, long>> _field20;
    struct PCString _field21;
    struct vector<int, std::__1::allocator<int>> _field22;
    unsigned int _field23;
    struct PCString _field24;
    struct vector<PCString, std::__1::allocator<PCString>> _field25;
};

struct OZChannelFolder {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
};

struct OZChannelGradient {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    struct OZChannelGradientRGBFolder _field18;
    struct OZChannelGradientAlphaFolder _field19;
    struct OZChannelDouble _field20;
    struct OZChannelEnum _field21;
    int _field22;
    _Bool _field23;
};

struct OZChannelGradientAlphaFolder {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
};

struct OZChannelGradientRGBFolder {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
};

struct OZChannelGradientWithAngle {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    struct OZChannelGradientRGBFolder _field18;
    struct OZChannelGradientAlphaFolder _field19;
    struct OZChannelDouble _field20;
    struct OZChannelEnum _field21;
    int _field22;
    _Bool _field23;
    struct OZChannelEnum _field24;
    struct OZChannelAngle _field25;
};

struct OZChannelImageForImageWithOptions {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
    _Bool _field20;
    _Bool _field21;
    _Bool _field22;
    _Bool _field23;
    _Bool _field24;
    struct OZChannel2D *_field25;
    _Bool _field26;
    struct OZChannelImageWithOptions *_field27;
};

struct OZChannelImageWithOptions {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelImageForImageWithOptions _field19;
    struct OZChannelUint32 _field20;
    struct OZChannelBool _field21;
    struct OZChannelPosition _field22;
    struct OZChannelEnum _field23;
};

struct OZChannelImpl;

struct OZChannelInfo;

struct OZChannelMaterialMapScale {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelDouble _field19;
    struct OZChannelDouble _field20;
    struct OZChannelBool _field21;
    struct OZChannelDouble _field22;
    struct OZChannelScale _field23;
};

struct OZChannelMaterialMapTransform {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    struct OZChannelEnum _field18;
    struct OZChannelEnum _field19;
    struct OZChannelEnum _field20;
    struct OZChannelEnum _field21;
    struct OZChannelPosition _field22;
    struct OZChannelMaterialMapScale _field23;
    struct OZChannelRotation3D _field24;
    double _field25;
};

struct OZChannelMaterialRoot {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    CDStruct_198678f7 _field18;
    struct PCTimeRange _field19;
    _Bool _field20;
    _Bool _field21;
    struct OZObjectManipulator *_field22;
    struct OZTimeMarkerSet *_field23;
    struct list<OZSimulationBehavior *, std::__1::allocator<OZSimulationBehavior *>> _field24;
    struct PCString _field25;
    struct OZMaterialBase *_field26;
};

struct OZChannelObjectRoot {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    CDStruct_198678f7 _field18;
    struct PCTimeRange _field19;
    _Bool _field20;
    _Bool _field21;
    struct OZObjectManipulator *_field22;
    struct OZTimeMarkerSet *_field23;
    struct list<OZSimulationBehavior *, std::__1::allocator<OZSimulationBehavior *>> _field24;
    struct PCString _field25;
};

struct OZChannelPercent {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
};

struct OZChannelPosition {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelDouble _field19;
    struct OZChannelDouble _field20;
    _Bool _field21;
    PCMatrix44Tmpl_93ed1289 _field22;
    vector_8f06c10f _field23;
    vector_8f06c10f _field24;
    vector_8f06c10f _field25;
    vector_8f06c10f _field26;
    vector_8f06c10f _field27;
    unsigned int _field28;
    struct PCSpinLock _field29;
};

struct OZChannelPosition3D {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelDouble _field19;
    struct OZChannelDouble _field20;
    _Bool _field21;
    PCMatrix44Tmpl_93ed1289 _field22;
    vector_8f06c10f _field23;
    vector_8f06c10f _field24;
    vector_8f06c10f _field25;
    vector_8f06c10f _field26;
    vector_8f06c10f _field27;
    unsigned int _field28;
    struct PCSpinLock _field29;
    vector_8f06c10f _field30;
    _Bool _field31;
    _Bool _field32;
    struct OZChannelDouble _field33;
};

struct OZChannelQuad {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelPosition _field19;
    struct OZChannelPosition _field20;
    struct OZChannelPosition _field21;
    struct OZChannelPosition _field22;
};

struct OZChannelRef {
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field1;
};

struct OZChannelRotation3D {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelAngle _field19;
    struct OZChannelAngle _field20;
    struct OZChannelAngle _field21;
    struct OZChannelEnumInterpMode _field22;
    struct PCSpinLock _field23;
};

struct OZChannelScale {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelDouble _field19;
    struct OZChannelDouble _field20;
};

struct OZChannelScale3D {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelDouble _field19;
    struct OZChannelDouble _field20;
    struct OZChannelDouble _field21;
};

struct OZChannelSceneNode {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    CDStruct_198678f7 _field18;
    struct PCTimeRange _field19;
    _Bool _field20;
    _Bool _field21;
    struct OZObjectManipulator *_field22;
    struct OZTimeMarkerSet *_field23;
    struct list<OZSimulationBehavior *, std::__1::allocator<OZSimulationBehavior *>> _field24;
    struct PCString _field25;
    struct OZSceneNode *_field26;
};

struct OZChannelSeed {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
};

struct OZChannelShear {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelShearAngle _field19;
    struct OZChannelShearAngle _field20;
};

struct OZChannelShearAngle {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
};

struct OZChannelStringEnum {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
    struct __map_iterator<std::__1::__tree_iterator<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, std::__1::__tree_node<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, void *>*, long>> _field20;
    struct PCString _field21;
    struct vector<int, std::__1::allocator<int>> _field22;
    unsigned int _field23;
    struct PCString _field24;
    struct vector<PCString, std::__1::allocator<PCString>> _field25;
    struct vector<PCString, std::__1::allocator<PCString>> _field26;
    struct PCString _field27;
};

struct OZChannelTimeConverter;

struct OZChannelUint16 {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
};

struct OZChannelUint32 {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
};

struct OZCurve;

struct OZCurveEditorState;

struct OZDocument {
    CDUnknownFunctionPointerType *_field1;
    CDUnknownFunctionPointerType *_field2;
    struct PCSafeHandle *_field3;
    struct OZScene *_field4;
    struct PCString _field5;
    struct list<OZObjectSelections *, std::__1::allocator<OZObjectSelections *>> _field6;
    struct vector<OZChannelRef, std::__1::allocator<OZChannelRef>> _field7;
    struct PCString _field8;
    unsigned int _field9;
    _Bool _field10;
    _Bool _field11;
    unsigned int _field12;
    _Bool _field13;
    int _field14;
    struct PCString _field15;
    struct PCString _field16;
    unsigned int _field17;
    unsigned long long _field18;
    _Bool _field19;
    struct OZNotificationManager *_field20;
    id _field21;
    _Bool _field22;
    struct OZViewerState *_field23[4];
    struct OZCanvasState *_field24;
    struct OZProjectPanelState *_field25;
    struct OZTimelineState *_field26;
    struct OZCurveEditorState *_field27;
    struct OZInspectorState *_field28;
    _Bool _field29;
    unsigned int _field30;
    unsigned int _field31;
    struct PCString _field32;
    _Bool _field33;
    struct OZRigWidget *_field34;
    struct vector<OZChannelRef, std::__1::allocator<OZChannelRef>> _field35;
    int _field36;
    _Bool _field37;
};

struct OZElement {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    struct PCSafeHandle *_field4;
    struct PCHash128 _field5;
    CDUnknownFunctionPointerType *_field6;
    struct OZChannelSceneNode _field7;
    struct OZChannelFolder _field8;
    struct OZChannelFolder _field9;
    struct OZChannelFolder _field10;
    struct OZChannelFolder _field11;
    struct OZChannelFolder _field12;
    struct OZSceneNode *_field13;
    struct OZScene *_field14;
    struct list<OZEffect *, std::__1::allocator<OZEffect *>> _field15;
    list_64b41211 _field16;
    unsigned int _field17;
    _Bool _field18;
    double _field19;
    struct PCHash128 _field20;
    struct vector<unsigned int, std::__1::allocator<unsigned int>> _field21;
    struct __list_iterator<OZSceneNode *, void *> _field22;
    unsigned int _field23;
    struct OZChannelFolder _field24;
    struct OZChannelPosition3D _field25;
    struct OZChannelRotation3D _field26;
    struct OZChannelPosition3D _field27;
    struct OZChannel3D _field28;
    struct OZChannelScale3D _field29;
    struct OZChannelShear _field30;
    struct OZChannelPosition3D _field31;
    double _field32;
    unsigned int _field33;
    struct OZChannelAngle _field34;
    CDUnknownFunctionPointerType *_field35;
    struct PCHash128 _field36;
    struct OZChannelFolder _field37;
    struct OZChannelPercent _field38;
    struct OZChannelBlendMode _field39;
    struct OZChannelFolder _field40;
    struct OZChannelDouble _field41;
    struct OZChannelPercent _field42;
    struct OZChannelPercent _field43;
    struct OZChannelEnum _field44;
    struct OZChannelPercent _field45;
    struct OZChannelBool _field46;
    struct OZLightingFolder _field47;
    struct OZFolderElementShadows _field48;
    struct OZChannelFolder _field49;
    struct OZChannelPercent _field50;
    struct OZChannelDouble _field51;
    struct OZChannelFolder _field52;
    struct OZChannelDouble _field53;
    struct OZChannelDouble _field54;
    struct OZChannelDouble _field55;
    struct OZChannelEnum _field56;
    struct OZChannelEnum _field57;
    struct OZChannelFolder _field58;
    struct OZChannelColorNoAlpha _field59;
    struct OZChannelPercent _field60;
    struct OZChannelDouble _field61;
    struct OZChannelDouble _field62;
    struct OZChannelAngle _field63;
    struct OZChannelBool _field64;
    struct OZChannelQuad _field65;
    struct OZChannelCrop _field66;
    struct OZChannelFolder _field67;
    unsigned int _field68;
    unsigned int _field69;
    unsigned int _field70;
    list_e89ce44a _field71;
    struct OZChannelFolder _field72;
    struct OZChanFootageRef _field73;
    struct PCHash128 _field74;
    unsigned int _field75;
    unsigned int _field76;
    _Bool _field77;
    _Bool _field78;
    struct shared_ptr<PGTexture> _field79;
    struct HGRef<HGMetalTexture> _field80;
};

struct OZFactory;

struct OZFactoryBase {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
};

struct OZFolderElementShadows {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    struct OZChannelBool _field18;
    struct OZChannelBool _field19;
    struct OZChannelBool _field20;
};

struct OZFolderMaterialProperties {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    struct OZChannelDouble _field18;
};

struct OZFontCollection {
    struct PCString _field1;
    struct PCString _field2;
    struct map<PCString, OZFontFamily *, std::__1::less<PCString>, std::__1::allocator<std::__1::pair<const PCString, OZFontFamily *>>> _field3;
};

struct OZFontFace;

struct OZFontFamily {
    struct PCString _field1;
    struct PCString _field2;
    struct vector<std::__1::shared_ptr<OZFontFace>, std::__1::allocator<std::__1::shared_ptr<OZFontFace>>> _field3;
};

struct OZGradientGroupShader;

struct OZInspectorState;

struct OZLayeredMaterial {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    struct PCSafeHandle *_field4;
    struct PCHash128 _field5;
    CDUnknownFunctionPointerType *_field6;
    CDUnknownFunctionPointerType *_field7;
    struct PCHash128 _field8;
    struct PCMutex _field9;
    struct OZChannelMaterialRoot _field10;
    struct OZChannelDouble _field11;
    struct OZChannelUint16 _field12;
    struct OZChannelUint32 _field13;
    struct OZChannelEnum _field14;
    struct OZChannelBool _field15;
    struct OZObjectManipulator *_field16;
    _Bool _field17;
    struct PCString _field18;
    _Bool _field19;
    struct OZMaterialLayersFolder _field20;
    struct OZChannelFolder _field21;
    struct OZChannelMaterialMapTransform _field22;
    struct OZChannelFolder _field23;
    struct OZChannelEnum _field24;
    _Bool _field25;
    int _field26;
    int _field27;
    _Bool _field28;
    struct map<PCHash128, LiTextureStoreToken, std::__1::less<PCHash128>, std::__1::allocator<std::__1::pair<const PCHash128, LiTextureStoreToken>>> _field29;
    struct PCSpinLock _field30;
};

struct OZLibraryPresetsMap {
    CDUnknownFunctionPointerType *_field1;
    struct __tree<std::__1::__value_type<PCString, OZLibraryPresetsMapDatum>, std::__1::__map_value_compare<PCString, std::__1::__value_type<PCString, OZLibraryPresetsMapDatum>, std::__1::less<PCString>, true>, std::__1::allocator<std::__1::__value_type<PCString, OZLibraryPresetsMapDatum>>> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<PCString, OZLibraryPresetsMapDatum>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<PCString, std::__1::__value_type<PCString, OZLibraryPresetsMapDatum>, std::__1::less<PCString>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field2;
};

struct OZLibraryPresetsMapDatum {
    id _field1;
    struct shared_ptr<OZLibraryPresetsMap> _field2;
};

struct OZLightingFolder {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    struct OZChannelEnum _field18;
    struct OZChannelBool _field19;
    struct OZChannelDouble _field20;
    struct OZFolderMaterialProperties _field21;
};

struct OZMaterialBase {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    struct PCSafeHandle *_field4;
    struct PCHash128 _field5;
    CDUnknownFunctionPointerType *_field6;
    CDUnknownFunctionPointerType *_field7;
    struct PCHash128 _field8;
    struct PCMutex _field9;
    struct OZChannelMaterialRoot _field10;
    struct OZChannelDouble _field11;
    struct OZChannelUint16 _field12;
    struct OZChannelUint32 _field13;
    struct OZChannelEnum _field14;
    struct OZChannelBool _field15;
    struct OZObjectManipulator *_field16;
    _Bool _field17;
    struct PCString _field18;
    _Bool _field19;
};

struct OZMaterialLayerBase {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelEnum _field19;
    struct OZChannelEnum _field20;
    struct OZChannelStringEnum _field21;
    struct OZChannelEnum _field22;
    struct map<PCHash128, LiTextureStoreToken, std::__1::less<PCHash128>, std::__1::allocator<std::__1::pair<const PCHash128, LiTextureStoreToken>>> _field23;
    struct PCSpinLock _field24;
};

struct OZMaterialLayersFolder {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
};

struct OZNotificationManager;

struct OZObjectManipulator {
    CDUnknownFunctionPointerType *_field1;
    struct PCSafeHandle *_field2;
    struct PCHash128 _field3;
};

struct OZPasteList {
    struct __list_node_base<OZPasteEntry *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZPasteEntry *, void *>>> _field2;
    struct list<OZPasteEntry *, std::__1::allocator<OZPasteEntry *>> _field3;
    _Bool _field4;
};

struct OZPlaybackEngine {
    int _field1;
    int _field2;
};

struct OZProcessControl;

struct OZProjectPanelState;

struct OZRenderNode {
    CDUnknownFunctionPointerType *_field1;
    struct PCHash128 _field2;
};

struct OZRenderParams {
    struct OZRenderState _field1;
    _Bool _field2;
    struct OZProcessControl *_field3;
    struct GLRenderer *_field4;
    struct shared_ptr<const HGComputeDevice> _field5;
    struct shared_ptr<const HGComputeDevice> _field6;
    struct PCImageAttributes _field7;
    struct PCHash128 _field8;
    struct PCHash128 _field9;
    _Bool _field10;
    PCVector2_79efa81a _field11;
    PCVector2_79efa81a _field12;
    int _field13;
    int _field14;
    int _field15;
    int _field16;
    _Bool _field17;
    _Bool _field18;
    _Bool _field19;
    _Bool _field20;
    _Bool _field21;
    _Bool _field22;
    _Bool _field23;
    _Bool _field24;
    _Bool _field25;
    int _field26;
    _Bool _field27;
    unsigned int _field28;
    double _field29;
    _Bool _field30;
    _Bool _field31;
    _Bool _field32;
    _Bool _field33;
    _Bool _field34;
    _Bool _field35;
    struct PCColor _field36;
    int _field37;
    _Bool _field38;
    PCRect_b601f9f3 _field39;
    PCRect_b601f9f3 _field40;
    struct PCRect<int> _field41;
    PCRect_b601f9f3 _field42;
    _Bool _field43;
    int _field44;
    struct CGColorSpace *_field45;
    float _field46;
    struct PCColorSpaceHandle _field47;
    int _field48;
    struct PCColorSpaceHandle _field49;
    struct PCColorSpaceHandle _field50;
    PCMatrix44Tmpl_93ed1289 _field51;
    _Bool _field52;
    struct OZPlaybackEngine _field53;
    id _field54;
    id _field55;
    CDStruct_198678f7 _field56;
    struct map<unsigned int, HGRef<HGNode>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, HGRef<HGNode>>>> *_field57;
    struct map<unsigned int, FFStreamVideo *, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, FFStreamVideo *>>> *_field58;
    struct map<unsigned int, CMTime, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, CMTime>>> _field59;
    struct map<unsigned int, CMTime, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, CMTime>>> _field60;
    struct map<unsigned int, PCRect<double>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, PCRect<double>>>> _field61;
    struct map<unsigned int, unsigned int, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, unsigned int>>> _field62;
    struct map<unsigned int, unsigned int, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, unsigned int>>> _field63;
    double _field64;
    id _field65;
    CDStruct_198678f7 _field66;
    CDStruct_198678f7 _field67;
    CDStruct_198678f7 _field68;
    CDStruct_198678f7 _field69;
    CDStruct_198678f7 _field70;
    _Bool _field71;
    _Bool _field72;
    _Bool _field73;
    _Bool _field74;
    struct shared_ptr<PCImage> _field75;
    _Bool _field76;
    _Bool _field77;
    struct PCPtr<OZRenderParams::SharedInfo> _field78;
    double _field79;
    double _field80;
    _Bool _field81;
    struct PCPtr<LiCamera> _field82;
    struct PCPtr<LiCamera> _field83;
    _Bool _field84;
    _Bool _field85;
    struct LiRenderingTechnology _field86;
    struct LiLightSet _field87;
    _Bool _field88;
    struct HGRef<HGCVBitmap> _field89;
    _Bool _field90;
    _Bool _field91;
    _Bool _field92;
};

struct OZRenderResult;

struct OZRenderState {
    CDStruct_198678f7 _field1;
    double _field2;
    double _field3;
    double _field4;
    unsigned int _field5;
    struct OZTransformNode *_field6;
    _Bool _field7;
    PCMatrix44Tmpl_93ed1289 _field8;
    _Bool _field9;
    _Bool _field10;
    _Bool _field11;
    _Bool _field12;
    _Bool _field13;
    _Bool _field14;
    struct OZRenderNode *_field15;
    int _field16;
    _Bool _field17;
    struct OZElement *_field18;
    _Bool _field19;
    _Bool _field20;
    _Bool _field21;
    _Bool _field22;
    _Bool _field23;
    _Bool _field24;
    _Bool _field25;
    _Bool _field26;
    int _field27;
    struct TransformSet _field28;
    struct set<OZElement *, std::__1::less<OZElement *>, std::__1::allocator<OZElement *>> *_field29;
};

struct OZRigWidget;

struct OZScene;

struct OZSceneNode {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    struct PCSafeHandle *_field4;
    struct PCHash128 _field5;
    CDUnknownFunctionPointerType *_field6;
    struct OZChannelSceneNode _field7;
    struct OZChannelFolder _field8;
    struct OZChannelFolder _field9;
    struct OZChannelFolder _field10;
    struct OZChannelFolder _field11;
    struct OZChannelFolder _field12;
    struct OZSceneNode *_field13;
    struct OZScene *_field14;
    struct list<OZEffect *, std::__1::allocator<OZEffect *>> _field15;
    list_64b41211 _field16;
    unsigned int _field17;
    _Bool _field18;
    double _field19;
    struct PCHash128 _field20;
    struct vector<unsigned int, std::__1::allocator<unsigned int>> _field21;
    struct __list_iterator<OZSceneNode *, void *> _field22;
    unsigned int _field23;
};

struct OZStyle;

struct OZTimeMarkerSet;

struct OZTimelineState;

struct OZTransformNode;

struct OZViewerState;

struct PCArray<LiLight, PCArray_Traits<LiLight>> {
    CDUnknownFunctionPointerType *_field1;
    int _field2;
    int _field3;
    struct LiLight *_field4;
};

struct PCBitmap;

struct PCBox<double> {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
};

struct PCColor {
    struct ColorComponents _field1;
    struct PCColorSpaceHandle _field2;
};

struct PCColorSpaceHandle {
    struct CGColorSpace *_field1;
};

struct PCHash128 {
    unsigned int _state[4];
};

struct PCImage;

struct PCImageAttributes {
    int _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    int _field6;
    struct PCColorSpaceHandle _field7;
    unsigned int _field8;
    int _field9;
    _Bool _field10;
    void *_field11;
    unsigned long long _field12;
    void *_field13;
};

struct PCMatrix44Tmpl<double> {
    double _field1[4][4];
};

struct PCMutex {
    CDUnknownFunctionPointerType *_field1;
    struct _opaque_pthread_mutex_t _field2;
};

struct PCPtr<LiCamera> {
    struct LiCamera *_field1;
    struct PCSharedCount _field2;
};

struct PCPtr<OZRenderParams::SharedInfo> {
    struct SharedInfo *_field1;
    struct PCSharedCount _field2;
};

struct PCPtr<POVertexAsset> {
    struct POVertexAsset *_field1;
    struct PCSharedCount _field2;
};

struct PCQuat<double> {
    double _field1;
    PCVector3_457fd1f0 _field2;
};

struct PCRange<unsigned int> {
    unsigned int _field1;
    unsigned int _field2;
};

struct PCRay3<double> {
    PCVector3_457fd1f0 _field1;
    PCVector3_457fd1f0 _field2;
};

struct PCRect<double> {
    double _x;
    double _y;
    double _nx;
    double _ny;
};

struct PCRect<int> {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
};

struct PCRecursiveMutex {
    CDUnknownFunctionPointerType *_vptr$PCMutex;
    struct _opaque_pthread_mutex_t _Mutex;
};

struct PCSafeHandle;

struct PCSharedCount {
    struct PC_Sp_counted_base *_field1;
};

struct PCSpinLock {
    struct os_unfair_lock_s _field1;
};

struct PCString {
    struct __CFString *_field1;
};

struct PCTimeRange {
    CDStruct_198678f7 _field1;
    CDStruct_198678f7 _field2;
};

struct PCUUID {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
};

struct PCVector2<double> {
    double _x;
    double _y;
};

struct PCVector2<float> {
    float _field1;
    float _field2;
};

struct PCVector3<double> {
    double _x;
    double _y;
    double _z;
};

struct PCVector3<int>;

struct PCWeakCount {
    struct PC_Sp_counted_base *_field1;
};

struct PC_Sp_counted_base;

struct PGTexture;

struct POColor {
    float _x;
    float _y;
    float _z;
    float _w;
};

struct POMove3DOSC {
    int _field1;
    _Bool _field2;
    _Bool _field3;
    _Bool _field4[3];
    _Bool _field5;
};

struct PORotate3DOSC {
    int _field1;
    _Bool _field2;
    _Bool _field3[3];
    _Bool _field4;
    _Bool _field5;
    _Bool _field6;
    PCVector3_457fd1f0 _field7;
    PCVector3_457fd1f0 _field8;
    PCVector3_457fd1f0 _field9;
    PCVector3_457fd1f0 _field10;
    PCVector3_457fd1f0 _field11;
    PCQuat_de30948b _field12;
    double _field13;
    double _field14;
};

struct POScale3DImpl {
    CDUnknownFunctionPointerType *_field1;
    PCVector3_457fd1f0 _field2;
    struct POScale3DOSC *_field3;
};

struct POScale3DOSC;

struct POVertexAsset;

struct SharedInfo;

struct TXChannelAlignment {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelEnum _field19;
    struct OZChannelEnum _field20;
};

struct TXChannelFont {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
    _Bool _field18;
    struct OZChannelEnum _field19;
    struct OZChannelEnum _field20;
    struct PCString _field21;
    struct PCString _field22;
    int _field23;
};

struct TXCollectionEnum {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    struct OZChannelImpl *_field15;
    struct OZChannelImpl *_field16;
    struct OZChannelInfo *_field17;
    struct OZChannelInfo *_field18;
    struct OZCurve *_field19;
    struct __map_iterator<std::__1::__tree_iterator<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, std::__1::__tree_node<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, void *>*, long>> _field20;
    struct PCString _field21;
    struct vector<int, std::__1::allocator<int>> _field22;
    unsigned int _field23;
    struct PCString _field24;
    struct vector<PCString, std::__1::allocator<PCString>> _field25;
};

struct TXDirectionalRun;

struct TXDiscontinuousSelection {
    struct vector<unsigned int, std::__1::allocator<unsigned int>> _charOffsets;
};

struct TXGlyphTransformInfo {
    CDUnknownFunctionPointerType *_field1;
    shared_ptr_a6fe21d1 _field2;
    id _field3;
    struct OZRenderState _field4;
    id _field5;
    _Bool _field6;
};

struct TXLineMetrics;

struct TXParagraphStyle {
    CDUnknownFunctionPointerType *_field1;
    CDUnknownFunctionPointerType *_field2;
    struct vector<unsigned int, std::__1::allocator<unsigned int>> _field3;
    struct TXParagraphStyleFolder _field4;
    struct OZChannelEnum _field5;
    struct OZChannelEnum _field6;
    struct OZChannelDouble _field7;
    struct vector<TXTabStop *, std::__1::allocator<TXTabStop *>> _field8;
    unsigned long long _field9;
    unsigned long long _field10;
    _Bool _field11;
    unsigned int _field12;
    double _field13;
    struct vector<TXLineMetrics, std::__1::allocator<TXLineMetrics>> _field14;
    unsigned int *_field15;
    double _field16;
    struct PCHash128 _field17;
    struct TXTextLayout *_field18;
    struct __CFAttributedString *_field19;
    int _field20;
    struct vector<TXDirectionalRun, std::__1::allocator<TXDirectionalRun>> _field21;
    struct map<unsigned long, std::__1::pair<unsigned long, unsigned long>, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, std::__1::pair<unsigned long, unsigned long>>>> _field22;
    struct vector<FFTextSearchResult, std::__1::allocator<FFTextSearchResult>> _field23;
    _Bool _field24;
    struct PCString _field25;
    unsigned int _field26;
    _Bool _field27;
    struct PCRange<unsigned int> _field28;
    CDUnknownFunctionPointerType *_field29;
    struct PCWeakCount _field30;
    _Bool _field31;
};

struct TXParagraphStyleFolder {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    unsigned int _field4;
    struct PCString _field5;
    struct PCString *_field6;
    struct OZChannelFolder *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    void *_field10;
    struct __CFString *_field11;
    struct __CFString *_field12;
    struct __CFString *_field13;
    struct OZChannelTimeConverter *_field14;
    vector_b71873ec *_field15;
    unsigned int _field16;
    unsigned int _field17;
};

struct TXSelectionRange {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    unsigned int _field3;
};

struct TXTabStop {
    CDUnknownFunctionPointerType *_field1;
    struct OZChannelFolder _field2;
    struct OZChannelDouble _field3;
    struct OZChannelEnum _field4;
    struct TXParagraphStyle *_field5;
};

struct TXTextLayout;

struct TXTextObject;

struct TXTextSequenceBehavior;

struct TXTextStyle {
    CDUnknownFunctionPointerType *_field1;
    struct OZFactory *_field2;
    CDUnknownFunctionPointerType *_field3;
    struct PCSafeHandle *_field4;
    struct PCHash128 _field5;
    CDUnknownFunctionPointerType *_field6;
    struct weak_ptr<OZStyle> _field7;
    struct OZChannelObjectRoot _field8;
    struct OZChannelSeed _field9;
    struct vector<OZMaterialBase *, std::__1::allocator<OZMaterialBase *>> _field10;
    struct OZSceneNode *_field11;
    unsigned int _field12;
    struct shared_ptr<OZFontFace> _field13;
    struct TXCollectionEnum _field14;
    struct OZChannelEnum _field15;
    struct OZChannelEnum _field16;
    struct TXChannelFont _field17;
    struct OZChannelDouble _field18;
    struct OZChannelFolder _field19;
    struct OZChannelDouble _field20;
    struct OZChannelDouble _field21;
    struct OZChannelDouble _field22;
    struct OZChannelDouble _field23;
    struct OZChannelScale3D _field24;
    struct OZChannelPosition3D _field25;
    struct OZChannelRotation3D _field26;
    struct OZChannelAngle _field27;
    struct OZChannelBool _field28;
    struct OZChannelBool _field29;
    struct OZChannelPercent _field30;
    struct OZChannelDouble _field31;
    struct OZChannelFolder _field32;
    struct OZChannelEnum _field33;
    struct OZChannelColorNoAlpha _field34;
    struct OZChannelGradientWithAngle _field35;
    struct OZChannelImageWithOptions _field36;
    id _field37;
    struct OZChannelPercent _field38;
    struct OZChannel2D _field39;
    struct OZChannelDouble _field40;
    struct OZChannelQuad _field41;
    struct OZChannelFolder _field42;
    struct OZChannelEnum _field43;
    struct OZChannelColorNoAlpha _field44;
    struct OZChannelGradientWithAngle _field45;
    struct OZChannelImageWithOptions _field46;
    id _field47;
    struct OZChannelPercent _field48;
    struct OZChannel2D _field49;
    struct OZChannelDouble _field50;
    struct OZChannelScale _field51;
    struct OZChannelDouble _field52;
    struct OZChannelAngle _field53;
    struct OZChannelBool _field54;
    struct OZChannelQuad _field55;
    struct OZChannelFolder _field56;
    struct OZChannelEnum _field57;
    struct OZChannelColorNoAlpha _field58;
    struct OZChannelGradientWithAngle _field59;
    struct OZChannelImageWithOptions _field60;
    id _field61;
    struct OZChannelPercent _field62;
    struct OZChannel2D _field63;
    struct OZChannelDouble _field64;
    struct OZChannelDouble _field65;
    struct OZChannelEnum _field66;
    struct OZChannelQuad _field67;
    struct OZChannelBool _field68;
    struct OZChannelFolder _field69;
    struct OZChannelEnum _field70;
    struct OZChannelColorNoAlpha _field71;
    struct OZChannelGradientWithAngle _field72;
    struct OZChannelImageWithOptions _field73;
    id _field74;
    struct OZChannelPercent _field75;
    struct OZChannel2D _field76;
    struct OZChannelDouble _field77;
    struct OZChannelDouble _field78;
    struct OZChannelScale _field79;
    struct OZChannelPosition _field80;
    struct OZChannelEnum _field81;
    struct OZChannelQuad _field82;
    struct OZ3DExtrusionProperties _field83;
    struct OZGradientGroupShader *_field84;
    struct OZGradientGroupShader *_field85;
    struct OZGradientGroupShader *_field86;
    struct OZGradientGroupShader *_field87;
    unsigned int _field88;
    struct TXTextLayout *_field89;
    unsigned int _field90;
    struct OZChannelBool _field91;
    struct OZChannelBool _field92;
    struct OZChannelBool _field93;
    struct OZChannelPercent _field94;
    struct OZChannelPercent _field95;
    struct OZChannelFolder _field96;
    unsigned int _field97;
    unsigned int _field98;
    _Bool _field99;
    _Bool _field100;
    _Bool _field101;
    struct PCString _field102;
    struct shared_ptr<OZFontFace> _field103;
    struct PCMutex _field104;
};

struct TransformSet {
    unsigned long long _field1;
};

struct _CGLContextObject;

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

struct __CFString;

struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZPasteEntry *, void *>>> {
    unsigned long long _field1;
};

struct __list_iterator<OZSceneNode *, void *> {
    struct __list_node_base<OZSceneNode *, void *> *_field1;
};

struct __list_node_base<OZBehavior *, void *> {
    struct __list_node_base<OZBehavior *, void *> *_field1;
    struct __list_node_base<OZBehavior *, void *> *_field2;
};

struct __list_node_base<OZChannelBase *, void *> {
    struct __list_node_base<OZChannelBase *, void *> *_field1;
    struct __list_node_base<OZChannelBase *, void *> *_field2;
};

struct __list_node_base<OZEffect *, void *> {
    struct __list_node_base<OZEffect *, void *> *_field1;
    struct __list_node_base<OZEffect *, void *> *_field2;
};

struct __list_node_base<OZObjectManipulator *, void *> {
    struct __list_node_base<OZObjectManipulator *, void *> *_field1;
    struct __list_node_base<OZObjectManipulator *, void *> *_field2;
};

struct __list_node_base<OZObjectSelections *, void *> {
    struct __list_node_base<OZObjectSelections *, void *> *_field1;
    struct __list_node_base<OZObjectSelections *, void *> *_field2;
};

struct __list_node_base<OZPasteEntry *, void *> {
    struct __list_node_base<OZPasteEntry *, void *> *_field1;
    struct __list_node_base<OZPasteEntry *, void *> *_field2;
};

struct __list_node_base<OZSceneNode *, void *> {
    struct __list_node_base<OZSceneNode *, void *> *__prev_;
    struct __list_node_base<OZSceneNode *, void *> *__next_;
};

struct __list_node_base<OZSimulationBehavior *, void *> {
    struct __list_node_base<OZSimulationBehavior *, void *> *_field1;
    struct __list_node_base<OZSimulationBehavior *, void *> *_field2;
};

struct __list_node_base<OZTransformNode *, void *> {
    struct __list_node_base<OZTransformNode *, void *> *_field1;
    struct __list_node_base<OZTransformNode *, void *> *_field2;
};

struct __list_node_base<PCUUID, void *> {
    struct __list_node_base<PCUUID, void *> *_field1;
    struct __list_node_base<PCUUID, void *> *_field2;
};

struct __list_node_base<POPathSelection, void *> {
    struct __list_node_base<POPathSelection, void *> *_field1;
    struct __list_node_base<POPathSelection, void *> *_field2;
};

struct __list_node_base<std::__1::shared_ptr<TXTextStyle>, void *> {
    struct __list_node_base<std::__1::shared_ptr<TXTextStyle>, void *> *__prev_;
    struct __list_node_base<std::__1::shared_ptr<TXTextStyle>, void *> *__next_;
};

struct __map_iterator<std::__1::__tree_iterator<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, std::__1::__tree_node<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, void *>*, long>> {
    struct __tree_iterator<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, std::__1::__tree_node<std::__1::__value_type<PCString, std::__1::vector<PCString, std::__1::allocator<PCString>>>, void *>*, long> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
    } _field1;
};

struct __shared_weak_count;

struct __tree_end_node<std::__1::__tree_node_base<void *>*> {
    struct __tree_node_base<void *> *_field1;
};

struct _opaque_pthread_mutex_t {
    long long __sig;
    char __opaque[56];
};

struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> {
    struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> {
        struct __rep {
            union {
                struct __long {
                    unsigned long long _field1;
                    unsigned long long _field2;
                    char *_field3;
                } _field1;
                struct __short {
                    union {
                        unsigned char _field1;
                        char _field2;
                    } _field1;
                    char _field2[23];
                } _field2;
                struct __raw {
                    unsigned long long _field1[3];
                } _field3;
            } _field1;
        } _field1;
    } _field1;
};

struct list<OZBehavior *, std::__1::allocator<OZBehavior *>> {
    struct __list_node_base<OZBehavior *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZBehavior *, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<OZChannelBase *, std::__1::allocator<OZChannelBase *>> {
    struct __list_node_base<OZChannelBase *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZChannelBase *, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<OZEffect *, std::__1::allocator<OZEffect *>> {
    struct __list_node_base<OZEffect *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZEffect *, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<OZObjectManipulator *, std::__1::allocator<OZObjectManipulator *>> {
    struct __list_node_base<OZObjectManipulator *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZObjectManipulator *, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<OZObjectSelections *, std::__1::allocator<OZObjectSelections *>> {
    struct __list_node_base<OZObjectSelections *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZObjectSelections *, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<OZPasteEntry *, std::__1::allocator<OZPasteEntry *>> {
    struct __list_node_base<OZPasteEntry *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZPasteEntry *, void *>>> _field2;
};

struct list<OZSceneNode *, std::__1::allocator<OZSceneNode *>> {
    struct __list_node_base<OZSceneNode *, void *> __end_;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZSceneNode *, void *>>> {
        unsigned long long __value_;
    } __size_alloc_;
};

struct list<OZSimulationBehavior *, std::__1::allocator<OZSimulationBehavior *>> {
    struct __list_node_base<OZSimulationBehavior *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZSimulationBehavior *, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<OZTransformNode *, std::__1::allocator<OZTransformNode *>> {
    struct __list_node_base<OZTransformNode *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZTransformNode *, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<PCUUID, std::__1::allocator<PCUUID>> {
    struct __list_node_base<PCUUID, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<PCUUID, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<POPathSelection, std::__1::allocator<POPathSelection>> {
    struct __list_node_base<POPathSelection, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<POPathSelection, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<std::__1::shared_ptr<TXTextStyle>, std::__1::allocator<std::__1::shared_ptr<TXTextStyle>>> {
    struct __list_node_base<std::__1::shared_ptr<TXTextStyle>, void *> __end_;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<std::__1::shared_ptr<TXTextStyle>, void *>>> {
        unsigned long long __value_;
    } __size_alloc_;
};

struct map<PCHash128, LiTextureStoreToken, std::__1::less<PCHash128>, std::__1::allocator<std::__1::pair<const PCHash128, LiTextureStoreToken>>> {
    struct __tree<std::__1::__value_type<PCHash128, LiTextureStoreToken>, std::__1::__map_value_compare<PCHash128, std::__1::__value_type<PCHash128, LiTextureStoreToken>, std::__1::less<PCHash128>, true>, std::__1::allocator<std::__1::__value_type<PCHash128, LiTextureStoreToken>>> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<PCHash128, LiTextureStoreToken>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<PCHash128, std::__1::__value_type<PCHash128, LiTextureStoreToken>, std::__1::less<PCHash128>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<PCString, OZFontFamily *, std::__1::less<PCString>, std::__1::allocator<std::__1::pair<const PCString, OZFontFamily *>>> {
    struct __tree<std::__1::__value_type<PCString, OZFontFamily *>, std::__1::__map_value_compare<PCString, std::__1::__value_type<PCString, OZFontFamily *>, std::__1::less<PCString>, true>, std::__1::allocator<std::__1::__value_type<PCString, OZFontFamily *>>> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<PCString, OZFontFamily *>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<PCString, std::__1::__value_type<PCString, OZFontFamily *>, std::__1::less<PCString>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<int, int, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, int>>> {
    struct __tree<std::__1::__value_type<int, int>, std::__1::__map_value_compare<int, std::__1::__value_type<int, int>, std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, int>>> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<int, int>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<int, std::__1::__value_type<int, int>, std::__1::less<int>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<unsigned int, CMTime, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, CMTime>>> {
    struct __tree<std::__1::__value_type<unsigned int, CMTime>, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, CMTime>, std::__1::less<unsigned int>, true>, std::__1::allocator<std::__1::__value_type<unsigned int, CMTime>>> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<unsigned int, CMTime>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, CMTime>, std::__1::less<unsigned int>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<unsigned int, FFStreamVideo *, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, FFStreamVideo *>>>;

struct map<unsigned int, HGRef<HGNode>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, HGRef<HGNode>>>>;

struct map<unsigned int, PCBox<double>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, PCBox<double>>>> {
    struct __tree<std::__1::__value_type<unsigned int, PCBox<double>>, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, PCBox<double>>, std::__1::less<unsigned int>, true>, std::__1::allocator<std::__1::__value_type<unsigned int, PCBox<double>>>> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<unsigned int, PCBox<double>>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, PCBox<double>>, std::__1::less<unsigned int>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<unsigned int, PCMatrix44Tmpl<double>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, PCMatrix44Tmpl<double>>>> {
    struct __tree<std::__1::__value_type<unsigned int, PCMatrix44Tmpl<double>>, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, PCMatrix44Tmpl<double>>, std::__1::less<unsigned int>, true>, std::__1::allocator<std::__1::__value_type<unsigned int, PCMatrix44Tmpl<double>>>> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<unsigned int, PCMatrix44Tmpl<double>>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, PCMatrix44Tmpl<double>>, std::__1::less<unsigned int>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<unsigned int, PCRect<double>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, PCRect<double>>>> {
    struct __tree<std::__1::__value_type<unsigned int, PCRect<double>>, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, PCRect<double>>, std::__1::less<unsigned int>, true>, std::__1::allocator<std::__1::__value_type<unsigned int, PCRect<double>>>> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<unsigned int, PCRect<double>>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, PCRect<double>>, std::__1::less<unsigned int>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<unsigned int, PCVector3<double>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, PCVector3<double>>>> {
    struct __tree<std::__1::__value_type<unsigned int, PCVector3<double>>, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, PCVector3<double>>, std::__1::less<unsigned int>, true>, std::__1::allocator<std::__1::__value_type<unsigned int, PCVector3<double>>>> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<unsigned int, PCVector3<double>>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, PCVector3<double>>, std::__1::less<unsigned int>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<unsigned int, unsigned int, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, unsigned int>>> {
    struct __tree<std::__1::__value_type<unsigned int, unsigned int>, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, unsigned int>, std::__1::less<unsigned int>, true>, std::__1::allocator<std::__1::__value_type<unsigned int, unsigned int>>> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<unsigned int, unsigned int>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, unsigned int>, std::__1::less<unsigned int>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<unsigned long, std::__1::pair<unsigned long, unsigned long>, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, std::__1::pair<unsigned long, unsigned long>>>> {
    struct __tree<std::__1::__value_type<unsigned long, std::__1::pair<unsigned long, unsigned long>>, std::__1::__map_value_compare<unsigned long, std::__1::__value_type<unsigned long, std::__1::pair<unsigned long, unsigned long>>, std::__1::less<unsigned long>, true>, std::__1::allocator<std::__1::__value_type<unsigned long, std::__1::pair<unsigned long, unsigned long>>>> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<unsigned long, std::__1::pair<unsigned long, unsigned long>>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<unsigned long, std::__1::__value_type<unsigned long, std::__1::pair<unsigned long, unsigned long>>, std::__1::less<unsigned long>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct os_unfair_lock_s {
    unsigned int _field1;
};

struct set<OZElement *, std::__1::less<OZElement *>, std::__1::allocator<OZElement *>>;

struct set<int, std::__1::less<int>, std::__1::allocator<int>> {
    struct __tree<int, std::__1::less<int>, std::__1::allocator<int>> {
        struct __tree_end_node<std::__1::__tree_node_base<void *>*> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<int, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::less<int>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct shared_ptr<OZFontFace> {
    struct OZFontFace *_field1;
    struct __shared_weak_count *_field2;
};

struct shared_ptr<OZLibraryPresetsMap> {
    struct OZLibraryPresetsMap *_field1;
    struct __shared_weak_count *_field2;
};

struct shared_ptr<OZRenderResult> {
    struct OZRenderResult *_field1;
    struct __shared_weak_count *_field2;
};

struct shared_ptr<PCBitmap> {
    struct PCBitmap *_field1;
    struct __shared_weak_count *_field2;
};

struct shared_ptr<PCImage> {
    struct PCImage *_field1;
    struct __shared_weak_count *_field2;
};

struct shared_ptr<PGTexture> {
    struct PGTexture *_field1;
    struct __shared_weak_count *_field2;
};

struct shared_ptr<TXTextObject> {
    struct TXTextObject *__ptr_;
    struct __shared_weak_count *__cntrl_;
};

struct shared_ptr<TXTextStyle> {
    struct TXTextStyle *__ptr_;
    struct __shared_weak_count *__cntrl_;
};

struct shared_ptr<const HGComputeDevice> {
    struct HGComputeDevice *_field1;
    struct __shared_weak_count *_field2;
};

struct shared_ptr<const HGGPUComputeDevice> {
    struct HGGPUComputeDevice *_field1;
    struct __shared_weak_count *_field2;
};

struct timeval {
    long long tv_sec;
    int tv_usec;
};

struct vector<FFTextSearchResult, std::__1::allocator<FFTextSearchResult>> {
    struct FFTextSearchResult *_field1;
    struct FFTextSearchResult *_field2;
    struct __compressed_pair<FFTextSearchResult *, std::__1::allocator<FFTextSearchResult>> {
        struct FFTextSearchResult *_field1;
    } _field3;
};

struct vector<OZChannelBase *, std::__1::allocator<OZChannelBase *>> {
    struct OZChannelBase **_field1;
    struct OZChannelBase **_field2;
    struct __compressed_pair<OZChannelBase **, std::__1::allocator<OZChannelBase *>> {
        struct OZChannelBase **_field1;
    } _field3;
};

struct vector<OZChannelDouble *, std::__1::allocator<OZChannelDouble *>> {
    struct OZChannelDouble **_field1;
    struct OZChannelDouble **_field2;
    struct __compressed_pair<OZChannelDouble **, std::__1::allocator<OZChannelDouble *>> {
        struct OZChannelDouble **_field1;
    } _field3;
};

struct vector<OZChannelRef, std::__1::allocator<OZChannelRef>> {
    struct OZChannelRef *_field1;
    struct OZChannelRef *_field2;
    struct __compressed_pair<OZChannelRef *, std::__1::allocator<OZChannelRef>> {
        struct OZChannelRef *_field1;
    } _field3;
};

struct vector<OZMaterialBase *, std::__1::allocator<OZMaterialBase *>> {
    struct OZMaterialBase **_field1;
    struct OZMaterialBase **_field2;
    struct __compressed_pair<OZMaterialBase **, std::__1::allocator<OZMaterialBase *>> {
        struct OZMaterialBase **_field1;
    } _field3;
};

struct vector<PCQuat<double>, std::__1::allocator<PCQuat<double>>> {
    PCQuat_de30948b *__begin_;
    PCQuat_de30948b *__end_;
    struct __compressed_pair<PCQuat<double>*, std::__1::allocator<PCQuat<double>>> {
        PCQuat_de30948b *__value_;
    } __end_cap_;
};

struct vector<PCString, std::__1::allocator<PCString>> {
    struct PCString *_field1;
    struct PCString *_field2;
    struct __compressed_pair<PCString *, std::__1::allocator<PCString>> {
        struct PCString *_field1;
    } _field3;
};

struct vector<PCVector3<double>, std::__1::allocator<PCVector3<double>>> {
    PCVector3_457fd1f0 *_field1;
    PCVector3_457fd1f0 *_field2;
    struct __compressed_pair<PCVector3<double>*, std::__1::allocator<PCVector3<double>>> {
        PCVector3_457fd1f0 *_field1;
    } _field3;
};

struct vector<PCVector3<int>, std::__1::allocator<PCVector3<int>>> {
    struct PCVector3<int> *__begin_;
    struct PCVector3<int> *__end_;
    struct __compressed_pair<PCVector3<int>*, std::__1::allocator<PCVector3<int>>> {
        struct PCVector3<int> *__value_;
    } __end_cap_;
};

struct vector<PODrawableTexture *, std::__1::allocator<PODrawableTexture *>> {
    id *__begin_;
    id *__end_;
    struct __compressed_pair<PODrawableTexture **, std::__1::allocator<PODrawableTexture *>> {
        id *__value_;
    } __end_cap_;
};

struct vector<TXDirectionalRun, std::__1::allocator<TXDirectionalRun>> {
    struct TXDirectionalRun *_field1;
    struct TXDirectionalRun *_field2;
    struct __compressed_pair<TXDirectionalRun *, std::__1::allocator<TXDirectionalRun>> {
        struct TXDirectionalRun *_field1;
    } _field3;
};

struct vector<TXGlyphAnimationPathOnScreenControl *, std::__1::allocator<TXGlyphAnimationPathOnScreenControl *>> {
    id *_field1;
    id *_field2;
    struct __compressed_pair<TXGlyphAnimationPathOnScreenControl **, std::__1::allocator<TXGlyphAnimationPathOnScreenControl *>> {
        id *_field1;
    } _field3;
};

struct vector<TXLineMetrics, std::__1::allocator<TXLineMetrics>> {
    struct TXLineMetrics *_field1;
    struct TXLineMetrics *_field2;
    struct __compressed_pair<TXLineMetrics *, std::__1::allocator<TXLineMetrics>> {
        struct TXLineMetrics *_field1;
    } _field3;
};

struct vector<TXTabStop *, std::__1::allocator<TXTabStop *>> {
    struct TXTabStop **__begin_;
    struct TXTabStop **__end_;
    struct __compressed_pair<TXTabStop **, std::__1::allocator<TXTabStop *>> {
        struct TXTabStop **__value_;
    } __end_cap_;
};

struct vector<TXTextSequenceBehavior *, std::__1::allocator<TXTextSequenceBehavior *>> {
    struct TXTextSequenceBehavior **_field1;
    struct TXTextSequenceBehavior **_field2;
    struct __compressed_pair<TXTextSequenceBehavior **, std::__1::allocator<TXTextSequenceBehavior *>> {
        struct TXTextSequenceBehavior **_field1;
    } _field3;
};

struct vector<bool, std::__1::allocator<bool>> {
    unsigned long long *_field1;
    unsigned long long _field2;
    struct __compressed_pair<unsigned long, std::__1::allocator<unsigned long>> {
        unsigned long long _field1;
    } _field3;
};

struct vector<double, std::__1::allocator<double>> {
    double *_field1;
    double *_field2;
    struct __compressed_pair<double *, std::__1::allocator<double>> {
        double *_field1;
    } _field3;
};

struct vector<int, std::__1::allocator<int>> {
    int *_field1;
    int *_field2;
    struct __compressed_pair<int *, std::__1::allocator<int>> {
        int *_field1;
    } _field3;
};

struct vector<std::__1::shared_ptr<OZFontFace>, std::__1::allocator<std::__1::shared_ptr<OZFontFace>>> {
    struct shared_ptr<OZFontFace> *_field1;
    struct shared_ptr<OZFontFace> *_field2;
    struct __compressed_pair<std::__1::shared_ptr<OZFontFace>*, std::__1::allocator<std::__1::shared_ptr<OZFontFace>>> {
        struct shared_ptr<OZFontFace> *_field1;
    } _field3;
};

struct vector<unsigned int, std::__1::allocator<unsigned int>> {
    unsigned int *__begin_;
    unsigned int *__end_;
    struct __compressed_pair<unsigned int *, std::__1::allocator<unsigned int>> {
        unsigned int *__value_;
    } __end_cap_;
};

struct weak_ptr<OZStyle> {
    struct OZStyle *_field1;
    struct __shared_weak_count *_field2;
};

#pragma mark Typedef'd Structures

typedef struct {
    long long _field1;
    int _field2;
    unsigned int _field3;
    long long _field4;
} CDStruct_198678f7;

// Template types
typedef struct PCBox<double> {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
} PCBox_dd92ab54;

typedef struct PCMatrix44Tmpl<double> {
    double _field1[4][4];
} PCMatrix44Tmpl_93ed1289;

typedef struct PCPtr<POVertexAsset> {
    struct POVertexAsset *_field1;
    struct PCSharedCount _field2;
} PCPtr_ca97d389;

typedef struct PCQuat<double> {
    double _field1;
    PCVector3_457fd1f0 _field2;
} PCQuat_de30948b;

typedef struct PCRay3<double> {
    PCVector3_457fd1f0 _field1;
    PCVector3_457fd1f0 _field2;
} PCRay3_bdf7da08;

typedef struct PCRect<double> {
    double _x;
    double _y;
    double _nx;
    double _ny;
} PCRect_b601f9f3;

typedef struct PCVector2<double> {
    double _x;
    double _y;
} PCVector2_79efa81a;

typedef struct PCVector3<double> {
    double _x;
    double _y;
    double _z;
} PCVector3_457fd1f0;

typedef struct list<OZBehavior *, std::__1::allocator<OZBehavior *>> {
    struct __list_node_base<OZBehavior *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZBehavior *, void *>>> {
        unsigned long long _field1;
    } _field2;
} list_64b41211;

typedef struct list<OZChannelBase *, std::__1::allocator<OZChannelBase *>> {
    struct __list_node_base<OZChannelBase *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZChannelBase *, void *>>> {
        unsigned long long _field1;
    } _field2;
} list_9af5505e;

typedef struct list<OZObjectManipulator *, std::__1::allocator<OZObjectManipulator *>> {
    struct __list_node_base<OZObjectManipulator *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZObjectManipulator *, void *>>> {
        unsigned long long _field1;
    } _field2;
} list_5b338eba;

typedef struct list<OZSceneNode *, std::__1::allocator<OZSceneNode *>> {
    struct __list_node_base<OZSceneNode *, void *> __end_;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZSceneNode *, void *>>> {
        unsigned long long __value_;
    } __size_alloc_;
} list_e89ce44a;

typedef struct list<OZTransformNode *, std::__1::allocator<OZTransformNode *>> {
    struct __list_node_base<OZTransformNode *, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<OZTransformNode *, void *>>> {
        unsigned long long _field1;
    } _field2;
} list_87f2377f;

typedef struct list<POPathSelection, std::__1::allocator<POPathSelection>> {
    struct __list_node_base<POPathSelection, void *> _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<POPathSelection, void *>>> {
        unsigned long long _field1;
    } _field2;
} list_9b90a499;

typedef struct list<std::__1::shared_ptr<TXTextStyle>, std::__1::allocator<std::__1::shared_ptr<TXTextStyle>>> {
    struct __list_node_base<std::__1::shared_ptr<TXTextStyle>, void *> __end_;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<std::__1::shared_ptr<TXTextStyle>, void *>>> {
        unsigned long long __value_;
    } __size_alloc_;
} list_bb601910;

typedef struct shared_ptr<OZRenderResult> {
    struct OZRenderResult *_field1;
    struct __shared_weak_count *_field2;
} shared_ptr_3bf61ddf;

typedef struct shared_ptr<PCBitmap> {
    struct PCBitmap *_field1;
    struct __shared_weak_count *_field2;
} shared_ptr_1a5c5a10;

typedef struct shared_ptr<TXTextObject> {
    struct TXTextObject *__ptr_;
    struct __shared_weak_count *__cntrl_;
} shared_ptr_a6fe21d1;

typedef struct shared_ptr<TXTextStyle> {
    struct TXTextStyle *__ptr_;
    struct __shared_weak_count *__cntrl_;
} shared_ptr_e0e110e1;

typedef struct shared_ptr<const HGGPUComputeDevice> {
    struct HGGPUComputeDevice *_field1;
    struct __shared_weak_count *_field2;
} shared_ptr_d444a1e3;

typedef struct vector<OZChannelBase *, std::__1::allocator<OZChannelBase *>> {
    struct OZChannelBase **_field1;
    struct OZChannelBase **_field2;
    struct __compressed_pair<OZChannelBase **, std::__1::allocator<OZChannelBase *>> {
        struct OZChannelBase **_field1;
    } _field3;
} vector_b71873ec;

typedef struct vector<OZChannelDouble *, std::__1::allocator<OZChannelDouble *>> {
    struct OZChannelDouble **_field1;
    struct OZChannelDouble **_field2;
    struct __compressed_pair<OZChannelDouble **, std::__1::allocator<OZChannelDouble *>> {
        struct OZChannelDouble **_field1;
    } _field3;
} vector_358c9849;

typedef struct vector<PCVector3<double>, std::__1::allocator<PCVector3<double>>> {
    PCVector3_457fd1f0 *_field1;
    PCVector3_457fd1f0 *_field2;
    struct __compressed_pair<PCVector3<double>*, std::__1::allocator<PCVector3<double>>> {
        PCVector3_457fd1f0 *_field1;
    } _field3;
} vector_ced1dec3;

typedef struct vector<bool, std::__1::allocator<bool>> {
    unsigned long long *_field1;
    unsigned long long _field2;
    struct __compressed_pair<unsigned long, std::__1::allocator<unsigned long>> {
        unsigned long long _field1;
    } _field3;
} vector_a7cf9eda;

typedef struct vector<double, std::__1::allocator<double>> {
    double *_field1;
    double *_field2;
    struct __compressed_pair<double *, std::__1::allocator<double>> {
        double *_field1;
    } _field3;
} vector_8f06c10f;

