//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OZViewCtlrRoot.h"

@class LKButtonCell, NSBox, NSMatrix, NSView, OZAutoTextFormatController, OZAutoTextLayoutController, OZAutoTextStyleController, OZViewControllerGroup, PIBuildContext;

@interface OZTextInspectorController : OZViewCtlrRoot
{
    struct TXTextLayout *_text;
    list_6eff4338 *_styles;
    NSView *_pMainView;
    NSBox *_pBox;
    NSMatrix *_pMatrix;
    LKButtonCell *_formatButtonCell;
    LKButtonCell *_styleButtonCell;
    LKButtonCell *_layoutButtonCell;
    OZAutoTextFormatController *_pFormatController;
    OZAutoTextStyleController *_pStyleController;
    OZAutoTextLayoutController *_pLayoutController;
    OZViewControllerGroup *_pCurrController;
    BOOL _capturingChannels;
    list_699e9227 *_textList;
    PIBuildContext *_pContext;
}

- (id)initWithSceneNodes:(list_699e9227 *)arg1 viewCtlrDelegate:(id)arg2;
- (id)initWithSceneNodes:(list_699e9227 *)arg1 viewCtlrDelegate:(id)arg2 context:(id)arg3;
- (void)dealloc;
- (id)mainView;
- (id)getNSFontForStyle:(struct TXTextStyle *)arg1 time:(CDStruct_1b6d18a9)arg2;
- (id)createNSShadowForStyle:(struct TXTextStyle *)arg1 time:(CDStruct_1b6d18a9)arg2;
- (BOOL)isFontPanelVisible;
- (void)syncFontPanelIfNeeded:(BOOL)arg1;
- (void)notify:(unsigned int)arg1;
- (void)fontPanelWillOpen:(id)arg1;
- (void)textSelectionChanged:(id)arg1;
- (BOOL)isEnabled;
- (void)enable;
- (void)disable;
- (void)switchPane:(id)arg1;
- (void)aboutToChangeChannel:(struct OZChannelBase *)arg1 isFirstController:(BOOL)arg2;
- (void)channelChanged:(struct OZChannelBase *)arg1 time:(CDStruct_1b6d18a9)arg2 qualifiers:(int)arg3;
- (void)resetOrAddAssociatedStyle:(struct TXTextStyle *)arg1 reset:(BOOL)arg2;
- (void)setAssociatedStyle:(struct TXTextStyle *)arg1;
- (void)setAssociatedStyles:(list_6eff4338 *)arg1 force:(BOOL)arg2;
- (id)createFormatControllerWithSceneNode:(struct OZSceneNode *)arg1;
- (_Bool)useGlyphTool;

@end

