//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProInspector/OZViewController.h>

@class NSPopUpButton;

@interface TXAddRemoveChanController : OZViewController
{
    NSPopUpButton *_addPopUp;
    NSPopUpButton *_removePopUp;
    struct OZChannelBehavior *_chanBH;
    struct TXTextSequenceBehavior *_sequenceBH;
}

- (void)buildRemoveChanMenu:(struct OZChannelBehavior *)arg1;
- (void)buildAddChanMenu:(struct OZChannelBehavior *)arg1;
- (id)buildChannelMenu:(id)arg1 withItems:(const vector_b71873ec *)arg2 isAdd:(_Bool)arg3;
- (void)removeChannelCB:(id)arg1;
- (void)addChannelCB:(id)arg1;
- (void)delayedRelease;
- (void)delayedReleaseCB:(id)arg1;
- (struct OZObjectManipulator *)appliedToObject;
- (struct OZDocument *)document;
- (void)disable;
- (void)enable;
- (void)update;
- (id)initWithBehavior:(struct TXTextSequenceBehavior *)arg1 context:(id)arg2;

@end

