//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OZViewController.h"

#import "NSComboBoxDelegate.h"

@class NSComboBox, NSString;

@interface TXFamilyController : OZViewController <NSComboBoxDelegate>
{
    NSComboBox *_pComboBox;
    struct TXTextLayout *_text;
    _Bool _isDragging;
    _Bool _areAllChansEqual;
    _Bool _selectionDidChange;
    _Bool _aboutToChangeCalled;
}

- (void)comboBoxWillDismiss:(id)arg1;
- (void)comboBoxWillPopUp:(id)arg1;
- (void)comboBoxSelectionDidChange:(id)arg1;
- (void)comboBoxSelectionIsChanging:(id)arg1;
- (void)setChannelValue:(id)arg1;
- (void)changeChannel:(id)arg1;
- (void)_saveDefaultFont:(int)arg1;
- (void)disable;
- (void)enable;
- (void)update;
- (BOOL)areAllChannelsEqual;
- (BOOL)control:(id)arg1 isValidObject:(id)arg2;
- (void)selectItemAtIndex:(int)arg1;
- (void)updateComboBox:(BOOL)arg1;
- (void)collectionChanged:(id)arg1;
- (void)fontTypeChanged:(id)arg1;
- (void)dealloc;
- (void)setAssociatedTextLayout:(struct TXTextLayout *)arg1;
- (id)initWithChan:(struct OZChannelBase *)arg1 textLayout:(struct TXTextLayout *)arg2 context:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

