//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "POScale3D.h"

@interface TXGlyphScale3D : POScale3D
{
}

-     // Error parsing type: v24@0:8^{TXTextObject=^^?^^?I{vector<std::__1::shared_ptr<TXTextObject>, std::__1::allocator<std::__1::shared_ptr<TXTextObject> > >=^{shared_ptr<TXTextObject>}^{shared_ptr<TXTextObject>}{__compressed_pair<std::__1::shared_ptr<TXTextObject> *, std::__1::allocator<std::__1::shared_ptr<TXTextObject> > >=^{shared_ptr<TXTextObject>}}}{shared_ptr<TXTextObject>=^{TXTextObject}^{__shared_weak_count}}B{TXComposedCharacter={PCString=^{__CFString}}{?=qq}IIIII}S{PCString=^{__CFString}}SB{PCVector2<double>=dd}B{PCVector3<double>=ddd}{PCVector3<double>=ddd}{PCVector3<double>=ddd}{PCVector2<double>=dd}d^{TXTextStyleRun}{PCSharedMutex={mutex={_opaque_pthread_mutex_t=q[56c]}}{atomic<std::__1::__thread_id>=A{__thread_id}}I{vector<PCSharedMutex::ReaderInfo, std::__1::allocator<PCSharedMutex::ReaderInfo> >=^{ReaderInfo}^{ReaderInfo}{__compressed_pair<PCSharedMutex::ReaderInfo *, std::__1::allocator<PCSharedMutex::ReaderInfo> >=^{ReaderInfo}}}}^{TXTextureGlyph}BI{PCRect<double>=dddd}{PCRect<double>=dddd}{PCRect<double>=dddd}{PCRect<double>=dddd}fI{shared_ptr<OZFontFace>=^{OZFontFace}^{__shared_weak_count}}^{TXTextLayout}^{LiImageSource}dBBdIIB^{__CTFont}^^?{PCWeakCount=^{PC_Sp_counted_base}}B}16, name: drawBoundingBox:
- (void)draw;
-     // Error parsing type: v56@0:8^d16^d24^d32^{TXTextObject=^^?^^?I{vector<std::__1::shared_ptr<TXTextObject>, std::__1::allocator<std::__1::shared_ptr<TXTextObject> > >=^{shared_ptr<TXTextObject>}^{shared_ptr<TXTextObject>}{__compressed_pair<std::__1::shared_ptr<TXTextObject> *, std::__1::allocator<std::__1::shared_ptr<TXTextObject> > >=^{shared_ptr<TXTextObject>}}}{shared_ptr<TXTextObject>=^{TXTextObject}^{__shared_weak_count}}B{TXComposedCharacter={PCString=^{__CFString}}{?=qq}IIIII}S{PCString=^{__CFString}}SB{PCVector2<double>=dd}B{PCVector3<double>=ddd}{PCVector3<double>=ddd}{PCVector3<double>=ddd}{PCVector2<double>=dd}d^{TXTextStyleRun}{PCSharedMutex={mutex={_opaque_pthread_mutex_t=q[56c]}}{atomic<std::__1::__thread_id>=A{__thread_id}}I{vector<PCSharedMutex::ReaderInfo, std::__1::allocator<PCSharedMutex::ReaderInfo> >=^{ReaderInfo}^{ReaderInfo}{__compressed_pair<PCSharedMutex::ReaderInfo *, std::__1::allocator<PCSharedMutex::ReaderInfo> >=^{ReaderInfo}}}}^{TXTextureGlyph}BI{PCRect<double>=dddd}{PCRect<double>=dddd}{PCRect<double>=dddd}{PCRect<double>=dddd}fI{shared_ptr<OZFontFace>=^{OZFontFace}^{__shared_weak_count}}^{TXTextLayout}^{LiImageSource}dBBdIIB^{__CTFont}^^?{PCWeakCount=^{PC_Sp_counted_base}}B}40^{PCBox<double>=dddddd}48, name: getAnchorX:andAnchorY:andAnchorZ:forTextObject:usingBox:
- (struct POScale3DImpl *)makeNewScale3DImpl;
- (id)initWithHostDelegate:(id)arg1 andViewDelegate:(id)arg2 andObjectDelegate:(id)arg3 andChannel:(struct OZChannelBase *)arg4;

@end

