//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OZViewController.h"

#import "NSComboBoxDelegate.h"

@class NSComboBox, NSSlider, NSStepper, OZMoAnimIndicator;

@interface TXSliderComboController : OZViewController <NSComboBoxDelegate>
{
    NSSlider *_pSlider;
    NSComboBox *_pComboBox;
    OZMoAnimIndicator *_pAnim;
    NSStepper *_pStepper;
    _Bool _isDragging;
    _Bool _aboutToChangeCalled;
}

- (id)initWithChan:(struct OZChannelBase *)arg1 suffix:(const char *)arg2 context:(id)arg3;
- (void)startSliderAction:(id)arg1;
- (void)endSliderAction:(id)arg1;
- (void)update;
- (void)enable;
- (void)disable;
- (void)changeChannel:(id)arg1;
- (void)setChannelValue:(id)arg1;
- (id)comboBox;
- (void)comboBoxSelectionIsChanging:(id)arg1;
- (void)comboBoxSelectionDidChange:(id)arg1;

@end

