//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProInspector/OZViewControllerGroup.h>

@class LKSegmentedControl;

@interface TXVerticalAlignmentController : OZViewControllerGroup
{
    LKSegmentedControl *_segmentedControl;
    struct TXTextLayout *_text;
}

- (void)setIsEnabled:(BOOL)arg1;
- (void)update;
- (void)setValue:(int)arg1 forChannel:(struct OZChannelEnum *)arg2 atTime:(CDStruct_198678f7)arg3;
- (void)setChannelValue:(id)arg1;
- (id)initWithChan:(struct OZChannelBase *)arg1 context:(id)arg2;

@end

