//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@interface CALayer (OZCaarExport)
+ (id)layerWithElement:(struct OZElement *)arg1;
+ (id)keyPathForChannelPath:(id)arg1;
+ (id)keyPathForChannel:(struct OZChannel *)arg1;
- (id)setupLayerFromImageElement:(struct OZImageElement *)arg1;
- (id)setupLayerFromRotoshape:(struct OZRotoshape *)arg1;
- (id)adjustedValue:(id)arg1 fromChannel:(struct OZChannel *)arg2;
- (void)setupChannel:(struct OZChannel *)arg1;
- (void)setupTransformations:(struct OZChannelFolder *)arg1;
- (id)initWithElement:(struct OZElement *)arg1;
@end

