//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Ozone/FxDynamicParameterAPI-Protocol.h>

@protocol FxDynamicParameterAPI_v2 <FxDynamicParameterAPI>
- (BOOL)setAsDefaultsAtFxTime:(CDUnion_2516e51e)arg1 withError:(id *)arg2;
@end

