//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Ozone/OZChanEnumWithImagesController.h>

@class NSMutableArray;

@interface OZAlignBehaviorEnumController : OZChanEnumWithImagesController
{
    NSMutableArray *_imageNames;
    struct OZDocument *_document;
}

- (void)update;
- (void)setChannelValue:(id)arg1;
- (void)updatePopUpMenu:(BOOL)arg1 force:(BOOL)arg2;
- (void)notify:(unsigned int)arg1;
- (id)imageForMenuItemIndex:(int)arg1;
- (void)updateImageNames;
- (struct OZTransformNode *)associatedObject;
- (BOOL)hasLightOrCamera;
- (BOOL)hasText;
- (void)dealloc;
- (id)initWithChan:(struct OZChannelBase *)arg1 context:(id)arg2;

@end

