//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProInspector/OZChanEnumController.h>

#import <Ozone/NSMenuDelegate-Protocol.h>

@class NSString;

@interface OZChanEnumWithImagesController : OZChanEnumController <NSMenuDelegate>
{
}

- (id)imageForMenuItemIndex:(int)arg1;
- (void)setImagesForPopUp:(BOOL)arg1;
- (void)menuWillOpen:(id)arg1;
- (void)menuDidClose:(id)arg1;
- (void)updatePopUpMenu:(BOOL)arg1;
- (id)initWithChan:(struct OZChannelBase *)arg1 context:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

