//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface OZDFRTimerWithWeakTargetProxy : NSObject
{
    id _target;
    SEL _action;
}

+ (id)scheduledTimerProxy:(id)arg1 withTimeInterval:(double)arg2 userInfo:(id)arg3 repeats:(BOOL)arg4;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) id target; // @synthesize target=_target;
- (void)onTimer:(id)arg1;
- (void)dealloc;

@end

