//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Ozone/OZEnableFolderParamCtrl.h>

@class OZColorWell;

@interface OZEnableColorParamCtrl : OZEnableFolderParamCtrl
{
    OZColorWell *_pColorWell;
    struct OZChannelColorNoAlpha *_pColorChan;
}

- (void)setColorChannelValue:(id)arg1;
- (float)suggestedMinParamWidth;
- (void)disable;
- (void)enable;
- (void)update;
- (void)dealloc;
- (id)initWithChan:(struct OZChannelBase *)arg1 colorChan:(struct OZChannelColorNoAlpha *)arg2 context:(id)arg3;

@end

