//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Ozone/OZOverlay.h>

#import "OZRenderClient.h"

@class PGDrawableTexture;

@interface OZInsetViewOverlay : OZOverlay <OZRenderClient>
{
    shared_ptr_92745eb9 *_image;
    struct PCMutex *_imageLock;
    PGDrawableTexture *_cameraNameTexture;
    struct PCString _cameraName;
    BOOL _isSceneCamera;
    float _lastBackingScale;
    struct PCPtr<POMultiResMultiPartTexture> _border;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)renderNodeCancelled:(const CDStruct_1b6d18a9 *)arg1 userData:(void *)arg2;
- (void)renderNodeFinished:(struct OZHGRenderNode *)arg1 result:(const shared_ptr_7e020609 *)arg2;
- (id)getCursorWithEvent:(id)arg1;
- (void)notify:(unsigned int)arg1;
- (void)renderFrame;
- (void)updateTip;
- (void)draw;
- (struct CGSize)getPreviewSizeForViewSize:(struct CGSize)arg1 andScene:(struct OZScene *)arg2 returningScale:(float *)arg3;
- (void)drawGradientRectX:(float)arg1 y:(float)arg2 width:(float)arg3 height:(float)arg4 alpha:(float)arg5 direction:(int)arg6;
- (void)drawArcQuadrant:(int)arg1 x:(float)arg2 y:(float)arg3 radius:(float)arg4;
- (void)drawGradArcQuadrant:(int)arg1 x:(float)arg2 y:(float)arg3 radius:(float)arg4 alpha:(float)arg5;
- (void)willBeRemoved;
- (void)dealloc;
- (BOOL)is3DOSC;
- (int)getDrawingOrder;
- (id)initWithHostDelegate:(id)arg1 andViewDelegate:(id)arg2 andObjectDelegate:(id)arg3 andChannel:(struct OZChannelBase *)arg4;

@end

