//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Ozone/OZEnableCell.h>

@interface OZLayerEnableCell : OZEnableCell
{
    BOOL _showCell;
}

- (void)setNextState;
- (unsigned long long)hitTestForEvent:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (long long)trackingRow;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)setShowValue:(BOOL)arg1;
- (id)initTextCell:(id)arg1;

@end

