//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProShapes/OZVerticesController.h>

@interface OZMotionPathVerticesController : OZVerticesController
{
}

- (id)newVertexController:(struct OZChannelBase *)arg1 index:(unsigned int)arg2 context:(id)arg3;
- (unsigned int)getNumberOfVertices:(struct OZChannelBase *)arg1;

@end

