//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LKTableView.h"

@class OZOpticalFlowProgressController;

@interface OZOpticalFlowTableView : LKTableView
{
    OZOpticalFlowProgressController *_controller;
}

- (void)delete:(id)arg1;
- (id)dragImageForRowsWithIndexes:(id)arg1 tableColumns:(id)arg2 event:(id)arg3 offset:(struct CGPoint *)arg4;
- (BOOL)canDragRowsWithIndexes:(id)arg1 atPoint:(struct CGPoint)arg2;
- (unsigned long long)draggingSourceOperationMaskForLocal:(BOOL)arg1;
- (void)mouseDown:(id)arg1;
- (struct CGRect)getStopRectForRow:(unsigned int)arg1;
- (void)setController:(id)arg1;

@end

