//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TMBrowserOutlineItem.h"

@class NSString;

@interface TMTheme : NSObject <TMBrowserOutlineItem>
{
    NSString *_name;
    BOOL _isSystemTheme;
    BOOL _isTemporaryTheme;
}

- (id)initWithName:(id)arg1 isSystemTheme:(BOOL)arg2;
- (void)dealloc;
- (long long)compare:(id)arg1;
- (id)title;
- (BOOL)canAddToItem;
- (BOOL)canRemoveItem;
@property(nonatomic) BOOL isTemporaryTheme; // @synthesize isTemporaryTheme=_isTemporaryTheme;
@property(nonatomic) BOOL isSystemTheme; // @synthesize isSystemTheme=_isSystemTheme;
@property(nonatomic) NSString *name; // @synthesize name=_name;

@end

