//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TryCandidateData : NSObject
{
    NSString *_pFilePath;
    struct OZFootage *_pFootage;
    int _result;
}

- (id)initWithFilePath:(id)arg1 footage:(struct OZFootage *)arg2;
- (int)result;
- (void)setResult:(int)arg1;
- (id)filePath;
- (struct OZFootage *)footage;

@end

