//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LKSegmentedScrubber.h"

@interface PISegmentedScrubber : LKSegmentedScrubber
{
}

+ (void)initialize;
- (void)setIsAutokeyTintEnabled:(BOOL)arg1;
- (BOOL)isAutokeyTintEnabled;

@end

