//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProChannel/CHCompoundChannel.h>

@interface CHChannelHistogram : CHCompoundChannel
{
}

+ (struct OZChannelBase *)_newOZChannelWithName:(id)arg1 channelID:(unsigned int)arg2 flags:(unsigned int)arg3;
+ (BOOL)_isOZChannelClassOK:(struct OZChannelBase *)arg1;
- (double)gammaValueAtTime:(CDStruct_198678f7)arg1 forHistogramChannel:(int)arg2;
- (double)whiteOutValueAtTime:(CDStruct_198678f7)arg1 forHistogramChannel:(int)arg2;
- (double)whiteInValueAtTime:(CDStruct_198678f7)arg1 forHistogramChannel:(int)arg2;
- (double)blackOutValueAtTime:(CDStruct_198678f7)arg1 forHistogramChannel:(int)arg2;
- (double)blackInValueAtTime:(CDStruct_198678f7)arg1 forHistogramChannel:(int)arg2;
- (id)gammaChannelForHistogramChannel:(unsigned int)arg1;
- (id)whiteOutChannelForHistogramChannel:(unsigned int)arg1;
- (id)whiteInChannelForHistogramChannel:(unsigned int)arg1;
- (id)blackOutChannelForHistogramChannel:(unsigned int)arg1;
- (id)blackInChannelForHistogramChannel:(unsigned int)arg1;
- (id)selectedChannel;
- (struct OZChannelHistogram *)ozChannel;

@end

