//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AVAssetReaderOutput.h"

@class AVAssetTrack, AVSampleBufferGenerator, AVSampleCursor, MIOOP1aReader, NSConditionLock;

__attribute__((visibility("hidden")))
@interface MIOOP1aReaderTrackOutput : AVAssetReaderOutput
{
    BOOL mIsEssenceTrack;
    CDStruct_1b6d18a9 mDecodeStart;
    CDStruct_1b6d18a9 mDecodeEnd;
    int mStatus;
    long long mRequestedChunk;
    AVSampleBufferGenerator *mSampleGenerator;
    MIOOP1aReader *mAssetReader;
    AVAssetTrack *mAssetTrack;
    AVSampleCursor *mSampleCursor;
    NSConditionLock *mCacheLock;
    void *mSampleBufferList;
}

+ (id)assetReaderTrackOutputWithTrack:(id)arg1;
@property list_4609f400 *sampleBufferList; // @synthesize sampleBufferList=mSampleBufferList;
@property(retain) AVSampleCursor *sampleCursor; // @synthesize sampleCursor=mSampleCursor;
@property(retain) AVAssetTrack *assetTrack; // @synthesize assetTrack=mAssetTrack;
@property(retain) MIOOP1aReader *assetReader; // @synthesize assetReader=mAssetReader;
@property(retain) AVSampleBufferGenerator *sampleGenerator; // @synthesize sampleGenerator=mSampleGenerator;
@property(readonly) int status; // @synthesize status=mStatus;
@property(nonatomic) CDStruct_1b6d18a9 decodeEnd; // @synthesize decodeEnd=mDecodeEnd;
@property(nonatomic) CDStruct_1b6d18a9 decodeStart; // @synthesize decodeStart=mDecodeStart;
@property(readonly) BOOL isEssenceTrack; // @synthesize isEssenceTrack=mIsEssenceTrack;
- (id)mediaType;
- (struct opaqueCMSampleBuffer *)copyNextSampleBuffer;
- (BOOL)stepCoursorByTime:(CDStruct_1b6d18a9)arg1;
- (void)addSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 lastSampleBuffer:(BOOL)arg2;
- (void)finalize;
- (void)dealloc;
- (id)initAssetReaderTrackOutputWithTrack:(id)arg1;

@end

