//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProColorWell.h"

@interface LKColorWell : NSProColorWell
{
}

- (id)_transientPickerSwatchBackgroundFacet;
- (id)_transientPickerTextBoxFacet;
- (id)_transientPickerImageFacet;
- (id)_transientPickerButtonFacet;
- (id)_transientPickerSeparatorFacet;
- (id)_transientPickerColorWellFacet;
- (id)_colorSwatchBezelFacet;
- (id)_colorWellBezelFacet;

@end

