//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <LunaKit/LKViewModule.h>

@class LKInspector, NSArray, NSMutableDictionary, NSScrollView, NSTextField;

@interface LKInspectorModule : LKViewModule
{
    NSTextField *_blankInspectorTextField;
    NSScrollView *_scrollView;
    LKViewModule *_currentModule;
    NSArray *_currentInspectedItems;
    LKInspector *_currentInspector;
    NSMutableDictionary *_registeredInspectors;
    unsigned int _containerMoved:1;
    unsigned int _reserved:31;
    void *_reserved8;
}

+ (id)defaultModuleNibName;
- (void)moduleDidBecomeVisible:(id)arg1;
- (void)moduleDidUnhide;
- (void)moduleDidHide;
- (id)scrollView;
- (id)blankInspectorTextField;
- (void)itemsChanged:(id)arg1;
- (void)windowDidUpdate:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (id)submoduleLayoutArray;
- (void)inspectModule:(id)arg1 onlyIfNeeded:(BOOL)arg2;
- (void)module:(id)arg1 willRemoveSubmodule:(id)arg2;
- (void)module:(id)arg1 didAddSubmodule:(id)arg2;
- (void)moduleViewWillBeRemoved:(id)arg1;
- (void)moduleViewWasInstalled:(id)arg1;
- (void)containerDidMove;
- (void)containerWillMove;
- (BOOL)_contentsJustMovedToAnotherContainer;
- (id)_activeModule;
- (id)currentInspector;
- (void)setCurrentInspector:(id)arg1;
- (id)currentInspectedItems;
- (void)setCurrentInspectedItems:(id)arg1;
- (id)currentModule;
- (void)setCurrentModule:(id)arg1;
- (void)hide:(id)arg1;
- (id)inspectorForClass:(id)arg1;
- (id)_registeredInspectors;
- (void)_registerInspector:(id)arg1;
- (void)_inspectorWasCreated:(id)arg1;
- (void)_layoutDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithModuleNibName:(id)arg1;

@end

