//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSMutableSet;

@interface LKModuleRegistry : NSObject
{
    NSMutableDictionary *_contextModuleMap;
    NSMutableSet *_registeredObjects;
}

+ (id)sharedInstance;
- (BOOL)isModuleRegistered:(id)arg1;
- (id)registeredModulesInContext:(id)arg1;
- (void)unregisterModulesInContext:(id)arg1;
- (void)unregisterModule:(id)arg1 inContext:(id)arg2;
- (void)registerModule:(id)arg1 inContext:(id)arg2;
- (id)moduleWithIdentifier:(id)arg1 inContext:(id)arg2;
- (id)moduleInAnyContextWithIdentifier:(id)arg1;
- (void)dealloc;
- (id)init;

@end

