//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPopUpButtonCell.h"

@interface LKPopUpButtonCell : NSPopUpButtonCell
{
    unsigned int hasSetTintIndex:1;
}

+ (double)_customArrowSpacingForControlSize:(unsigned long long)arg1;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (struct CGRect)drawingRectForBounds:(struct CGRect)arg1;
- (void)dealloc;

@end

