//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProSegmentedScrubberCell.h"

@interface LKSegmentedScrubberCell : NSProSegmentedScrubberCell
{
}

- (id)_scrubbingArrowsFacetForStyle:(long long)arg1;
- (id)_stepperArrowsFacet;
- (id)_caretFacet;
- (id)_baseFacet;
- (id)_squareBezelFacet;

@end

