//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSImage;

@interface LKSplashView : NSView
{
    NSImage *_aboutImage;
    NSImage *_splashImage;
    BOOL _isSplash;
}

@property BOOL isSplash; // @synthesize isSplash=_isSplash;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

