//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface LunaKit : NSObject
{
}

+ (BOOL)hasHUDContextMenus;
+ (BOOL)useSelectedSegmentedControlTextHUDColor;
+ (BOOL)hasHUDMenus;
+ (unsigned int)smoothingStyleIsUsed:(char *)arg1 forFont:(id)arg2;
+ (void)install;
+ (BOOL)_wantsConsumerLook;
+ (void)initialize;
+ (BOOL)_isInIBCocoaSimulator;
+ (id)_proToolbarBAppearanceOff;
+ (id)_proToolbarBAppearanceOn;
+ (id)headerAppearanceLight;
+ (id)viewerAppearance;
+ (id)revealedAppearance;
+ (id)proToolbarAppearance;
+ (id)proTokenAppearance;
+ (id)proInspectorAppearance;
+ (id)_MOTIONHUDAppearance;
+ (id)HUDAppearance;
+ (id)mainAppearance;

@end

