//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FFColorSelectionOSCDelegate.h"

@class FFEffectStack, FFMaskBase, NSString;

__attribute__((visibility("hidden")))
@interface _FFColorIsolationDelegate : NSObject <FFColorSelectionOSCDelegate>
{
    FFEffectStack *_effectStack;
    FFMaskBase *_mask;
}

+ (id)sharedDelegate;
@property(nonatomic) FFMaskBase *mask; // @synthesize mask=_mask;
@property(nonatomic) FFEffectStack *effectStack; // @synthesize effectStack=_effectStack;
@property(readonly, getter=wantsSaturatedResult) BOOL wantsSaturatedResult;
- (int)HDRDelinearizedForWorkingSpace:(int)arg1;
- (long long)colorSelectionOSCSampleModel;
- (id)effect;
- (long long)effectCountForReference;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

