//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/_FFInspectorHeaderSubController.h>

@class LKTextField, NSString;

__attribute__((visibility("hidden")))
@interface _FFInspectorLibraryNameController : _FFInspectorHeaderSubController
{
    NSString *_libraryName;
    int _colorProcessingMode;
    LKTextField *_libraryNameField;
    LKTextField *_libraryColorProcessingField;
}

- (id)view;
- (void)setLibraryColorProcessingMode:(int)arg1;
- (void)_updateLibraryColorProcessingModeTextField;
- (void)setLibraryName:(id)arg1;
- (void)_updateLibraryNameTextField;
- (void)dealloc;
- (id)init;

@end

