//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

#import <Flexo/NSDraggingDestination-Protocol.h>

@class FFInspectorContainerController, NSArray, NSDraggingSession, NSIndexSet, NSLayoutConstraint, NSString;

__attribute__((visibility("hidden")))
@interface _FFInspectorContainerStackView : NSView <NSDraggingDestination>
{
    FFInspectorContainerController *_delegate;
    float _verticalClippingResistancePriority;
    float _verticalHuggingPriority;
    double _spacing;
    NSArray *_cachedViewOrder;
    struct {
        NSDraggingSession *session;
        NSIndexSet *rowIndexes;
        int insertionLocation;
        long long insertionRowIndex;
        double insertionCoord;
        long long acceptingRowIndex;
    } _draggingInfo;
    NSLayoutConstraint *_topConstraint;
    NSLayoutConstraint *_bottomConstraint;
}

@property(readonly, nonatomic) FFInspectorContainerController *delegate; // @synthesize delegate=_delegate;
- (void)draggingEnded:(id)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (void)_deselectLastAcceptingRowIndex;
- (id)_acceptingRowIndexView;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)setSpacing:(double)arg1;
- (void)setDistribution:(long long)arg1;
- (void)setOrientation:(long long)arg1;
- (float)huggingPriorityForOrientation:(long long)arg1;
- (void)setHuggingPriority:(float)arg1 forOrientation:(long long)arg2;
- (float)clippingResistancePriorityForOrientation:(long long)arg1;
- (void)setClippingResistancePriority:(float)arg1 forOrientation:(long long)arg2;
- (id)views;
- (void)removeView:(id)arg1;
- (void)insertView:(id)arg1 atIndex:(unsigned long long)arg2 inGravity:(long long)arg3;
- (void)setViews:(id)arg1 inGravity:(long long)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)draggingSession:(id)arg1 willBeginAtRow:(long long)arg2;
- (id)sourceForDraggingSession;
- (id)identifierForPasteboardWriterAtRow:(long long)arg1;
- (BOOL)isDraggingInSession;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

