//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFInspectorBaseController.h>

@class FFInspectorModuleProjectSharing, LKPopUpButton, LKTextField, NSDate, NSString, NSView;

__attribute__((visibility("hidden")))
@interface _FFProjectSharingExportController : FFInspectorBaseController
{
    FFInspectorModuleProjectSharing *_delegate;
    NSString *_shareKind;
    NSDate *_publishedDate;
    NSString *_publishedString;
    NSString *_location;
    NSView *_rowView;
    LKTextField *_publishedField;
    LKPopUpButton *_actionButton;
}

@property(copy, nonatomic) NSString *shareKind; // @synthesize shareKind=_shareKind;
@property(nonatomic) FFInspectorModuleProjectSharing *delegate; // @synthesize delegate=_delegate;
- (id)view;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)visitSharedItem:(id)arg1;
- (void)tellAFriendOfSharedItem:(id)arg1;
- (void)revealInFinder:(id)arg1;
@property(copy, nonatomic) NSString *location; // @dynamic location;
- (void)_resyncHiddenStates;
- (id)_menuForSocialMedia;
- (id)_menuForLocalFile;
@property(copy, nonatomic) NSDate *publishedString; // @dynamic publishedString;
@property(copy, nonatomic) NSDate *publishedDate; // @dynamic publishedDate;
- (void)_updatePublishedField;
- (void)dealloc;

@end

