//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Flexo/FFREDRAWPropertyChangeController-Protocol.h>

@class FFSharedLock, NSString;

__attribute__((visibility("hidden")))
@interface _REDRAWPropertyChangeController : NSObject <FFREDRAWPropertyChangeController>
{
    FFSharedLock *_modelLockingObject;
    CDUnknownBlockType _setter;
    CDUnknownBlockType _invalidateBlock;
}

- (CDUnknownBlockType)REDRAWPropertySetter;
- (void)didMakeChanges;
- (void)willMakeChanges;
- (void)endPropertyChanges;
- (void)beginPropertyChanges;
- (void)dealloc;
- (id)initWithModelLockingObject:(id)arg1 setterBlock:(CDUnknownBlockType)arg2 invalidateBlock:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

