//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class FFAddEffectComponentChooserComponentRoleView;

__attribute__((visibility("hidden")))
@interface FFAddEffectComponentChooserComponentTableCellView : NSTableCellView
{
    FFAddEffectComponentChooserComponentRoleView *_roleView;
}

@property FFAddEffectComponentChooserComponentRoleView *roleView; // @synthesize roleView=_roleView;

@end

