//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class FFAnchoredCollection, NSArray;

@interface FFAlignEditsOperation : NSOperation
{
    NSArray *_edits;
    FFAnchoredCollection *_container;
    CDStruct_1b6d18a9 _sampleDuration;
}

+ (void)alignEdits:(id)arg1;
@property(nonatomic) CDStruct_1b6d18a9 sampleDuration; // @synthesize sampleDuration=_sampleDuration;
@property(retain, nonatomic) FFAnchoredCollection *container; // @synthesize container=_container;
@property(readonly, nonatomic) NSArray *edits; // @synthesize edits=_edits;
- (void)alignEdit:(id)arg1;
- (void)findTargetContainerAndSampleDuration;
- (void)main;
- (void)dealloc;
- (id)initWithEdits:(id)arg1;

@end

