//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class TLKLayoutDatabase;

__attribute__((visibility("hidden")))
@interface FFAlignItemLayerTitleToVisibleRectOperation : NSOperation
{
    TLKLayoutDatabase *_layoutDatabase;
}

@property(retain, nonatomic) TLKLayoutDatabase *layoutDatabase; // @synthesize layoutDatabase=_layoutDatabase;
- (void)updateTextLayerForItemLayer:(id)arg1 withBadgeAreaBounds:(const struct CGRect *)arg2;
- (void)updateBadgeLayersForItemLayer:(id)arg1 withBadgeAreaBounds:(struct CGRect *)arg2;
- (void)alignTitleAreaForItemLayer:(id)arg1;
- (void)main;
- (void)dealloc;

@end

