//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFAnchoredSequenceSettingsModule.h>

@class FFVideoProps;

__attribute__((visibility("hidden")))
@interface FFAnchoredSequenceConfirmSettingsModule : FFAnchoredSequenceSettingsModule
{
    BOOL _suggestChoosingCustom;
    FFVideoProps *_bestGuess;
}

- (int)closingWithCode:(int)arg1;
- (BOOL)loadView;
- (void)changeVideoFormat:(id)arg1;
- (void)setBestGuess:(id)arg1;
- (void)setSuggestChoosingCustomText:(BOOL)arg1;
- (BOOL)isEmptyProject;
- (void)dealloc;
- (id)initWithProvider:(id)arg1;

@end

