//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FFBackgroundTaskTarget.h"

@class FFAnchoredSequence, FigTimeRangeAndObject, NSMutableArray, NSSet;

@interface FFAutoStackIngestTask : NSObject <FFBackgroundTaskTarget>
{
    NSSet *_rangesAndObjectsToSynchronize;
    FigTimeRangeAndObject *_referenceRangeAndObject;
    FFAnchoredSequence *_targetSequence;
    NSSet *_newItems;
    NSSet *_existingItems;
    NSMutableArray *_itemsToMerge;
    NSMutableArray *_offsetsToMerge;
}

+ (double)ZCRCompareClip:(id)arg1 toClip:(id)arg2 onTask:(id)arg3;
+ (_Bool)_spectrallySimilar:(id)arg1 andClip:(id)arg2 wasStereo:(BOOL)arg3 onTask:(id)arg4;
+ (double)getRMSFor:(id)arg1 onTask:(id)arg2;
+ (_Bool)checkCancelOrPauseOn:(id)arg1;
+ (BOOL)checkHasAudio:(id)arg1;
- (id)librariesInUse;
- (id)assetsChanging;
- (id)assetsInUse;
- (void)canceledTask:(id)arg1;
- (void)dealloc;
- (id)initWithRangesAndObjects:(id)arg1 referenceRangeAndObject:(id)arg2 targetSequence:(id)arg3;

@end

