//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FFAnchoredObject;

@interface FFAudioMatchRequest : NSObject
{
    FFAnchoredObject *_object;
    int _pass;
}

@property int pass; // @synthesize pass=_pass;
@property(retain) FFAnchoredObject *object; // @synthesize object=_object;
- (void)dealloc;
- (id)initWithRequestObject:(id)arg1 andPass:(int)arg2;

@end

