//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFMatchTool.h>

@interface FFAudioMatchTool : FFMatchTool
{
}

+ (id)cursor;
+ (id)displayName;
+ (void)initialize;
+ (id)TLKEventHandlerID;
- (void)becomeActiveTool;
- (void)didRemoveAsHandlerForTimeline:(id)arg1;
- (void)willSetAsHandlerForTimeline:(id)arg1;

@end

