//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface FFAudioComponentsConfigObject : NSObject
{
    NSArray *m_componentSources;
}

- (id)orphanedComponentSources;
- (void)updateExpandState:(int)arg1;
- (int)expandState;
- (void)setRoleComponentsMode:(int)arg1;
- (int)roleComponentsMode;
- (BOOL)supportsRoleComponentsModeConfig;
- (id)layoutForReset;
- (BOOL)canResetLayout;
- (void)refreshObject;
- (void)updateToLayout:(id)arg1;
- (id)newCurrentLayoutFromObject;
- (BOOL)isAudioComponentSource:(id)arg1 associatedWith:(id)arg2;
- (int)numAvailableChannels;
- (BOOL)supportsChannelComponentsConfig;
- (id)componentSources;
- (id)backingAnchoredObject;
- (id)skimmableObject;
- (id)displayName;
- (void)dealloc;

@end

