//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFAudioComponentsLayoutMap.h>

@class NSSet;

__attribute__((visibility("hidden")))
@interface FFAudioObjectComponentsLayoutMap : FFAudioComponentsLayoutMap
{
    NSSet *_cachedRoles;
}

- (id)referenceRolesForKey:(id)arg1 layoutItemKey:(id)arg2;
- (id)rolesForKey:(id)arg1 layoutItemKey:(id)arg2;
- (id)localRoleToPreserveForKey:(id)arg1;
- (void)setRole:(id)arg1 forKey:(id)arg2;
- (id)rolesForKey:(id)arg1;
- (id)_rolesForKey:(id)arg1 localOnly:(BOOL)arg2 findRoleToPreserve:(BOOL)arg3;
- (id)_rolesForKey:(id)arg1 layoutItemKey:(id)arg2 localOnly:(BOOL)arg3;
- (void)setRole:(id)arg1;
- (id)roles;
- (void)_didChangeAudioComponentsLayoutMap:(id)arg1;
- (id)copyWithDelegate:(id)arg1;
- (void)demandAudioComponentSourceForKey:(id)arg1 layoutItemKey:(id)arg2;
- (id)newAudioComponentSourceForKey:(id)arg1 layoutItemKey:(id)arg2;
- (BOOL)hasEnabledLayoutItems;
- (BOOL)isIntrinsicLayoutForKey:(id)arg1;
- (BOOL)isIntrinsicObjectLayout:(id)arg1;
- (CDStruct_bdcb2b0d)audioMD5:(int)arg1;
- (CDStruct_bdcb2b0d)_audioMD5:(int)arg1 forLayout:(id)arg2;
- (id)demandMutableObjectLayoutItemForKey:(id)arg1 layoutItemKey:(id)arg2;
- (void)notifyDelegateRolesChanged;
- (void)_clearCachedRoles;
- (void)dealloc;

@end

