//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FFBackgroundTaskTarget.h"

@class FFAnchoredObject, FFAudioMatchRequest, FFAudioUnitAnalyzingEffect, NSMutableArray, NSMutableSet;

@interface FFAudioMatchTask : NSObject <FFBackgroundTaskTarget>
{
    FFAnchoredObject *_object;
    NSMutableArray *_pendingRequests;
    NSMutableSet *_cancelledRequests;
    FFAudioMatchRequest *_currentRequest;
    FFAudioMatchRequest *_currentObjectToMatchRequest;
    BOOL _taskRunning;
    BOOL _taskCancelled;
    CDUnknownBlockType _completionBlock;
    struct NSDictionary *_matchEffectStateForObject;
    FFAudioUnitAnalyzingEffect *_analyzedMatchEffect;
}

@property(readonly, nonatomic) FFAnchoredObject *object; // @synthesize object=_object;
- (id)librariesInUse:(id)arg1;
- (id)assetsInUse:(id)arg1;
- (void)canceledTask:(id)arg1;
- (id)_taskObjects;
- (void)_backgroundTaskCompleted;
- (void)_dispatchBackgroundTask;
- (BOOL)_isCurrentRequestCancelled;
- (BOOL)_isRequestCancelled:(id)arg1;
- (id)popRequest;
- (void)_addRequest:(id)arg1;
- (void)_performCompletionBlock;
- (void)setCompletionBlock:(CDUnknownBlockType)arg1;
- (BOOL)isMatchingForEffectStack:(id)arg1;
- (void)setObjectToMatch:(id)arg1;
- (void)_matchRunLoop:(id)arg1 onTask:(id)arg2;
- (void)match:(id)arg1 forPass:(int)arg2 onTask:(id)arg3;
- (void)_setMatchParameterOnChannelFolder:(id)arg1 templateLearn:(BOOL)arg2 materialLearn:(BOOL)arg3 materialMatch:(BOOL)arg4;
- (void)dealloc;
- (id)initWithObject:(id)arg1;

@end

