//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FFEffect, FFEffectBundle;

__attribute__((visibility("hidden")))
@interface FFAudioEffectEditorDelegate : NSObject
{
    BOOL _allowsBypass;
    BOOL _showSubmenu;
    FFEffect *_effect;
    FFEffectBundle *_effectBundle;
}

+ (BOOL)_setBypass:(BOOL)arg1 onEffect:(id)arg2;
+ (id)effectEditorDelegateForEffect:(id)arg1 andBundle:(id)arg2;
@property(readonly, nonatomic) BOOL showSubmenu; // @synthesize showSubmenu=_showSubmenu;
@property(nonatomic) BOOL allowsBypass; // @synthesize allowsBypass=_allowsBypass;
@property(readonly, retain, nonatomic) FFEffectBundle *effectBundle; // @synthesize effectBundle=_effectBundle;
@property(readonly, retain, nonatomic) FFEffect *effect; // @synthesize effect=_effect;
- (id)bypassChannel;
- (BOOL)hasPresets;
- (id)displayName;
- (id)backingEffect;
- (void)setPresetFromRepresentedObject:(id)arg1 tag:(long long)arg2;
@property(nonatomic, getter=bypassed) BOOL bypassEffect;
- (void)buildPresetMenu:(id)arg1;
- (void)dealloc;
- (id)initWithAudioUnitEffect:(id)arg1 andBundle:(id)arg2 allowsBypass:(BOOL)arg3 showSubmenu:(BOOL)arg4;

@end

