//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class NSImage;

__attribute__((visibility("hidden")))
@interface FFClapperZebraOverlayLayer : CALayer
{
    NSImage *_clapperZebraImage;
}

+ (BOOL)needsDisplayForKey:(id)arg1;
@property(retain, nonatomic) NSImage *clapperZebraImage; // @synthesize clapperZebraImage=_clapperZebraImage;
- (void)drawInContext:(struct CGContext *)arg1;
- (void)dealloc;

@end

