//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface FFCoder : NSObject
{
}

+ (id)unarchiver:(id)arg1 didDecodeObject:(id)arg2;
+ (void)archiver:(id)arg1 didEncodeObject:(id)arg2;
+ (id)archiver:(id)arg1 willEncodeObject:(id)arg2;
+ (id)encodeData:(id)arg1 options:(id)arg2 error:(id *)arg3;
+ (BOOL)encode:(id)arg1 url:(id)arg2 error:(id *)arg3;
+ (id)newEncodedExternalData:(id)arg1;
+ (id)newDecodedObject:(id)arg1 targetSequence:(id)arg2 event:(id)arg3 options:(id)arg4 error:(id *)arg5;
+ (id)decodeExternal:(id)arg1 event:(id)arg2 error:(id *)arg3;
+ (id)decode:(id)arg1 event:(id)arg2 error:(id *)arg3;
+ (id)decode:(id)arg1 error:(id *)arg2;

@end

