//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class FFComparePickerView, FFLibrary, LKButton, LKPopUpButton, LKTextField, NSString;

@interface FFComparePickerWindowController : NSWindowController <NSWindowDelegate>
{
    FFComparePickerView *_snapshotPickerView;
    LKPopUpButton *_libraryPopupButton;
    LKButton *_addSnapshot;
    FFLibrary *_library;
    LKTextField *_numberOfSlots;
}

@property(readonly, nonatomic) FFComparePickerView *pickerView; // @synthesize pickerView=_snapshotPickerView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (id)comparedObjects;
- (void)updateSelectedIndex:(long long)arg1;
- (void)updateNumberOfSlots;
- (id)stringForNumberOfSlots;
- (void)deleteSnapshotAtIndexes:(id)arg1;
- (void)addSnapshot:(id)arg1;
- (void)close;
- (void)close:(id)arg1;
- (void)windowDidLoad;
- (void)showWindow:(id)arg1;
- (void)_assetChange:(id)arg1;
@property(retain) FFLibrary *library;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

