//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFEffectPreset.h>

__attribute__((visibility("hidden")))
@interface FFColorEffectPreset : FFEffectPreset
{
}

+ (id)directoryURL;
+ (void)registerOneEffectPreset:(id)arg1 updateSet:(BOOL)arg2 notify:(BOOL)arg3;
+ (void)registerEffects;
- (id)presetURL;

@end

