//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSButton;

__attribute__((visibility("hidden")))
@interface FFConsolidateOptionsView : NSView
{
    NSButton *_originalMediaCheckbox;
    NSButton *_optimizedMediaCheckbox;
    NSButton *_proxyMediaCheckbox;
    NSButton *_okButton;
}

+ (BOOL)runConsolidateDialogWithTitle:(id)arg1 description:(id)arg2 library:(id)arg3 options:(int *)arg4;
- (void)updateOKButton;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (int)consolidateOptions;
- (id)options;
- (void)setOptions:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (void)runConsolidateDialogWithTitle:(id)arg1 description:(id)arg2 library:(id)arg3;

@end

