//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFHeliumEffect.h>

#import <Flexo/FFColorSubEffect-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface FFConsumerColorEffect : FFHeliumEffect <FFColorSubEffect>
{
}

+ (BOOL)isNoOpForSoleOpEffect:(id)arg1;
+ (unsigned long long)numberOfAllowedInstances;
+ (id)effectID;
+ (void)registerEffects;
- (id)colorEffect;
- (void)setColorEffect:(id)arg1;
- (void)populateUsingLegacyIMovieParams:(CDStruct_a68fe99b *)arg1;
- (void)_setDoubleValue:(double)arg1 forChannelID:(unsigned int)arg2 atTime:(CDStruct_1b6d18a9)arg3;
- (void)setParameterValuesForNode:(struct HGNode *)arg1 atTime:(CDStruct_1b6d18a9)arg2 withInputStream:(id)arg3 context:(id)arg4 pixelTransform:(id)arg5 inputData:(id)arg6 inputBounds:(struct CGRect)arg7;
- (struct HGNode *)newNodeForContext:(id)arg1;
- (id)processingFormat:(int)arg1;
- (BOOL)isNoOp;
- (id)inputKeys;
- (unsigned int)intrinsicCacheFlag;
- (void)createChannelsInFolder:(id)arg1;
- (id)initWithEffectID:(id)arg1;
- (void)finishedSettingEffectParameters;
- (id)designatedChannelsForXMLExport;
- (BOOL)hasDesignatedChannelsForXMLExport;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

