//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "CBPuckControllerDelegate.h"

@class FFColorBoardImageView, FFColorBoardPuckButton, FFColorBoardPuckInfoView, LKButton, NSArray;

__attribute__((visibility("hidden")))
@interface FFColorBoardPanelView : NSView <CBPuckControllerDelegate>
{
    int _boardType;
    NSArray *_boardPuckControllers;
    LKButton *_resetButton;
    FFColorBoardImageView *_boardImageView;
    FFColorBoardPuckButton *_globalPuckView;
    FFColorBoardPuckButton *_shadowPuckView;
    FFColorBoardPuckButton *_midtonePuckView;
    FFColorBoardPuckButton *_highlightPuckView;
    FFColorBoardPuckInfoView *_globalPuckInfoView;
    FFColorBoardPuckInfoView *_shadowPuckInfoView;
    FFColorBoardPuckInfoView *_midtonePuckInfoView;
    FFColorBoardPuckInfoView *_highlightPuckInfoView;
}

@property(retain, nonatomic) FFColorBoardPuckInfoView *highlightPuckInfoView; // @synthesize highlightPuckInfoView=_highlightPuckInfoView;
@property(retain, nonatomic) FFColorBoardPuckInfoView *midtonePuckInfoView; // @synthesize midtonePuckInfoView=_midtonePuckInfoView;
@property(retain, nonatomic) FFColorBoardPuckInfoView *shadowPuckInfoView; // @synthesize shadowPuckInfoView=_shadowPuckInfoView;
@property(retain, nonatomic) FFColorBoardPuckInfoView *globalPuckInfoView; // @synthesize globalPuckInfoView=_globalPuckInfoView;
@property(retain, nonatomic) FFColorBoardPuckButton *highlightPuckView; // @synthesize highlightPuckView=_highlightPuckView;
@property(retain, nonatomic) FFColorBoardPuckButton *midtonePuckView; // @synthesize midtonePuckView=_midtonePuckView;
@property(retain, nonatomic) FFColorBoardPuckButton *shadowPuckView; // @synthesize shadowPuckView=_shadowPuckView;
@property(retain, nonatomic) FFColorBoardPuckButton *globalPuckView; // @synthesize globalPuckView=_globalPuckView;
@property(retain, nonatomic) NSArray *boardPuckControllers; // @synthesize boardPuckControllers=_boardPuckControllers;
@property(retain, nonatomic) FFColorBoardImageView *boardImageView; // @synthesize boardImageView=_boardImageView;
@property(retain, nonatomic) LKButton *resetButton; // @synthesize resetButton=_resetButton;
@property(nonatomic) int boardType; // @synthesize boardType=_boardType;
- (struct CGPoint)puck:(id)arg1 convertPuckToNormalizedCoord:(struct CGPoint)arg2;
- (struct CGPoint)puck:(id)arg1 convertNormalizedToPuckCoord:(struct CGPoint)arg2;
- (BOOL)becomeFirstResponder;
- (BOOL)acceptsFirstResponder;
- (BOOL)canBecomeKeyView;
- (BOOL)puck:(id)arg1 willMoveTo:(struct CGPoint *)arg2;
- (struct CGPoint)convertNormalizedColorToBoardCoord:(struct CGPoint)arg1;
- (struct CGPoint)convertBoardToNormalizedColorCoord:(struct CGPoint)arg1;
- (struct CGPoint)calcPuckCenterPosition:(id)arg1;
- (struct CGRect)calcPuckFrame:(id)arg1;
- (struct CGRect)calcPuckMovementFrame;
- (void)attachPuckControllerOfType:(int)arg1 toPuck:(id)arg2;
- (id)controllerForPuckType:(int)arg1;
- (void)removePuckControllerDelegates;
- (void)loadBoardPuckControllers;
- (BOOL)hasPuckController:(id)arg1;
- (void)syncToBoardType;
- (void)resetLayerData:(id)arg1;
- (void)notificationHandler:(id)arg1;
- (void)removeNotificationObservers;
- (void)addNotificationObservers;
- (void)mouseDown:(id)arg1;
- (void)_deselectAllPucksNotMatchingPuckType:(int)arg1 boardType:(int)arg2;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

