//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class FFCPSClapperboardView, NSImage;

__attribute__((visibility("hidden")))
@interface FFCPSShadowView : NSView
{
    FFCPSClapperboardView *_clapperView;
    NSImage *_shadowImage;
}

@property(retain, nonatomic) NSImage *shadowImage; // @synthesize shadowImage=_shadowImage;
@property(nonatomic) FFCPSClapperboardView *clapperView; // @synthesize clapperView=_clapperView;
- (struct CGRect)scaleCenterClapperViewInRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

