//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSCalendar, NSString;

__attribute__((visibility("hidden")))
@interface FFDateParsingContext : NSObject
{
    NSCalendar *_calendar;
    NSArray *_formatters;
    NSArray *_calendarUnits;
}

+ (id)parsingContextForCalendar:(id)arg1;
+ (id)_keyForCalendar:(id)arg1;
@property(readonly) NSArray *calendarUnits; // @synthesize calendarUnits=_calendarUnits;
@property(readonly) NSArray *formatters; // @synthesize formatters=_formatters;
@property(readonly) NSCalendar *calendar; // @synthesize calendar=_calendar;
- (void)_addFormattersForDateComponentMatching;
- (id)_copyFormatterWithDateStyle:(unsigned long long)arg1 calendar:(id)arg2;
- (id)_copyFormatterWithTemplate:(id)arg1 calendar:(id)arg2;
@property(readonly) NSString *identifier;
- (id)initWithCalendar:(id)arg1;

@end

