//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface FFDataViewerNode : NSObject
{
    NSObject *_nodeObject;
    FFDataViewerNode *_parent;
    NSString *_key;
    long long _index;
    NSArray *_children;
    BOOL _leafNode;
    Class _nodeClass;
}

+ (id)nodeWithRootObject:(id)arg1;
+ (id)nodeWithParent:(id)arg1 nodeKey:(id)arg2 nodeIndex:(long long)arg3 class:(Class)arg4;
- (BOOL)_testIfLeafNode;
- (id)initWithRootObject:(id)arg1;
- (id)initWithParent:(id)arg1 nodeKey:(id)arg2 nodeIndex:(long long)arg3 class:(Class)arg4;
- (void)dealloc;
@property(retain, nonatomic) NSObject *nodeObject; // @synthesize nodeObject=_nodeObject;
@property(retain, nonatomic) NSArray *children; // @synthesize children=_children;
- (unsigned long long)numberOfChildren;
- (id)childAtIndex:(unsigned long long)arg1;
- (id)keyDescription;
- (id)typeDescription;
- (id)valueDescription;
- (id)description;
@property(nonatomic) Class nodeClass; // @synthesize nodeClass=_nodeClass;
@property(nonatomic) FFDataViewerNode *parent; // @synthesize parent=_parent;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(nonatomic) BOOL leafNode; // @synthesize leafNode=_leafNode;

@end

