//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FFAnchoredObject, NSString;

__attribute__((visibility("hidden")))
@interface FFDestAnalyzerController : NSObject
{
    FFAnchoredObject *_anchoredObject;
    id _delegate;
    NSString *_dataFilePath;
}

- (id)initWithAnchoredObject:(id)arg1;
- (void)dealloc;
- (int)createDataFiles;
@property(readonly, nonatomic) NSString *dataFilePath; // @synthesize dataFilePath=_dataFilePath;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) FFAnchoredObject *anchoredObject; // @synthesize anchoredObject=_anchoredObject;

@end

