//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFEffect.h>

@interface FFEffect (FFEffectRegistry)
+ (id)_effectRegistry;
+ (void)ensureEffectsRegistered;
+ (id)_effectRegistryForLookup;
+ (void)deferEffectRegistrationForClass:(Class)arg1;
+ (void)runDeferredRegistration;
+ (void)registerEffectClass:(Class)arg1 forEffectID:(id)arg2 withProperties:(id)arg3;
+ (id)newEffectWithID:(id)arg1;
+ (BOOL)effectIDIsRegistered:(id)arg1;
+ (id)_registryEntryForEffectID:(id)arg1;
+ (id)propertiesForEffect:(id)arg1;
+ (id)allRegisteredEffectIDs;
+ (id)userVisibleEffectIDs;
+ (id)effectTypeForEffectID:(id)arg1;
+ (id)registeredEffectIDsForEffectType:(id)arg1;
+ (id)registeredEffectIDsForEffectTypes:(id)arg1;
+ (id)firstRegisteredEffectIDContainingSubstring:(id)arg1;
+ (Class)classForEffectID:(id)arg1;
+ (id)registeredEffectIDsForClass:(Class)arg1;
+ (id)displayNameForEffectType:(id)arg1;
+ (id)displayNameForEffectID:(id)arg1;
+ (id)categoryForEffectID:(id)arg1;
+ (id)descriptionForEffectID:(id)arg1;
+ (BOOL)isVideoForEffectID:(id)arg1;
@end

