//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFResponderLayer.h>

#import "CALayerDelegate.h"
#import "NSMenuDelegate.h"

@class CALayer, CHChannel, FFAnchoredObject, FFFadeHandlesLayerUpdater, FFRoleColorImageTinter, FFRoleColorScheme, NSDictionary, NSMutableArray, NSSet, NSString, TLKImageLayer, TLKTimelineView;

__attribute__((visibility("hidden")))
@interface FFFadeHandlesLayer : FFResponderLayer <CALayerDelegate, NSMenuDelegate>
{
    id <FFFadeHandlesDataSource> _dataSource;
    TLKTimelineView *_timelineView;
    id _representedObject;
    BOOL _isAudio;
    BOOL _isAudioOnly;
    NSMutableArray *_handleLayers;
    CALayer *_curvesLayer;
    NSMutableArray *_curveLayers;
    FFFadeHandlesLayerUpdater *_layerUpdater;
    FFAnchoredObject *_observedAudioComponentSourceRootObject;
    BOOL _showingAlignedFadeHandles;
    BOOL _showAlignedFadeHandle;
    int _showAlignedWhichFade;
    NSSet *_componentSourcesFadeAligned;
    NSDictionary *_handleImages;
    FFRoleColorScheme *_roleColorScheme;
    FFRoleColorImageTinter *_tinter;
    CHChannel *_channel;
    TLKImageLayer *_draggedHandleLayer;
    TLKImageLayer *_rolloverHandleLayer;
}

@property(retain, nonatomic) FFFadeHandlesLayerUpdater *layerUpdater; // @synthesize layerUpdater=_layerUpdater;
@property(nonatomic) NSSet *componentSourcesFadeAligned; // @synthesize componentSourcesFadeAligned=_componentSourcesFadeAligned;
@property(nonatomic) TLKImageLayer *rolloverHandleLayer; // @synthesize rolloverHandleLayer=_rolloverHandleLayer;
@property(nonatomic) TLKImageLayer *draggedHandleLayer; // @synthesize draggedHandleLayer=_draggedHandleLayer;
@property(retain, nonatomic) NSMutableArray *curveLayers; // @synthesize curveLayers=_curveLayers;
@property(retain, nonatomic) CALayer *curvesLayer; // @synthesize curvesLayer=_curvesLayer;
@property(retain, nonatomic) NSMutableArray *handleLayers; // @synthesize handleLayers=_handleLayers;
@property(nonatomic) BOOL isAudio; // @synthesize isAudio=_isAudio;
@property(nonatomic) id representedObject; // @synthesize representedObject=_representedObject;
@property(retain, nonatomic) CHChannel *channel; // @synthesize channel=_channel;
@property(nonatomic) TLKTimelineView *timelineView; // @synthesize timelineView=_timelineView;
@property(nonatomic) id <FFFadeHandlesDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (id)view:(id)arg1 stringForToolTip:(long long)arg2 point:(struct CGPoint)arg3 userData:(void *)arg4;
- (BOOL)_adjustShowHandle:(BOOL)arg1 forLayer:(id)arg2;
- (void)_hideAlignedFadeHandles;
- (void)_showAlignedFadeHandlesUsingEvent:(id)arg1;
- (void)_removeAlignedFadesObserving;
- (void)_addAlignedFadesObserving;
- (void)_clearRolloverHandleLayer;
- (void)_showHideAlignedFadeHandle:(id)arg1;
- (CDStruct_1b6d18a9)_timeFromLocation:(double)arg1;
- (double)_locationForTime:(CDStruct_1b6d18a9)arg1;
- (void)_showTimecodeDisplayForHandleAtIndex:(unsigned long long)arg1;
- (struct CGRect)_frameForHandleAtIndex:(unsigned long long)arg1 timeRange:(CDStruct_e83c9415)arg2;
- (struct CGRect)_frameForCurveAtIndex:(unsigned long long)arg1 timeRange:(CDStruct_e83c9415)arg2;
- (id)_fadeCurveContextMenuForHandleAtIndex:(unsigned long long)arg1;
- (void)_drawFadeWithBounds:(struct CGRect)arg1 inContext:(struct CGContext *)arg2 curvature:(unsigned int)arg3 enabled:(BOOL)arg4 forFadeIn:(BOOL)arg5;
- (void)_channelChanged:(id)arg1;
- (id)_newHandleImagesDict;
- (void)setCurveType:(id)arg1;
- (void)stopObservingRangeInvalidationNotifications;
- (void)startObservingRangeInvalidationNotifications;
- (id)roleColorScheme;
- (id)initWithDataSource:(id)arg1;
- (BOOL)shouldAutoscroll:(id)arg1;
- (id)cursorAtPoint:(struct CGPoint)arg1 event:(id)arg2;
- (void)mouseDragCanceled:(id)arg1;
- (void)mouseUp:(id)arg1;
- (BOOL)mouseDragged:(id)arg1;
- (BOOL)mouseDown:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (BOOL)mouseEntered:(id)arg1;
- (void)flagsChanged:(id)arg1;
- (id)subpartAtPoint:(struct CGPoint)arg1;
- (id)contextMenuForPart:(id)arg1;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
- (void)layoutSublayers;
- (void)setNeedsLayout;
- (void)colorSchemeHasChanged;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)hideFadeHandlesAndCurveLayers;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

