//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMapTable, NSProThemeFacet;

__attribute__((visibility("hidden")))
@interface FFFacetTextures : NSObject
{
    NSMapTable *_textures;
    BOOL _invalidated;
    int _virtualScreen;
    NSProThemeFacet *_facet;
}

+ (void)initialize;
+ (void)_handleLookDidChange:(id)arg1;
+ (id)cachedTexturesForFacet:(id)arg1 context:(struct _CGLContextObject *)arg2;
+ (id)uncachedTexturesForFacet:(id)arg1 context:(struct _CGLContextObject *)arg2;
- (id)_initWithFacet:(id)arg1 virtualScreen:(int)arg2;
- (id)initWithFacet:(id)arg1 context:(struct _CGLContextObject *)arg2;
- (void)dealloc;
- (void)invalidate;
- (BOOL)isValidForContext:(struct _CGLContextObject *)arg1;
- (id)textureForContext:(struct _CGLContextObject *)arg1 state:(long long)arg2 dimension1:(long long)arg3 value:(long long)arg4 size:(struct CGSize)arg5 createIfNeeded:(BOOL)arg6 colorSync:(BOOL)arg7;
- (id)textureForContext:(struct _CGLContextObject *)arg1 state:(long long)arg2 size:(struct CGSize)arg3 createIfNeeded:(BOOL)arg4 colorSync:(BOOL)arg5;

@end

