//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSAnimationDelegate.h"
#import "NSOpenSavePanelDelegate.h"

@class FFEventLibraryModule, FFFileImportAccessoryView, FFFileImportOpenPanel, FFFileImporter, FFMediaEventProject, NSArray, NSButton, NSMutableArray;

@interface FFFileImportDialogController : NSViewController <NSAnimationDelegate, NSOpenSavePanelDelegate>
{
    NSButton *_optimizeMediaButton;
    NSButton *_proxyMediaButton;
    NSMutableArray *_urlsToValidate;
    NSArray *_selectedFilesInDialog;
    FFEventLibraryModule *_eventOrganizerModule;
    FFFileImportOpenPanel *_openPanel;
    FFFileImportAccessoryView *_accessoryView;
    FFFileImporter *_fileImporter;
    FFMediaEventProject *_destinationEvent;
    NSArray *_importedMediaRanges;
}

- (id)initWithEventLibraryModule:(id)arg1;
- (void)showDuplicateEventDialog;
- (id)createNewEvent;
- (BOOL)validateFiles;
- (void)processFiles;
- (BOOL)importFiles;
- (id)runFileImportWithInitialEvent:(id)arg1 keywordNames:(id)arg2;
- (void)dealloc;
- (id)stringFromFourCharCode:(unsigned int)arg1;
- (BOOL)subPathContainsValidFiles:(id)arg1;
- (BOOL)needsOptimizationForURL:(id)arg1;
- (void)panelSelectionDidChange:(id)arg1;
- (BOOL)panel:(id)arg1 validateURL:(id)arg2 error:(id *)arg3;
- (BOOL)checkIfPackageOrHidden:(id)arg1;
- (BOOL)panel:(id)arg1 shouldEnableURL:(id)arg2;
- (void)panel:(id)arg1 didChangeToDirectoryURL:(id)arg2;

@end

