//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface FFFindCaptionThroughEditsInRowOperation : NSOperation
{
    NSMutableArray *_throughEditDescriptions;
    NSMutableArray *_captionsWithoutThroughEdits;
    NSArray *_orderedItems;
}

+ (void)initialize;
@property(readonly, nonatomic) NSArray *captionsWithoutThroughEdits; // @synthesize captionsWithoutThroughEdits=_captionsWithoutThroughEdits;
@property(readonly, nonatomic) NSArray *throughEditDescriptions; // @synthesize throughEditDescriptions=_throughEditDescriptions;
@property(readonly, nonatomic) NSArray *orderedItems; // @synthesize orderedItems=_orderedItems;
- (void)_addToThroughEditsWithItem:(id)arg1 nextItem:(id)arg2 previousItem:(id)arg3;
- (id)_nextItemAfterIndex:(unsigned long long)arg1;
- (id)_previousItemBeforeIndex:(unsigned long long)arg1;
- (BOOL)_captionHasThroughEditAnimationStyle:(id)arg1;
- (BOOL)_shouldSearchForThroughEditsForItem:(id)arg1;
- (void)_makeThroughEditDescriptionIfNeededForClip:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)_findThroughEdits;
- (void)main;
- (void)dealloc;
- (id)initWithOrderedItems:(id)arg1;

@end

