//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSColorWell.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface FFFontSettingsColorWell : NSColorWell
{
    NSString *_name;
    BOOL _ignoreSetColor;
}

@property(nonatomic) BOOL ignoreSetColor; // @synthesize ignoreSetColor=_ignoreSetColor;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void)setColor:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)dealloc;

@end

