//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFMapEffect.h>

@class NSImage;

__attribute__((visibility("hidden")))
@interface FFGlobeMapEffect : FFMapEffect
{
    NSImage *_mapImage;
    NSImage *_mapImage4K;
    NSImage *_backgroundImage;
}

+ (id)newMapImageForMapType:(int)arg1 use4K:(BOOL)arg2;
+ (id)newImageByScalingImage:(id)arg1 toWidth:(unsigned long long)arg2;
- (void)setCompositionParameterValuesAtTime:(CDStruct_1b6d18a9)arg1 use4K:(BOOL)arg2;
- (void)createChannelsInFolder:(id)arg1;
- (id)compositionName;
- (id)atmosphereColor;
- (id)backgroundImage;
- (id)mapImage4K;
- (id)mapImage;
- (void)dealloc;

@end

