//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFTool.h>

@interface FFHandTool : FFTool
{
    struct CGPoint _startPoint;
}

+ (id)cursor;
+ (id)toolbarFacetImageOff;
+ (id)toolbarFacetImageOn;
+ (id)toolTip;
+ (id)displayName;
+ (void)initialize;
+ (id)TLKEventHandlerID;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;

@end

