//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface FFHGAsyncQueue : NSObject
{
    struct HGRenderQueue *_queue;
    NSMutableArray *_renderInfos;
    NSMutableArray *_XGPURenderInfos;
}

+ (void)installSensoLockOrderingCheck;
+ (void)teardown;
+ (id)sharedInstance;
- (void)setMinExecutionPriority:(int)arg1;
- (id)description;
- (void)ensureRendererForLocations:(const struct FxDeviceSet *)arg1;
- (struct HGGLContextPtr)getContextPtrForLocation:(const struct FxDevice *)arg1;
- (struct HGRenderQueue *)queue;
- (void)dealloc;
- (void)drainQueue;
- (id)init;
- (void)appWillTerminate:(id)arg1;

@end

