//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FFFileImporter, NSDictionary, NSMutableDictionary;

@interface FFImportFileManager : NSObject
{
    FFFileImporter *_fileImporter;
    NSDictionary *_postponedFileImportInfo;
    NSMutableDictionary *_importQueue;
    BOOL _rejectedSheetShown;
    CDUnknownBlockType _sizeValidationBlock;
    CDUnknownBlockType _importDidBeginBlock;
    long long _bytesRequired;
}

+ (void)releaseSharedInstance;
+ (id)sharedInstance;
@property long long bytesRequired; // @synthesize bytesRequired=_bytesRequired;
@property(copy) CDUnknownBlockType importDidBeginBlock; // @synthesize importDidBeginBlock=_importDidBeginBlock;
@property(copy) CDUnknownBlockType sizeValidationBlock; // @synthesize sizeValidationBlock=_sizeValidationBlock;
@property BOOL rejectedSheetShown; // @synthesize rejectedSheetShown=_rejectedSheetShown;
@property(retain) NSDictionary *postponedFileImportInfo; // @synthesize postponedFileImportInfo=_postponedFileImportInfo;
- (void)copyQueueCanceled:(id)arg1;
- (void)copyQueueCompleted:(id)arg1;
- (void)clearSourceURL:(id)arg1 forTargetFileID:(id)arg2;
- (void)cancelValidation;
- (void)processFiles:(id)arg1;
- (void)processPostponedImport:(BOOL)arg1;
- (void)rejectedSheetDidEnd:(id)arg1;
- (void)rejectedSheetWillBegin:(id)arg1;
- (id)importFiles:(id)arg1 toEvent:(id)arg2 keywords:(id)arg3 window:(id)arg4 isValid:(char *)arg5 sizeValidation:(CDUnknownBlockType)arg6 importDidBegin:(CDUnknownBlockType)arg7;
- (void)dealloc;
- (oneway void)release;
- (id)init;

@end

