//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FFImageBrowserSectionLayer, FFImageBrowserView, NSIndexSet;

@protocol FFImageBrowserDataSource <NSObject>
- (id <FFImageBrowserRepresentedItem>)imageBrowser:(FFImageBrowserView *)arg1 representedItemAtIndex:(long long)arg2;
- (long long)numberOfItemsInImageBrowser:(FFImageBrowserView *)arg1;

@optional
- (FFImageBrowserSectionLayer *)imageBrowser:(FFImageBrowserView *)arg1 sectionLayerAtIndex:(unsigned long long)arg2;
- (long long)numberOfSectionsInImageBrowser:(FFImageBrowserView *)arg1;
- (void)imageBrowser:(FFImageBrowserView *)arg1 removeItemsAtIndexes:(NSIndexSet *)arg2;
@end

