//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFImageRep.h>

@class FFSegmentReadSample;

__attribute__((visibility("hidden")))
@interface FFImageRepSegmentReadSample : FFImageRep
{
    FFSegmentReadSample *_readSample;
}

- (int)getConversionTypeForPF:(id)arg1 colorSpace:(struct CGColorSpace *)arg2 pixelTransform:(id)arg3 location:(struct FxDevice *)arg4 nonStandardAlphaOK:(_Bool)arg5 backingRequest:(int)arg6;
- (void)getSampleBuffer:(struct opaqueCMSampleBuffer **)arg1 alphaKnownToBeFullyOpaque:(char *)arg2;
- (int)errorCode;
- (id)pixelTransform;
- (id)newTextureBufferWithFormatByFlatteningIfNeeded:(id)arg1 location:(struct FxDevice *)arg2 roi:(struct CGRect)arg3 pixelTransform:(id)arg4 flattenOptions:(const CDStruct_f51ed29d *)arg5 workingSpace:(int)arg6;
- (id)newPixelBufferWithFormatByFlatteningIfNeeded:(id)arg1 roi:(struct CGRect)arg2 pixelTransform:(id)arg3 nonStandardAlphaOK:(_Bool)arg4 flattenOptions:(const CDStruct_f51ed29d *)arg5 getRawPixelsWithoutSourceConform:(_Bool)arg6 workingSpace:(int)arg7;
- (unsigned int)field;
- (struct CGRect)pixelSpaceBounds;
- (int)nativeAlphaType;
- (id)nativePixelFormat;
- (id)_ensureFinalImage:(id)arg1;
- (unsigned long long)approximateMemoryUsage;
- (id)type;
- (id)description;
- (void)dealloc;
- (id)initWithReadSample:(id)arg1 sampleNum:(long long)arg2 quality:(int)arg3 colorSpace:(struct CGColorSpace *)arg4;

@end

