//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFInspectorParameterController.h>

@class LKButton, LKSlider, NSArray, NSView, PISegmentedScrubber;

__attribute__((visibility("hidden")))
@interface FFInspectorDoubleParameterController : FFInspectorParameterController
{
    NSView *_view;
    id <FFInspectorDoubleParameterControllerDelegate> _delegate;
    NSArray *_values;
    LKSlider *_slider;
    PISegmentedScrubber *_scrubber;
    LKButton *_resetButton;
    long long _actionCount;
}

+ (id)numberFormatter;
- (void)endSegmentedScrubberAction:(id)arg1;
- (void)startSegmentedScrubberAction:(id)arg1;
- (void)endSliderAction:(id)arg1;
- (void)startSliderAction:(id)arg1;
- (void)controlValueDidChange:(id)arg1;
- (void)resetValueToDefault:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)view;
- (id)_resetButton;
- (id)_scrubber;
- (id)_slider;
- (BOOL)ownsControl:(id)arg1;
@property(nonatomic) id <FFInspectorDoubleParameterControllerDelegate> delegate; // @dynamic delegate;
- (void)_reloadData;
- (BOOL)_allValuesAreEqual;
- (BOOL)_hasMultipleValues;
- (void)dealloc;

@end

