//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFAdjustmentTool.h>

#import "NSWindowDelegate.h"

@class LKButton, LKPopOverWindow, LKTextField, NSArray, NSButton, NSDateFormatter, NSImageView, NSView;

@interface FFInfoTool : FFAdjustmentTool <NSWindowDelegate>
{
    NSView *_adjustmentToolbarView;
    NSView *_infoView;
    NSView *_eventClipInfoView;
    NSView *_transitionsView;
    NSView *_simpleInfoView;
    LKTextField *_infoName;
    LKTextField *_infoDuration;
    LKTextField *_simpleInfoDuration;
    LKTextField *_simpleInfoName;
    LKTextField *_infoMaxDuration;
    NSImageView *_eventClipInfoClipIcon;
    NSImageView *_eventClipInfoDurationIcon;
    NSButton *_eventClipInfoShareIcon;
    LKTextField *_eventClipInfoName;
    LKTextField *_eventClipInfoMaxDuration;
    LKTextField *_eventClipInfoShareLabel;
    LKButton *_transitionButton;
    LKTextField *_transitionDuration;
    BOOL _selectionIsAllEventClips;
    BOOL _selectionIsAllTransitions;
    BOOL _selectionIsAllStillsEtc;
    NSArray *_selectedItems;
    CDStruct_1b6d18a9 _infoMaxDurationValue;
    NSDateFormatter *_dateFormatter;
    NSView *_currentView;
    LKPopOverWindow *_sharePopoverWindow;
}

+ (id)toolTip;
+ (id)toolbarFacetSelected;
+ (id)toolbarFacet;
+ (id)displayName;
+ (void)initialize;
+ (long long)sortOrderForGroup:(id)arg1;
+ (id)groups;
@property(retain, nonatomic) LKTextField *eventClipInfoShareLabel; // @synthesize eventClipInfoShareLabel=_eventClipInfoShareLabel;
@property(retain, nonatomic) NSButton *eventClipInfoShareIcon; // @synthesize eventClipInfoShareIcon=_eventClipInfoShareIcon;
@property(retain, nonatomic) NSImageView *eventClipInfoDurationIcon; // @synthesize eventClipInfoDurationIcon=_eventClipInfoDurationIcon;
@property(retain, nonatomic) NSImageView *eventClipInfoClipIcon; // @synthesize eventClipInfoClipIcon=_eventClipInfoClipIcon;
- (void)updateInfoDuration:(id)arg1;
- (void)popOverWindowDidCancel:(id)arg1;
- (void)shareHistory:(id)arg1;
- (void)sharePopoverWindowDidResignKey:(id)arg1;
- (void)applyToAllTransitions:(id)arg1;
- (void)updateTransitionDuration:(id)arg1;
- (void)setTransitionDurations:(id)arg1;
- (CDStruct_1b6d18a9)transitionMaxDuration:(id)arg1;
- (void)setAdjustmentStateFromDictionary:(id)arg1;
- (id)adjustmentsToolbarView;
- (id)newAdjustmentDictionaryForSelection:(id)arg1;
- (void)selectedItemsChanged:(id)arg1;
- (void)rangeInvalidated:(id)arg1;
- (void)removeRangeInvalNotifications;
- (void)addRangeInvalNotifications;
- (void)setCurrentInfoDurationUI;
- (void)setCurrentTransitionDurationUI;
- (id)shareString;
- (id)currentTransitionEffectID;
- (id)currentTransitionName;
- (id)currentInfoName;
- (BOOL)supportsMultipleSelection;
- (BOOL)allowsEffectOSCs;
- (BOOL)handlesSelection;
- (void)resignActiveTool;
- (void)dealloc;
- (id)init;

@end

