//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OZFolderGroupController.h"

__attribute__((visibility("hidden")))
@interface FFInlineViewControllerGroup : OZFolderGroupController
{
}

- (BOOL)setFromPasteboard:(id)arg1;
- (BOOL)checkPasteboard:(id)arg1;
- (id)performDragOperationWithInfo:(id)arg1;
- (id)draggingEnteredWithInfo:(id)arg1;
- (id)readableTypes;
- (void)didBuildUI;
- (id)initWithChan:(struct OZChannelBase *)arg1 context:(id)arg2;

@end

