//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@interface FFIndexPath : NSObject <NSCopying, NSCoding>
{
    unsigned long long *_indexes;
    unsigned long long _length;
}

+ (id)indexPathWithIndex:(unsigned long long)arg1;
+ (id)indexPathWithIndexes:(unsigned long long *)arg1 length:(unsigned long long)arg2;
- (id)_initWithIndexesPtr:(unsigned long long *)arg1 length:(unsigned long long)arg2;
- (id)initWithIndexes:(unsigned long long *)arg1 length:(unsigned long long)arg2;
- (id)initWithIndex:(unsigned long long)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)indexPathByAddingIndex:(unsigned long long)arg1;
- (id)indexPathByRemovingLastIndex;
- (id)indexPathByRemovingFirstIndex;
- (id)indexPathByReversingIndexPath;
- (unsigned long long)indexAtPosition:(unsigned long long)arg1;
- (unsigned long long)length;
- (void)getIndexes:(unsigned long long *)arg1;
- (long long)compare:(id)arg1;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;

@end

