//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFInspectorBaseFolderController.h>

#import "FFInspectorEffectsBrick.h"
#import "FFInspectorEffectsControllerHighlighting.h"
#import "FFInspectorEffectsDragging.h"

@class CHChannelFolder, FFAnchoredObject, FFEffect, FFInspectorControllerHighlightDrawer, FFInspectorEffectsDraggingContext;

__attribute__((visibility("hidden")))
@interface FFInspectorEffectBrickController : FFInspectorBaseFolderController <FFInspectorEffectsControllerHighlighting, FFInspectorEffectsDragging, FFInspectorEffectsBrick>
{
    id <FFInspectorEffectsRootDelegate> _effectsRootDelegate;
    FFInspectorEffectsDraggingContext *_draggingContext;
    FFEffect *_effect;
    CHChannelFolder *_effectChannelFolder;
    FFInspectorControllerHighlightDrawer *_highlightDrawer;
    FFAnchoredObject *_observedObject;
}

@property(readonly, nonatomic) id <FFInspectorEffectsRootDelegate> effectsRootDelegate; // @synthesize effectsRootDelegate=_effectsRootDelegate;
@property(readonly, nonatomic) FFEffect *effect; // @synthesize effect=_effect;
- (void)collapseForDragging:(BOOL)arg1;
- (BOOL)shouldCollapseForDragging;
- (id)associatedEffect;
- (void)setDraggingContext:(id)arg1;
- (id)draggingContext;
- (BOOL)supportsDraggingOwner:(id)arg1;
- (id)draggingOwner;
- (id)selectionOwner;
- (unsigned int)defaultExpandState;
- (BOOL)isExpandable;
- (id)childAtIndex:(long long)arg1;
- (long long)numberOfChildren;
- (void)setDropState:(unsigned long long)arg1 insertionIndex:(unsigned long long)arg2;
- (void)setUseInactiveSelectionState:(BOOL)arg1;
- (void)setSelected:(BOOL)arg1;
- (id)draggingImageForDrag;
- (BOOL)isEffectsBrickSelected;
- (void)_effectSelectionStateChanged:(id)arg1;
- (void)dealloc;
- (id)initWithEffect:(id)arg1 effectsRootDelegate:(id)arg2 context:(id)arg3;

@end

