//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFInspectorOZEffectsController.h>

#import <Flexo/FFInspectorEffectsSubcontrollersDelegate-Protocol.h>
#import <Flexo/FFInspectorVideoEffectsDataSource-Protocol.h>
#import <Flexo/FFInspectorVideoEffectsRootDelegate-Protocol.h>

@class FFInspectorMaskEffectsDraggingOwner, FFInspectorMaskEffectsSelectionOwner;

__attribute__((visibility("hidden")))
@interface FFInspectorVideoEffectsController : FFInspectorOZEffectsController <FFInspectorEffectsSubcontrollersDelegate, FFInspectorVideoEffectsRootDelegate, FFInspectorVideoEffectsDataSource>
{
    FFInspectorMaskEffectsSelectionOwner *_maskEffectsSelectionOwner;
    FFInspectorMaskEffectsDraggingOwner *_maskEffectsDraggingOwner;
}

- (BOOL)supportsDraggingOwner:(id)arg1 forEffect:(id)arg2;
- (id)subcontrollerForEffect:(id)arg1 atIndex:(long long)arg2 draggingContext:(id)arg3 context:(id)arg4;
- (long long)numSubcontrollersForEffect:(id)arg1;
- (id)maskEffectsDraggingOwner;
- (id)maskEffectsSelectionOwner;
- (id)dataSource;
- (BOOL)moveMasks:(id)arg1 toIndex:(unsigned long long)arg2 inEffect:(id)arg3;
- (BOOL)swapMask:(id)arg1 withMask:(id)arg2;
- (BOOL)removeMaskEffects:(id)arg1;
- (id)ozChannelDontBuildListForEffect:(id)arg1;
- (id)supportedDraggedEffectTypes;
- (id)inspectorEffectsSubcontrollersDelegate;
- (id)effectStackForSelectedObject:(id)arg1;
- (void)dealloc;
- (id)initWithChan:(struct OZChannelBase *)arg1 context:(id)arg2;

@end

