//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFInspectorModule.h>

@class NSBox;

__attribute__((visibility("hidden")))
@interface FFInspectorModuleAudioProperties : FFInspectorModule
{
    NSBox *_volumeModuleView;
    NSBox *_channelModuleView;
    BOOL _needsSetup;
}

- (id)moduleFooterAccessoryView;
- (id)moduleAccessoryView;
- (void)setInspectorModule:(id)arg1;
- (void)moduleViewWillBeRemoved:(id)arg1;
- (void)moduleDidUnhide;
- (void)module:(id)arg1 willRemoveSubmodule:(id)arg2;
- (void)module:(id)arg1 didAddSubmodule:(id)arg2;
- (void)_setupCurrentItems;
- (void)setCurrentItems:(id)arg1;
- (void)viewDidLoad;
- (id)moduleNibName;

@end

