//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMapTable;

__attribute__((visibility("hidden")))
@interface FFInspectorLabelParameterContext : NSObject
{
    id <FFInspectorLabelParameterContainerDataSource> _dataSource;
    double _preferredSplitterPosition;
    NSMapTable *_reusableViewControllers;
}

@property double preferredSplitterPosition; // @synthesize preferredSplitterPosition=_preferredSplitterPosition;
@property(nonatomic) id <FFInspectorLabelParameterContainerDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)container:(id)arg1 reloadItemsWithRange:(struct _NSRange)arg2;
- (void)container:(id)arg1 reloadItemAtRow:(unsigned long long)arg2;
- (void)reloadDataWithContainer:(id)arg1;
- (void)removeAllDequeuedReusableViewControllers;
- (id)dequeueReusableViewController:(id)arg1 withIdentifier:(id)arg2;
- (void)dealloc;
- (id)init;

@end

