//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class FFLibrary, LKPopUpButton;

__attribute__((visibility("hidden")))
@interface FFLibraryPicker : NSViewController
{
    LKPopUpButton *libraryPopup;
    FFLibrary *_library;
}

@property(retain, nonatomic) FFLibrary *library; // @synthesize library=_library;
@property(nonatomic) LKPopUpButton *libraryPopup; // @synthesize libraryPopup;
- (void)selectLibrary:(id)arg1;
- (void)_updateLibraryPopup;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

