//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/NSObject-Protocol.h>

@class FFMaskBase, NSString;

@protocol FFMaskOSC <NSObject>

@optional
+ (BOOL)isSamplingOSC;
@property(nonatomic, getter=isActive) BOOL active;
@property(copy, nonatomic) NSString *name;
@property(readonly, nonatomic) FFMaskBase *mask;
@end

