//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFSourceVideo.h>

#import "FFModelLocking.h"

__attribute__((visibility("hidden")))
@interface FFMCSwitcherVideoSource : FFSourceVideo <FFModelLocking>
{
    FFSourceVideo *_chosen;
    long long _anglesCount;
    long long _anglesOffset;
    FFSourceVideo *_angles;
}

+ (void)_sendAngleCountNotification:(id)arg1;
+ (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
+ (void)initialize;
+ (Class)streamClass;
- (id)aosProvider;
- (CDStruct_e83c9415)timeRange;
- (CDStruct_1b6d18a9)magicFrameTime;
- (id)nativeVideoProps;
- (void)videoRangeInvalidated:(id)arg1;
- (void)anglesVideoRangeInvalidated:(id)arg1;
- (void)makeAnglesSource:(BOOL)arg1;
- (id)initWithProvider:(id)arg1 chosenVideo:(id)arg2;
- (void)dealloc;
- (void)setAnglesCount:(long long)arg1 andOffset:(long long)arg2;
- (long long)anglesCount;
- (long long)anglesOffset;
- (id)angles;
- (id)newContextForAnglesSource:(id)arg1;
- (id)newSubRangeMD5InfoForSampleDuration:(CDStruct_1b6d18a9)arg1 atTime:(CDStruct_1b6d18a9)arg2 context:(id)arg3;
- (long long)timecodeDisplayDropFrame;
- (CDStruct_1b6d18a9)timecodeFrameDuration;
- (void)_writeLock;
- (void)_writeUnlock;
- (void)_readLock;
- (void)_readUnlock;
- (void)_multiAngleOffsetOrCountHasChangedSelectorOnMainThread:(id)arg1;
@property(readonly, nonatomic) FFSourceVideo *chosen; // @synthesize chosen=_chosen;

@end

