//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFMDMusicModule.h>

@interface FFMDGarageBandModule : FFMDMusicModule
{
}

- (id)mediaBrowserIdentifier;
- (BOOL)supportsMovie;
- (BOOL)supportsAudio;
- (void)revealInFinder:(id)arg1;
- (void)openInGarageBand:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (id)mediaPlugInLoadCompletionNotificationName;
- (id)mediaPlugInIdentifier;
- (void)viewWasInstalled;
- (void)dealloc;
- (id)init;

@end

