//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFMDAbstractLibraryCell.h>

__attribute__((visibility("hidden")))
@interface FFMDPhotoGroupCell : FFMDAbstractLibraryCell
{
}

+ (id)placeholderThumbnail;
- (struct CGPath *)_newPathForRoundedRect:(struct CGRect)arg1 radius:(double)arg2 lineWidth:(double)arg3;
- (void)drawOutlinedSelectionRingWithRect:(struct CGRect)arg1;
- (long long)numberOfThumbnails;
- (long long)numberOfChildren;
- (id)latestDate;
- (id)earliestDate;
- (id)displayName;
- (id)thumbnailAtIndex:(long long)arg1;
- (id)displayedPhotoObjectAtIndex:(long long)arg1;

@end

