//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <LunaKit/LKViewModule.h>

#import <Flexo/FFMediaSidebarSelectionSource-Protocol.h>

@class FFMediaSidebarController, FFMediaSidebarOutlineView, NSView;

@interface FFMediaSidebarModule : LKViewModule <FFMediaSidebarSelectionSource>
{
    NSView *_headerView;
    FFMediaSidebarController *_sidebarController;
    NSView *_sidebarContainerView;
    FFMediaSidebarOutlineView *_outlineView;
}

+ (id)defaultModuleNibName;
@property(retain, nonatomic) FFMediaSidebarOutlineView *outlineView; // @synthesize outlineView=_outlineView;
@property(retain, nonatomic) NSView *sidebarContainerView; // @synthesize sidebarContainerView=_sidebarContainerView;
@property(retain, nonatomic) FFMediaSidebarController *sidebarController; // @synthesize sidebarController=_sidebarController;
@property(retain, nonatomic) NSView *headerView; // @synthesize headerView=_headerView;
- (void)revealMediaRanges:(id)arg1;
- (void)revealObjects:(id)arg1;
- (void)selectSidebarItem:(id)arg1;
- (BOOL)isSidebarVisible;
- (id)sortedArrayMatchingSidebarOrder:(id)arg1;
- (void)selectDataItem:(id)arg1 extendSelection:(BOOL)arg2;
- (void)clearSelection;
- (void)syncSidebar;
- (void)sidebarDidSelectNodes:(id)arg1;
- (id)moduleHeaderAccessoryView;
- (BOOL)wantsHeaderBar;
- (void)setSidebarConnections:(id)arg1;
- (void)setUpSidebarController;
- (id)newSidebarController;
- (void)reloadSidebar;
- (void)preLayout:(id)arg1;
- (id)contentLayoutDictionary;
- (void)takeContentLayoutFromDictionary:(id)arg1;
- (id)targetModules;
- (void)viewDidLoad;
- (struct CGSize)viewMaxSize;
- (struct CGSize)viewMinSize;
- (id)firstKeyView;

@end

