//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFBaseDSObject.h>

@class DSObject, NSString;

__attribute__((visibility("hidden")))
@interface FFObjectDictKeyValue : FFBaseDSObject
{
    NSString *_key;
    DSObject *_value;
}

+ (BOOL)supportsSecureCoding;
+ (id)copyClassDescription;
+ (Class)DSClassDescriptionClass;
@property(retain, nonatomic) DSObject *value; // @synthesize value=_value;
@property(readonly, nonatomic) NSString *key; // @synthesize key=_key;
- (id)FFObjectDictKey;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithKey:(id)arg1 object:(id)arg2;

@end

