//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LKViewModule.h"

__attribute__((visibility("hidden")))
@interface FFOrganizerFilterHUDTileModule : LKViewModule
{
}

- (id)library;
- (void)controlUpdated:(id)arg1;
- (id)tileGlyphString;
- (id)metadataKey;
- (void)updateWithSelectedRoleUIDs:(id)arg1;
- (void)setKeywords:(id)arg1 selectedKeywords:(id)arg2;
- (id)filterDict;
- (void)setFilterDict:(id)arg1;
- (void)tileWasInstalled;
- (BOOL)active;
- (void)setActive:(BOOL)arg1;

@end

