//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFOrganizerFilterHUDTileModule.h>

@class LKPopUpButton, LKTextField, NSArray, NSDate, NSString;

__attribute__((visibility("hidden")))
@interface FFOrganizerFilterHUDTimeTileModule : FFOrganizerFilterHUDTileModule
{
    NSArray *_datePopUpMetadataKeysArray;
    LKPopUpButton *_dateTypePopup;
    LKPopUpButton *_comparisonTypePopup;
    LKTextField *_durationTextField;
    LKPopUpButton *_timeUintPopup;
    NSString *_timeString;
    NSDate *_date;
}

@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) NSString *timeString; // @synthesize timeString=_timeString;
- (id)metadataKey;
- (id)_comparisonTypesAllowed;
- (void)updateDurationTextField:(id)arg1;
- (void)updateComparisonTypePopup:(id)arg1;
- (id)tileNameString;
- (id)tileGlyphString;
- (id)filterDict;
- (void)setFilterDict:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (id)_stringForMetadataKey:(id)arg1;

@end

