//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface FFPBOInfo : NSObject
{
    struct _CGLContextObject *_context;
    unsigned int _fbo;
    unsigned int _pbo;
    int _virtualScreen;
    unsigned long long _size;
    void *_baseAddress;
}

- (struct _CGLContextObject *)context;
- (unsigned int)pbo;
- (unsigned int)fbo;
- (int)virtualScreen;
- (unsigned long long)size;
- (id)initWithPBO:(unsigned int)arg1 context:(struct _CGLContextObject *)arg2 virtualScreen:(int)arg3 fbo:(unsigned int)arg4 size:(unsigned long long)arg5;

@end

