//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FFProxySizing : NSObject
{
}

+ (BOOL)verifyProxySizeIsCompatibleWithSourceSize:(struct CGSize)arg1 proxySize:(struct CGSize)arg2 codec:(unsigned int)arg3;
+ (BOOL)_proxySizeCorrectForSourceSize:(struct CGSize)arg1 proxySize:(struct CGSize)arg2;
+ (BOOL)_compareProxySize:(struct CGSize)arg1 calulatedSize:(struct CGSize)arg2;
+ (struct CGSize)requestedSizeForAssetSize:(struct CGSize)arg1 scaleDownFactor:(double)arg2 codec:(unsigned int)arg3 outProxySizeAdjustedForCodec:(char *)arg4;
+ (double)calculateProxyScaleFactorFromAssetSize:(struct CGSize)arg1 downscale:(long long)arg2 limit:(long long)arg3 codec:(unsigned int)arg4 outProxySizeAdjustedForCodec:(char *)arg5;
+ (struct CGSize)_scaleSizeAndAdjustToEvenWidthAndHeight:(struct CGSize)arg1 proxyScale:(double)arg2 adjustToEvenHeightAndWidth:(BOOL)arg3 outSizeWasAdjusted:(char *)arg4;
+ (double)_calculateProxyScaleFactorFromAssetSize:(struct CGSize)arg1 limit:(long long)arg2;
+ (double)_calculateProxyScaleFactorFromAssetSize:(struct CGSize)arg1 downscale:(long long)arg2;
+ (long long)strictestOfLimit:(long long)arg1 andLimit:(long long)arg2;
+ (long long)limitFromSizingMode:(long long)arg1;
+ (long long)downscaleFromSizingMode:(long long)arg1;
+ (BOOL)_codecRequiresEvenWidthAndHeight:(unsigned int)arg1;

@end

