//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFProviderCG.h>

@class NSRecursiveLock, NSString;

__attribute__((visibility("hidden")))
@interface FFProviderCGANIM : FFProviderCG
{
    struct CGImageSource *_imageSourceRef;
    NSString *_srcExtension;
    unsigned long long _numFrames;
    double _frameRate;
    CDStruct_1b6d18a9 _frameDuration;
    struct CGSize _imageSize;
    CDStruct_bdcb2b0d _md5;
    NSRecursiveLock *_lock;
    _Bool _unsupportedFileFeature;
}

+ (id)extensions;
+ (id)utis;
- (id)MD5Seed;
- (void)setMD5Seed:(id)arg1;
- (CDStruct_bdcb2b0d)_md5;
- (_Bool)unsupportedFileFeature;
- (id)nativeVideoProps;
- (id)newSourceForKey:(id)arg1;
- (void)_setupSources;
- (CDStruct_1b6d18a9)frameDuration;
- (unsigned long long)frameCount;
- (struct CGImageSource *)imageSourceRef;
- (void)dealloc;
- (id)initWithAssetFileID:(id)arg1;

@end

