//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFMediaSidebarController.h>

@class FFMediaSidebarNode, FFMediaSidebarSectionNode;

__attribute__((visibility("hidden")))
@interface FFProjectExtrasSidebarController : FFMediaSidebarController
{
    BOOL _silenceSelectionChange;
    FFMediaSidebarSectionNode *_extrasSectionNode;
}

@property(retain, nonatomic) FFMediaSidebarNode *extrasSectionNode; // @synthesize extrasSectionNode=_extrasSectionNode;
@property(nonatomic) BOOL silenceSelectionChange; // @synthesize silenceSelectionChange=_silenceSelectionChange;
- (id)nodeForExtrasDisplayType:(int)arg1;
- (id)outlineView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 item:(id)arg5 mouseLocation:(struct CGPoint)arg6;
- (id)outlineView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;
- (id)newMediaRootNode;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (int)selectedDisplayType;
- (void)selectDisplayType:(int)arg1;
- (id)persistentState;
- (void)restorePersistentState:(id)arg1;
- (void)dealloc;
- (id)init;

@end

