//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFScheduleToken.h>

@class NSDictionary, NSObject, QCRenderer;
@protocol OS_dispatch_semaphore;

__attribute__((visibility("hidden")))
@interface FFQCScheduleToken : FFScheduleToken
{
    unsigned int m_flags;
    struct _CGLContextObject *m_context;
    QCRenderer *_renderer;
    NSDictionary *_inputValues;
    NSObject<OS_dispatch_semaphore> *_frameCompleteSemaphore;
    CDStruct_1b6d18a9 _time;
}

@property(retain) NSObject<OS_dispatch_semaphore> *frameCompleteSemaphore; // @synthesize frameCompleteSemaphore=_frameCompleteSemaphore;
@property CDStruct_1b6d18a9 time; // @synthesize time=_time;
@property(copy) NSDictionary *inputValues; // @synthesize inputValues=_inputValues;
@property(retain) QCRenderer *renderer; // @synthesize renderer=_renderer;
- (id)copyErrorInfoStoppingAfterFirstError:(BOOL)arg1;
- (_Bool)waitForStatusFlagsToClear:(unsigned int)arg1 beforeDate:(id)arg2;
- (_Bool)hintWillImageSoon;
- (unsigned int)scheduleStatusInformation;
- (oneway void)dealloc;
- (id)initWithStream:(id)arg1 renderer:(id)arg2 context:(struct _CGLContextObject *)arg3;

@end

