//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFResponderLayerCheckbox.h>

@class NSColor, NSImage;

__attribute__((visibility("hidden")))
@interface FFResponderLayerRoleTintedCheckbox : FFResponderLayerCheckbox
{
    NSImage *_imageOn;
    NSImage *_imageOff;
    NSColor *_tintColor;
}

@property(copy, nonatomic) NSColor *tintColor; // @synthesize tintColor=_tintColor;
- (void)dealloc;
- (id)initWithBundle:(id)arg1 valueOff:(id)arg2 valueOn:(id)arg3;

@end

