//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface FFRejectedFileDataSource : NSObject
{
    NSString *_filename;
    NSString *_reason;
}

@property(retain) NSString *reason; // @synthesize reason=_reason;
@property(retain) NSString *filename; // @synthesize filename=_filename;
- (void)dealloc;

@end

