//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCondition, NSMutableArray;

__attribute__((visibility("hidden")))
@interface FFRendererPool : NSObject
{
    long long _maxRenderers;
    long long _rendererCount;
    int _location;
    int _virtualScreen;
    NSMutableArray *_renderers;
    NSMutableArray *_borrowedRenderers;
    NSCondition *_rendererAvailableCondition;
    long long _nextCustomerNumber;
    long long _nowServingNumber;
    int _maxTextureSizeHalfFloat;
    NSMutableArray *_threads;
}

- (id)initWithLocation:(int)arg1;
- (void)dealloc;
- (int)location;
- (id)renderer;
- (void)releaseRenderer:(id)arg1;
- (int)maxTextureSizeHalfFloat;
- (_Bool)canLoadImageAsTexture:(struct CGRect)arg1;
- (void)releaseHGObjectsForRenderer:(id)arg1;
- (_Bool)managesRenderer:(struct HGRenderer *)arg1;

@end

