//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFResponderLayerButton.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface FFResponderLayerCheckbox : FFResponderLayerButton
{
    long long _state;
    unsigned long long _valueCount;
    NSString *_accessibilityTitle;
}

@property(nonatomic) long long state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *accessibilityTitle; // @synthesize accessibilityTitle=_accessibilityTitle;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (void)_handleButtonActuated;
- (long long)_nextState;
@property(nonatomic) BOOL allowsMixedState;
- (void)configureWithState:(long long)arg1;
- (void)dealloc;

@end

