//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface FFReturnToManagedRenderer : NSObject
{
    struct HGObject *_obj;
    struct FxDevice *_loc;
}

- (void)dealloc;
- (id)initWithLocation:(struct FxDevice *)arg1 hgObj:(struct HGObject *)arg2;

@end

