//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FFLibrary, NSSet;

@interface FFRolesMenuContext : NSObject
{
    FFLibrary *_library;
    NSSet *_roleUIDsUsedByAll;
    NSSet *_roleUIDsUsedByAny;
    BOOL _selectionHasAudio;
    BOOL _selectionHasVideo;
    BOOL _selectionHasCaption;
    BOOL _selectionSupportsShowingAudioSubRoles;
    BOOL _selectionSupportsAssigningAudioSubRoles;
    BOOL _selectionSupportsAssigningAudioMainRoles;
    BOOL _selectionContainsAtleastOneProject;
}

@property(nonatomic) BOOL selectionContainsAtleastOneProject; // @synthesize selectionContainsAtleastOneProject=_selectionContainsAtleastOneProject;
@property(readonly, nonatomic) BOOL selectionSupportsAssigningAudioMainRoles; // @synthesize selectionSupportsAssigningAudioMainRoles=_selectionSupportsAssigningAudioMainRoles;
@property(readonly, nonatomic) BOOL selectionSupportsAssigningAudioSubRoles; // @synthesize selectionSupportsAssigningAudioSubRoles=_selectionSupportsAssigningAudioSubRoles;
@property(readonly, nonatomic) BOOL selectionSupportsShowingAudioSubRoles; // @synthesize selectionSupportsShowingAudioSubRoles=_selectionSupportsShowingAudioSubRoles;
@property(readonly, nonatomic) BOOL selectionHasCaption; // @synthesize selectionHasCaption=_selectionHasCaption;
@property(readonly, nonatomic) BOOL selectionHasVideo; // @synthesize selectionHasVideo=_selectionHasVideo;
@property(readonly, nonatomic) BOOL selectionHasAudio; // @synthesize selectionHasAudio=_selectionHasAudio;
@property(readonly, retain, nonatomic) NSSet *roleUIDsUsedByAll; // @synthesize roleUIDsUsedByAll=_roleUIDsUsedByAll;
@property(readonly, retain, nonatomic) NSSet *roleUIDsUsedByAny; // @synthesize roleUIDsUsedByAny=_roleUIDsUsedByAny;
@property(readonly, retain, nonatomic) FFLibrary *library; // @synthesize library=_library;
- (void)dealloc;
- (id)initWithLibrary:(id)arg1;

@end

