//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableView.h"

@class NSTrackingArea;

__attribute__((visibility("hidden")))
@interface FFRolloverTableView : NSTableView
{
    NSTrackingArea *_track;
    BOOL _mouseOverView;
    long long _mouseOverRow;
    long long _mouseOverCol;
    long long _lastOverRow;
}

@property long long mouseOverColumn; // @synthesize mouseOverColumn=_mouseOverCol;
@property long long mouseOverRow; // @synthesize mouseOverRow=_mouseOverRow;
- (void)viewDidEndLiveResize;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (void)updateTrackingAreas;
- (void)removeTracking;
- (void)addTracking;
- (void)dealloc;
- (void)awakeFromNib;

@end

