//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSString;

__attribute__((visibility("hidden")))
@interface FFSampleGenerator : NSObject
{
    struct OpaqueFigSampleGenerator *m_figSampleGenerator;
    NSObject<OS_dispatch_semaphore> *m_generatorSemaphore;
    _Bool m_usingScheduledIO;
    struct OpaqueFigSampleCursorService *m_figSampleCursorService;
    NSString *m_eventDocumentIDAndPath;
    int m_numSamplesPerFrame;
    struct OpaqueFigSampleCursor *m_figSampleCursor;
    NSObject<OS_dispatch_semaphore> *m_cursorSemaphore;
    CDStruct_1b6d18a9 m_ptsOfFirstSampleInDecodeOrder;
    NSObject<OS_dispatch_queue> *m_queues[3];
    NSObject<OS_dispatch_group> *m_group;
    struct FFChunkedSampleBufferCache *m_csbCache;
    _Bool m_copiedFromCSBCacheTable;
}

- (id).cxx_construct;
- (_Bool)usingScheduledIO;
- (id)eventDocumentIDAndPath;
- (int)numSamplesPerFrame;
- (struct opaqueCMSampleBuffer *)createSampleBuffer:(id)arg1;
- (void)prefetch:(id)arg1 schedToken:(id)arg2;
- (CDStruct_1b6d18a9)getPresentationTimeStampOfFirstSampleInDecodeOrder;
- (id)newFFSampleCursorAtPresentationTimeStamp:(CDStruct_1b6d18a9)arg1 fieldDuration:(CDStruct_1b6d18a9)arg2;
- (struct OpaqueFigSampleCursor *)createFigSampleCursorAtPresentationTimeStamp:(CDStruct_1b6d18a9)arg1;
- (void)dealloc;
- (id)initWithFigSampleGenerator:(struct OpaqueFigSampleGenerator *)arg1 usingScheduledIO:(_Bool)arg2 figSampleCursorService:(struct OpaqueFigSampleCursorService *)arg3 eventDocumentIDAndPath:(id)arg4 numSamplesPerFrame:(int)arg5;

@end

