//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFScheduleToken.h>

@class FFProviderOffline, FFVideoProps, NSArray, NSCondition, NSOperation;

__attribute__((visibility("hidden")))
@interface FFSchedTokenForOfflineProvider : FFScheduleToken
{
    FFProviderOffline *_provider;
    FFVideoProps *_videoProps;
    NSArray *_errorInfo;
    BOOL _forThumb;
    NSCondition *_cond;
    NSOperation *_op;
}

- (id)copyErrorInfoStoppingAfterFirstError:(BOOL)arg1;
- (_Bool)waitForStatusFlagsToClear:(unsigned int)arg1 beforeDate:(id)arg2;
- (unsigned int)scheduleStatusInformation;
- (unsigned int)_internal_scheduleStatusInformation:(_Bool)arg1;
- (void)dealloc;
- (id)initWithStream:(id)arg1 forThumb:(BOOL)arg2 videoProps:(id)arg3;

@end

