//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FFRenderProps, NSMutableArray, NSMutableDictionary, NSMutableIndexSet, NSString;

@interface FFSegmentStoreInfo : NSObject
{
    NSString *_segmentPath;
    NSString *_plistPath;
    NSMutableDictionary *_segmentInfoDict;
    NSMutableArray *_pixelTransformSerializedArray;
    CDStruct_bdcb2b0d _md5;
    FFRenderProps *_renderProps;
    unsigned int _encodedWidth;
    unsigned int _encodedHeight;
    int _fieldOrder;
    long long _firstSample;
    long long _bitDepth;
    long long _alphaMode;
    long long _fileFrameCount;
    NSMutableIndexSet *_storedFrameIndexes;
    unsigned int _nUpdates;
    NSMutableArray *_pixelTransformArray;
    NSMutableArray *_openStreamFiles;
    struct opaqueCMFormatDescription *_videoFormatDescription;
    struct opaqueCMFormatDescription *_videoFormatDescriptionForSampleBuffer;
    NSMutableArray *_compressionSessions;
    double _lastCompressionWallClockStamp;
}

- (id)initWithPath:(id)arg1 segmentStoreMD5:(CDStruct_60067b7e)arg2 renderProps:(id)arg3;
- (void)dealloc;
- (void)_maybeUpdateSegmentInfo;
- (void)ageOutCompressor:(BOOL)arg1;
- (BOOL)_quickApproximateFrameExists:(long long)arg1;
- (BOOL)frameExists:(long long)arg1;
- (id)newFrameData:(long long)arg1 threadInfo:(id)arg2 sampleObj:(id)arg3;
- (id)newImageFromFrameData:(id)arg1 sampleNumber:(long long)arg2 threadInfo:(id)arg3 requestedQuality:(int)arg4;
- (int)writeFrame:(id)arg1 image2:(id)arg2 fieldOrder:(int)arg3 sampleNumber:(long long)arg4 threadInfo:(id)arg5;
- (int)writeBuffer:(id)arg1 sampleNumber:(long long)arg2 threadInfo:(id)arg3;
- (id)renderProps;
- (id)storedFrameIndexes;
- (void)updateSegmentInfo;
- (id)copyFrameDataFileForSampleNumber:(long long)arg1 createFile:(BOOL)arg2;
- (id)fileNameForStartFrame:(long long)arg1 fileFrameCount:(long long)arg2;
- (unsigned long long)pixelTransformIndex:(id)arg1;
- (id)pixelTransformFromIndex:(unsigned long long)arg1;

@end

