//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFSegmentSample.h>

__attribute__((visibility("hidden")))
@interface FFSegmentWriteSample : FFSegmentSample
{
    id _sample2;
    int _fieldOrder;
    double _cost;
}

- (id)sample2;
- (void)main;
- (void)dealloc;
- (id)initWithSample:(id)arg1 sample2:(id)arg2 fieldOrder:(int)arg3 segmentStore:(id)arg4 offset:(long long)arg5 cost:(double)arg6;

@end

