//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCondition, NSOperationQueue;

__attribute__((visibility("hidden")))
@interface FFSegmentStoreOperationQueue : NSObject
{
    NSOperationQueue *_primaryQueue;
    NSOperationQueue *_housekeepingQueue;
    NSCondition *_guard;
    _Bool _mainThreadWaiting;
    int _waitersWithReadLock;
    unsigned int _queueLength;
    unsigned int _unfinishedOps;
}

- (void)waitForAllOperationsToFinish;
- (void)enqueueHousekeepingOp:(id)arg1;
- (void)performBlockWhenPendingSamplesFinish:(CDUnknownBlockType)arg1;
- (void)addInvocationWhenPendingSamplesFinish:(id)arg1;
- (void)cancelPendingOperations;
- (void)enqueue:(id)arg1 mustQueue:(BOOL)arg2;
- (_Bool)_spaceAvailable:(_Bool)arg1;
- (void)dealloc;
- (id)initWithThreadCount:(long long)arg1 queueLength:(unsigned int)arg2;

@end

