//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class CKSource, FFShareDestination, LKImageView, LKTextField, NSProView;

@interface FFShareDestinationController : NSViewController
{
    NSProView *_headerView;
    LKImageView *_imageView;
    LKTextField *_name;
    LKTextField *_infoText;
    NSProView *_expandableView;
    FFShareDestination *_destination;
    CKSource *_source;
    CDUnknownBlockType _completionHandler;
}

+ (id)inactiveHighlightGradient;
+ (id)activeHighlightGradient;
+ (id)shareDestinationControllerForDestination:(id)arg1;
@property(retain, nonatomic) CKSource *source; // @synthesize source=_source;
@property(retain, nonatomic) FFShareDestination *destination; // @synthesize destination=_destination;
@property(retain, nonatomic) NSProView *expandableView; // @synthesize expandableView=_expandableView;
@property(retain, nonatomic) LKTextField *infoText; // @synthesize infoText=_infoText;
@property(retain, nonatomic) LKTextField *name; // @synthesize name=_name;
@property(retain, nonatomic) LKImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSProView *headerView; // @synthesize headerView=_headerView;
- (id)destinationNameByAppendingUserNameFrom:(id)arg1;
- (id)destinationNameByRemovingUserNameFrom:(id)arg1;
- (id)extractUsernameFrom:(id)arg1;
- (long long)optimalStompSettingIndex;
- (struct CGSize)actualVideoResolutionFromPotentialVideoResolution:(struct CGSize)arg1;
- (long long)buildSettingsMenu:(id)arg1 withSize:(BOOL)arg2 withOne:(BOOL)arg3;
- (void)selectSetting:(id)arg1;
- (BOOL)displaysDeviceCompatibilityInfo;
- (long long)showModalPanelIfNeeded;
- (void)showPanelIfNeededModalForWindow:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)theImageForResource:(id)arg1;
- (void)dealloc;
- (id)initWithDestination:(id)arg1 withSource:(id)arg2;
- (id)initWithNibName:(id)arg1 withDestination:(id)arg2 withSource:(id)arg3;

@end

