//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFShareDestinationVideoResolutionMenuMaker.h>

__attribute__((visibility("hidden")))
@interface FFShareDestinationVideoResolutionMenuMakerMXF : FFShareDestinationVideoResolutionMenuMaker
{
}

- (id)enabledVideoResolutionsForMXFWithoutDestination:(id)arg1;
- (id)enabledVideoResolutionsForMXFWithDestination:(id)arg1;
- (id)enabledVideoResolutionsForMXF;
- (void)populateMenu;

@end

