//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKSource;

__attribute__((visibility("hidden")))
@interface FFShareVideoPreviewTimeConverter : NSObject
{
    CKSource *_source;
}

@property(retain, nonatomic) CKSource *source; // @synthesize source=_source;
- (BOOL)isExportingASelection;
- (double)normalizedTimeFromPreviewTimeWhenExportingSelection:(double)arg1;
- (double)normalizedTimeFromPreviewTime:(double)arg1;
- (double)previewTimeFromNormalizedTimeWhenExportingSelection:(double)arg1;
- (double)previewTimeFromNormalizedTime:(double)arg1;
@property(readonly, nonatomic) double sourceCurrentFrameTime;
- (void)dealloc;

@end

