//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSPopoverDelegate.h"

@class NSPopover, NSSet, NSString;

__attribute__((visibility("hidden")))
@interface FFShareDisabledRolesViewController : NSViewController <NSPopoverDelegate>
{
    NSPopover *_hostingPopover;
    BOOL _hasHomogeneousDisabledRoles;
    NSSet *_disabledRoles;
}

+ (id)sharedDisabledRolesViewControllerWithDisabledRoles:(id)arg1 hasHomogeneousDisabledRoles:(BOOL)arg2;
+ (id)sharedDisabledRolesViewControllerWithDisabledRoles:(id)arg1;
+ (id)sharedDisabledRolesViewController;
@property(retain, nonatomic) NSSet *disabledRoles; // @synthesize disabledRoles=_disabledRoles;
@property(nonatomic) BOOL hasHomogeneousDisabledRoles; // @synthesize hasHomogeneousDisabledRoles=_hasHomogeneousDisabledRoles;
- (void)close;
- (void)showRelativeToRect:(struct CGRect)arg1 ofView:(id)arg2 preferredEdge:(unsigned long long)arg3;
- (void)dealloc;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

