//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFSharePanelRolesListHeaderBrickViewController.h>

@class FFSharePanelAudioChildBrick;

__attribute__((visibility("hidden")))
@interface FFSharePanelRolesListAudioHeaderBrickViewController : FFSharePanelRolesListHeaderBrickViewController
{
}

- (id)newEditTrackViewController;

// Remaining properties
@property(retain) FFSharePanelAudioChildBrick *representedObject; // @dynamic representedObject;

@end

