//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFSharePanelBrick.h>

__attribute__((visibility("hidden")))
@interface FFSharePanelParentBrick : FFSharePanelBrick
{
    unsigned long long _count;
}

@property(nonatomic) unsigned long long count; // @synthesize count=_count;
- (void)addVideoChildBrick;
- (void)addAudioChildBrick;
@property(readonly, nonatomic) BOOL canAddAudioChildBrick;
@property(readonly, nonatomic) BOOL canAddVideoChildBrick;
- (id)initWithDataSource:(id)arg1;

@end

