//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FFModelLocking.h"

@class NSCondition, NSString;

@interface FFSharedLock : NSObject <FFModelLocking>
{
    NSCondition *_guard;
    NSString *_identifier;
    struct __CFBag *_readers;
    struct FFThread *_writer;
    int _writeRequested;
    int _readLockCount;
    int _readLockCountInsideWrite;
    int _writeLockCount;
}

+ (id)globalLock;
+ (void)initialize;
- (BOOL)_hasWriteLock;
- (void)_writeUnlock;
- (void)_writeLock;
- (void)_readUnlock;
- (void)_readLockEvenIfWriteRequestPending;
- (void)_readLock;
- (void)_readLock:(BOOL)arg1;
- (void)dealloc;
- (id)init;

@end

