//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFShareDestinationVideoPresetsMakerVideoCase.h>

__attribute__((visibility("hidden")))
@interface FFShareDestinationVideoPresetsMakerNonBroadcastVideoCase : FFShareDestinationVideoPresetsMakerVideoCase
{
}

+ (BOOL)isCapableOfHandlingDestination:(id)arg1 source:(id)arg2;
- (BOOL)isSameAsSourceSetting:(id)arg1;
- (id)presetForSetting:(id)arg1;
- (void)appendPresetsToSet:(id)arg1 stompSetting:(id)arg2;
- (id)presets;

@end

