//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FFPlayerVideoModule, NSMutableArray;

__attribute__((visibility("hidden")))
@interface FFSnapGrid : NSObject
{
    NSMutableArray *_snapsHor;
    NSMutableArray *_snapsVer;
    int _activeHorIndex;
    int _activeVerIndex;
    BOOL _enabled;
    FFPlayerVideoModule *_videoModule;
    BOOL _isBuilt;
}

- (id)initWithPlayerVideoModule:(id)arg1;
- (void)dealloc;
- (void)setPlayerVideoModule:(id)arg1;
- (void)build;
- (id)horizontalSnaps;
- (id)verticalSnaps;
- (BOOL)isBuilt;
- (BOOL)isEnabled;
- (void)clearGrid;
@property BOOL enabled; // @synthesize enabled=_enabled;
@property int activeHorIndex; // @synthesize activeHorIndex=_activeHorIndex;
@property int activeVerIndex; // @synthesize activeVerIndex=_activeVerIndex;

@end

