//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFSource.h>

@interface FFSourceMetadata : FFSource
{
}

+ (Class)streamClass;
+ (id)spotlightMetadataForURL:(id)arg1;
- (id)type;
- (id)newStream:(id)arg1 options:(id)arg2;

@end

