//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFSourceAudio.h>

__attribute__((visibility("hidden")))
@interface FFSourceAudioOffline : FFSourceAudio
{
    CDStruct_1b6d18a9 _start;
    CDStruct_1b6d18a9 _duration;
}

+ (Class)streamClass;
+ (id)type;
- (double)sampleRate;
- (unsigned int)numberOfChannels;
- (CDStruct_e83c9415)timeRange;
- (void)setDuration:(CDStruct_1b6d18a9)arg1;
- (void)setStart:(CDStruct_1b6d18a9)arg1;
- (id)initWithProvider:(id)arg1;

@end

