//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFShapeMaskEffect.h>

__attribute__((visibility("hidden")))
@interface FFSplineMaskEffect : FFShapeMaskEffect
{
    unsigned int _numberOfVertices;
}

+ (struct FFShape *)previewShape;
+ (void)registerEffects;
- (struct FFShape *)getShapeForRenderWithContext:(id)arg1;
- (BOOL)shouldRenderShape:(struct FFShape *)arg1 atTime:(CDStruct_1b6d18a9)arg2;
- (id)onScreenControlsForChannelFolder:(id)arg1 effectStack:(id)arg2;
- (id)newChannelFolderWithParent:(id)arg1 name:(id)arg2;
- (id)channelFolder;
- (void)setShapeData:(struct FFShape *)arg1;
- (void)channelParameterChanged:(id)arg1;
- (void)createChannelsInFolder:(id)arg1;
- (struct FFShape *)createShape;
- (void)dealloc;

@end

