//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class TLKImageLayer;

__attribute__((visibility("hidden")))
@interface FFSpeedTransitionLayer : CALayer
{
    id _item;
    BOOL _isModelLayer;
    TLKImageLayer *_backgroundLayer;
    CDStruct_e83c9415 _timeRange;
    struct CGSize _themeFacetImageSize;
    struct CGSize _themeFacetBottomLeft;
    struct CGSize _themeFacetTopRight;
}

- (void)layoutSublayers;
- (void)setTimeRange:(CDStruct_e83c9415)arg1;
- (CDStruct_e83c9415)timeRange;
- (BOOL)layer:(id)arg1 shouldInheritContentsScale:(double)arg2 fromWindow:(id)arg3;
- (void)dealloc;
- (id)initWithItem:(id)arg1 module:(id)arg2;

@end

