//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFStreamOptions.h>

@class NSMapTable, NSSet;

@interface FFStreamAudioOptions : FFStreamOptions
{
    double _sampleRate;
    unsigned int _numChannels;
    BOOL _forPlayback;
    unsigned long long _streamAudioFlags;
    NSSet *_playObjects;
    NSMapTable *_streamAudioFlagsForPlayObjects;
}

- (id)initWithSampleRate:(double)arg1 numChannels:(unsigned int)arg2 forPlayback:(BOOL)arg3;
- (id)initWithAudioOptions:(id)arg1;
- (id)initWithAudioOptionsForDescendant:(id)arg1;
- (void)dealloc;
- (double)sampleRate;
- (unsigned int)numChannels;
- (BOOL)isForPlayback;
- (id)playObjects;
- (BOOL)streamAudioFlagsForPlayObject:(id)arg1 streamFlags:(unsigned long long *)arg2 streamFlagsMask:(unsigned long long *)arg3;
@property(readonly, nonatomic) unsigned long long streamAudioFlags; // @synthesize streamAudioFlags=_streamAudioFlags;

@end

