//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFStreamMetadata.h>

__attribute__((visibility("hidden")))
@interface FFStreamMetadataCG : FFStreamMetadata
{
}

- (id)metadata;
- (id)dictionaryWithPrefixType:(id)arg1 forDictionary:(id)arg2;
- (id)periodsvStringFromArray:(id)arg1;
- (id)cfsvStringFromArray:(id)arg1;
- (id)commasvStringFromArray:(id)arg1;
- (id)_separatedStringFromArray:(id)arg1 separator:(id)arg2 justCallStringValue:(BOOL)arg3;

@end

