//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FFStreamAudio;

__attribute__((visibility("hidden")))
@interface FFStreamAudioRenderContext : NSObject
{
    struct FFAudioGraphRenderSession *_renderSession;
    FFStreamAudio *_stream;
    unsigned int _channelBitmap;
    struct CAStreamBasicDescription *_format;
    long long _streamPrerollTime;
    BOOL _prerolledStream;
    long long _nextRenderTime;
    long long _numPreparedFrames;
}

@property(readonly, nonatomic) long long nextRenderTime; // @synthesize nextRenderTime=_nextRenderTime;
- (int)renderFrames:(unsigned int)arg1 buffers:(struct AudioBufferList *)arg2 framesRendered:(unsigned int *)arg3;
- (int)prepareRenderFrames:(unsigned int)arg1;
- (BOOL)canUseContextWithStartTime:(long long)arg1 format:(struct AudioStreamBasicDescription)arg2 channelBitmap:(unsigned int)arg3;
- (void)dealloc;
- (id)initWithStream:(id)arg1 prerollTime:(long long)arg2 format:(struct AudioStreamBasicDescription)arg3 channelBitmap:(unsigned int)arg4;

@end

