//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Flexo/FFTaskProgressViewController.h>

@class CALayer, CAShapeLayer, LKButton, LKProgressIndicator, LKTextField, NSImageView;

@interface FFTaskProgressIndicator : FFTaskProgressViewController
{
    LKTextField *_backgroundPercentage;
    LKTextField *_percentageString;
    NSImageView *_progressFinished;
    NSImageView *_progressEmpty;
    NSImageView *_progressFilling;
    LKProgressIndicator *_progressSpinner;
    LKButton *_backgroundTasksButton;
    BOOL _progressIndeterminate;
    BOOL _progressIsFilling;
    double _currentProgress;
    long long _lastProgressValueDrawn;
    CALayer *_progressLayer;
    CAShapeLayer *_progressMaskLayer;
    id _clickTarget;
    SEL _clickAction;
}

- (void)updateProgressFillMaskToValue:(long long)arg1;
- (void)setBackgroundProgress:(long long)arg1 evenIfValueUnchanged:(BOOL)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)toggleBackgroundTasks:(id)arg1;
- (void)setClickTarget:(id)arg1 action:(SEL)arg2;
- (void)shouldUpdateWithTaskProgressNotifications:(BOOL)arg1;
- (void)viewDidDisappear;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (void)appWillTerminate:(id)arg1;
- (void)dealloc;
- (void)_unregisterForNotifications;
- (void)_registerForNotifications;
- (void)viewDidLoad;

@end

