//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface FFTimelineLayerTitleUpdateRequest : NSObject
{
    BOOL _isMultiAngleTrack;
    int _containmentType;
    id _representedObject;
    NSArray *_buttonLayerReps;
    NSString *_displayName;
}

@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(copy, nonatomic) NSArray *buttonLayerReps; // @synthesize buttonLayerReps=_buttonLayerReps;
@property(retain, nonatomic) id representedObject; // @synthesize representedObject=_representedObject;
@property(nonatomic) BOOL isMultiAngleTrack; // @synthesize isMultiAngleTrack=_isMultiAngleTrack;
@property(nonatomic) int containmentType; // @synthesize containmentType=_containmentType;
- (void)dealloc;

@end

