//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProTimecodeFormatter.h"

__attribute__((visibility("hidden")))
@interface FFTimecodeFormatter : NSProTimecodeFormatter
{
}

+ (id)sharedInstance;
+ (void)releaseSharedInstance;
- (void)_FFTimecodeFormatter_init;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

