//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFCurvesLayer.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface FFVideoCurvesLayer : FFCurvesLayer
{
    NSMutableDictionary *_dummyIntrinsics;
}

- (BOOL)validateUserInterfaceItem:(id)arg1;
- (id)effectStack;
- (BOOL)sender:(id)arg1 willSetChannel:(id)arg2;
- (id)effectsToDisplay;
- (void)dealloc;
- (id)initWithObject:(id)arg1 topToBottom:(BOOL)arg2 timeline:(id)arg3;
- (void)initializeIntrinsicDummys;
- (id)intrinsicOrDummyWithID:(id)arg1;

@end

