//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FFMetadataViewSet, NSArray, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface FFViewSetEditorExtendedViewSet : NSObject
{
    FFMetadataViewSet *_representedObject;
    NSString *_displayName;
    NSString *_userModifiable;
    NSMutableArray *_properties;
}

@property(retain, nonatomic) NSArray *properties; // @synthesize properties=_properties;
@property(retain, nonatomic) NSString *userModifiable; // @synthesize userModifiable=_userModifiable;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(retain, nonatomic) FFMetadataViewSet *representedObject; // @synthesize representedObject=_representedObject;
- (id)propertyFromKey:(id)arg1;
- (void)removeProperty:(id)arg1;
- (void)addProperty:(id)arg1;
- (void)setPropertiesFromMetadataViewSet:(id)arg1;
- (void)setKeysFromMetadataViewSet:(id)arg1;
- (void)dealloc;
- (id)initWithMetadataViewSet:(id)arg1;

@end

