//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Flexo/NSSecureCoding-Protocol.h>

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface FFXMLVideoReservedData : NSObject <NSSecureCoding>
{
    int _rotationAngle;
    NSDictionary *_HETrimValues;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) NSDictionary *HETrimValues; // @synthesize HETrimValues=_HETrimValues;
@property(nonatomic) int rotationAngle; // @synthesize rotationAngle=_rotationAngle;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

