//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FFAnchoredSequence, FFMediaEventProject, FFProject, FFStorageLocation, NSMapTable, NSMutableArray, NSURL, NSXMLDocument;

__attribute__((visibility("hidden")))
@interface FFXMLImporter : NSObject
{
    NSXMLDocument *_xmlDoc;
    NSURL *_baseURL;
    FFProject *_project;
    FFMediaEventProject *_eventProject;
    FFAnchoredSequence *_sequence;
    FFStorageLocation *_defaultStorage;
    NSMapTable *_resByResID;
    NSMutableArray *_modifiedEvents;
    NSMutableArray *_errors;
    NSMutableArray *_warnings;
    NSMapTable *_audioOnlyMap;
    unsigned long long _audioOnlyCheck;
}

- (id)_errorDict:(id)arg1 detail:(id)arg2;
- (id)error:(id)arg1 code:(int)arg2;
- (id)error:(id)arg1 detail:(id)arg2;
- (id)error:(id)arg1 node:(id)arg2 attr:(id)arg3;
- (void)log:(id)arg1 warningOnly:(BOOL)arg2;
- (id)warnings;
- (void)makeDefaultClipsForNewMedia:(id)arg1;
- (void)addModifiedEvent:(id)arg1;
- (BOOL)processModifiedEvents:(id *)arg1;
- (void)setChannel:(id)arg1 stringValue:(id)arg2 atTime:(CDStruct_1b6d18a9)arg3 isRadians:(BOOL)arg4;
- (id)copyParameterNode:(id)arg1;
- (BOOL)allowAdjustmentsForObject:(id)arg1;
- (void)addFormat:(id)arg1 toObject:(id)arg2;
- (void)addAudioRouting:(id)arg1 toObject:(id)arg2;
- (void)addAttributes:(id)arg1 toObject:(id)arg2;
- (void)addRoles:(id)arg1 toObject:(id)arg2;
- (void)addColorInfo:(id)arg1 toObject:(id)arg2;
- (void)addFadeIn:(id)arg1 channel:(id)arg2 toObject:(id)arg3;
- (void)addFadeOut:(id)arg1 channel:(id)arg2 toObject:(id)arg3;
- (void)addParameterNode:(id)arg1 channel:(id)arg2 toObject:(id)arg3;
- (void)addParam:(id)arg1 channel:(id)arg2 toObject:(id)arg3;
- (void)addAttributes:(id)arg1 map:(id)arg2 toObject:(id)arg3;
- (void)addAdjustment:(id)arg1 type:(CDUnknownFunctionPointerType)arg2 toObject:(id)arg3;
- (void)addCropInfo:(id)arg1 toObject:(id)arg2;
- (void)addAudioPanner:(id)arg1 toObject:(id)arg2;
- (void)addIntrinsicChannels:(id)arg1 toObject:(id)arg2;
- (void)addAngleData:(id)arg1 toObject:(id)arg2;
- (void)updateDisplayName:(id)arg1 node:(id)arg2;
- (id)newMediaComponentFromNode:(id)arg1 sourceKey:(id)arg2;
- (id)newEffectComponentFromNode:(id)arg1;
- (id)newAuditionFromNode:(id)arg1 inParent:(id)arg2;
- (id)newMulticamMedia:(id)arg1 name:(id)arg2 identifier:(id)arg3 eventProject:(id)arg4 error:(id *)arg5;
- (id)newMulticamClip:(id)arg1 inParent:(id)arg2 error:(id *)arg3;
- (id)newMulticamAngleNode:(id)arg1;
- (void)addMulticamAngleNode:(id)arg1 toObject:(id)arg2;
- (void)addAnchoredNode:(id)arg1 media:(id)arg2 toObject:(id)arg3;
- (void)addContainedNode:(id)arg1 media:(id)arg2 toObject:(id)arg3;
- (void)addEffectNode:(id)arg1 toObject:(id)arg2;
- (void)addGapNode:(id)arg1 toObject:(id)arg2;
- (void)addAVNode:(id)arg1 toObject:(id)arg2 type:(id)arg3;
- (void)addVideoNode:(id)arg1 toObject:(id)arg2;
- (void)addAudioNode:(id)arg1 toObject:(id)arg2;
- (void)addMulticamClipNode:(id)arg1 toObject:(id)arg2;
- (void)addClipNode:(id)arg1 toObject:(id)arg2;
- (void)addSpineNode:(id)arg1 toObject:(id)arg2;
- (void)addAuditionNode:(id)arg1 toObject:(id)arg2;
- (void)addTransitionNodes:(id)arg1 toSpine:(id)arg2;
- (void)addTitleNode:(id)arg1 toObject:(id)arg2;
- (void)addFilterNode:(id)arg1 video:(id)arg2 audio:(id)arg3 toObject:(id)arg4;
- (void)addFilterNode:(id)arg1 toObject:(id)arg2;
- (void)addNoteNode:(id)arg1 toObject:(id)arg2;
- (void)addKeywordNode:(id)arg1 toObject:(id)arg2;
- (void)addRatingNode:(id)arg1 toObject:(id)arg2;
- (void)addMarkerNode:(id)arg1 toObject:(id)arg2;
- (void)addTimeMapNode:(id)arg1 toObject:(id)arg2;
- (void)_addEdits:(id)arg1 toObject:(id)arg2;
- (void)addEdits:(id)arg1 toObject:(id)arg2 parent:(id)arg3;
- (Class)documentClassForProjectNode:(id)arg1;
- (id)locationForProjectNode:(id)arg1 error:(id *)arg2;
- (id)newOfflineAssetRef:(id)arg1 eventProject:(id)arg2 error:(id *)arg3;
- (id)newAssetRefFromResource:(id)arg1 eventProject:(id)arg2 error:(id *)arg3;
- (id)resolveEvent:(id)arg1 create:(BOOL)arg2 error:(id *)arg3;
- (id)registerProjectRef:(id)arg1;
- (id)copyClipRef:(id)arg1 error:(id *)arg2;
- (id)copyAssetRef:(id)arg1 error:(id *)arg2;
- (id)createEventDocument:(id)arg1 name:(id)arg2 error:(id *)arg3;
- (id)bindExternalProject:(id)arg1 create:(BOOL)arg2 error:(id *)arg3;
- (void)prepareResources:(id)arg1 defaultEventID:(id)arg2;
- (void)closeAndDeleteDocumentFiles:(id)arg1;
- (id)newSequenceProjectFromNode:(struct NSXMLElement *)arg1 error:(id *)arg2;
- (id)newMulticamMediaSetItem:(id)arg1;
- (id)newClipMediaSetItem:(id)arg1;
- (id)newAuditionMediaSetItem:(id)arg1;
- (id)newEventProjectFromNode:(struct NSXMLElement *)arg1 error:(id *)arg2;
- (id)import:(id *)arg1;
- (id)prepareDocument:(id)arg1 error:(id *)arg2;
- (id)initWithURL:(id)arg1 location:(id)arg2 error:(id *)arg3;
- (void)dealloc;

@end

