//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/FFZipFileExtractor.h>

__attribute__((visibility("hidden")))
@interface FFZipFileExtractor_SFU : FFZipFileExtractor
{
}

- (BOOL)entry:(void *)arg1 asFile:(id)arg2 error:(id *)arg3;
- (id)entryAsData:(void *)arg1 error:(id *)arg2;
- (id)entryPath:(void *)arg1 error:(id *)arg2;
- (BOOL)iterateEntries:(CDUnknownBlockType)arg1 error:(id *)arg2;

@end

