//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <iLifeMediaBrowser/ILMediaManager.h>

@interface ILMediaManager (FFAdditions)
- (id)ff_mediaGroupsForIdentifiers:(id)arg1;
- (id)ff_mediaSourceIdentifier;
@end

