//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <LunaKit/LKTimecode.h>

@interface LKTimecode (FFShareAdditions)
- (id)copyWithSeconds:(double)arg1;
@end

