//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImage.h"

@interface NSImage (Additions)
+ (id)newImageForPixelSize:(struct CGSize)arg1 withBlock:(CDUnknownBlockType)arg2;
+ (id)imageNamed:(id)arg1 fromBundle:(id)arg2;
+ (id)imageWithContentsOfFile:(id)arg1 respectOrientation:(BOOL)arg2;
+ (struct CGImage *)newCGImageByApplyingOrientation:(int)arg1 toCGImage:(struct CGImage *)arg2;
+ (struct CGAffineTransform)affineTransformWithImageOrientation:(int)arg1 width:(unsigned long long)arg2 height:(unsigned long long)arg3;
- (id)initWithCGImage:(struct CGImage *)arg1;
- (void)removeCachedImageReps;
- (void)useOptimalDPI;
- (BOOL)writeToTIFFFile:(id)arg1;
- (BOOL)writeToPNGFile:(id)arg1;
- (BOOL)writeToJPEGFile:(id)arg1 quality:(float)arg2;
- (id)compressedPNG;
- (id)compressedJPEG:(float)arg1;
- (id)imageLetterBoxedOrPillarBoxedForAspectRatio:(float)arg1;
- (id)imageWithOverlaidText:(id)arg1;
- (id)imageWithAlpha:(float)arg1;
- (id)imageByCrossDissolvingWithImage:(id)arg1 inRect:(struct CGRect)arg2 percent:(float)arg3;
- (id)imageByCrossDissolvingWithImage:(id)arg1 percent:(float)arg2;
- (id)imageCroppedAndResized:(struct CGSize)arg1 allowEnlarging:(BOOL)arg2;
- (id)imageCroppedToRect:(struct CGRect)arg1;
- (id)imageScaledToWidth:(float)arg1 maintainAspectRatio:(BOOL)arg2;
- (id)imageScaledByAmount:(float)arg1;
- (id)imageScaledToSize:(struct CGSize)arg1;
- (id)imageScaledToSize:(struct CGSize)arg1 highQuality:(BOOL)arg2;
- (id)deinterlacedImage:(int)arg1;
- (void)tileInRect:(struct CGRect)arg1 inView:(id)arg2 operation:(unsigned long long)arg3 fraction:(float)arg4;
- (void)tileInRect:(struct CGRect)arg1 inView:(id)arg2 operation:(unsigned long long)arg3 fraction:(float)arg4 offset:(struct CGPoint)arg5;
- (void)drawInRect:(struct CGRect)arg1 inView:(id)arg2 fromRect:(struct CGRect)arg3 operation:(unsigned long long)arg4 fraction:(float)arg5 mode:(int)arg6;
- (void)drawInRect:(struct CGRect)arg1 inView:(id)arg2 fromRect:(struct CGRect)arg3 operation:(unsigned long long)arg4 fraction:(float)arg5;
- (float)aspectRatio;
- (struct CGRect)bounds;
@end

