//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/NSObject-Protocol.h>

@class NSArray, NSMenu, NSMenuItem, NSString, NSView, PAELUTRepositoryController, PAELUTRepositoryItem;

@protocol PAELUTRepositoryControllerDelegate <NSObject>

@optional
- (void)controller:(PAELUTRepositoryController *)arg1 didEndOpenPanelForMenu:(NSMenu *)arg2 result:(long long)arg3;
- (void)controller:(PAELUTRepositoryController *)arg1 willBeginOpenPanelForMenu:(NSMenu *)arg2;
- (BOOL)controller:(PAELUTRepositoryController *)arg1 enablesMenuItem:(NSMenuItem *)arg2;
- (void)controller:(PAELUTRepositoryController *)arg1 populateMenu:(NSMenu *)arg2 wantsRecents:(char *)arg3;
- (void)controller:(PAELUTRepositoryController *)arg1 didInstallItem:(PAELUTRepositoryItem *)arg2;
- (NSView *)openPanelAccessoryViewForController:(PAELUTRepositoryController *)arg1;
- (NSString *)customLUTHeaderForController:(PAELUTRepositoryController *)arg1;
- (NSString *)chooseCustomLUTTitleForController:(PAELUTRepositoryController *)arg1;
- (NSArray *)allowedFileTypesForController:(PAELUTRepositoryController *)arg1;
- (NSString *)openPanelTitleForController:(PAELUTRepositoryController *)arg1;
@end

