//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TLKit/TLKAnchorLayer.h>

@class FFRoleColorScheme;

__attribute__((visibility("hidden")))
@interface PEAnchorLayer : TLKAnchorLayer
{
    FFRoleColorScheme *_colorScheme;
}

@property(retain) FFRoleColorScheme *colorScheme; // @synthesize colorScheme=_colorScheme;
- (void)updateAppearance;
- (void)dealloc;

@end

