//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface Radar : NSObject
{
}

+ (void)newProblemWithTitle:(id)arg1 withDescription:(id)arg2 withSeverity:(int)arg3;

@end

