//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSDictionary;

@protocol TLKItemLayerInfo
@property(readonly) BOOL clipTrimmedClip;
@property(readonly) double trailingEdgeInset;
@property(readonly) double leadingEdgeInset;
@property(readonly) BOOL audioComponent;
@property(readonly) BOOL splitEdit;
@property(readonly) BOOL draggedItem;
@property(readonly) BOOL timelineZooming;
@property(readonly) struct CGRect videoLayerFrame;
@property(readonly) struct CGRect audioLayerFrame;
@property(readonly) struct CGRect visibleBounds;
@property(retain) NSDictionary *userInfoDictionary;
- (NSArray *)timeSegmentTimePerPoints;
- (NSArray *)timeSegmentTimeScalesegmentRanges;
- (NSArray *)timeSegmentTimes;
@end

