//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, TLKItemComponentFragment, TLKItemComponentInfo, TLKLayoutManager, TLKLayoutTile;

@protocol TLKLayoutManagerDelegate <NSObject>

@optional
- (void)layoutManagerWillBeginLayout:(TLKLayoutManager *)arg1;
- (void)layoutManagerDidEndLayout:(TLKLayoutManager *)arg1;
- (struct CGRect)layoutManager:(TLKLayoutManager *)arg1 willUseLineFragmentRect:(struct CGRect)arg2 forItems:(NSArray *)arg3 inTimeRange:(CDStruct_e83c9415)arg4;
- (struct CGRect)layoutManager:(TLKLayoutManager *)arg1 willUseLayoutFrame:(struct CGRect)arg2 forItemComponentFragment:(TLKItemComponentFragment *)arg3;
- (void)layoutManager:(TLKLayoutManager *)arg1 didCompleteLayoutForTile:(TLKLayoutTile *)arg2 atEnd:(BOOL)arg3;
- (double)layoutManager:(TLKLayoutManager *)arg1 heightForItemComponent:(TLKItemComponentInfo *)arg2 proposedHeight:(double)arg3;
@end

