//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Flexo/NSObject-Protocol.h>

@class NSString;

@protocol TLKPosterFrameInfoProtocol <NSObject>
- (BOOL)defaultPosition;
- (NSString *)label;
- (CDStruct_1b6d18a9)posterTime;
@end

