//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class _PAEFTCurveColorPickerLayer;

@interface _PAEFTCurveColorSelectionLayer : CALayer
{
    _PAEFTCurveColorPickerLayer *_colorPickerLayer;
}

- (id)actionForKey:(id)arg1;
- (void)layoutSublayers;
- (void)setBounds:(struct CGRect)arg1;
- (void)setNeedsDisplay;
- (void)setContentsScale:(double)arg1;
- (void)buildSublayers;
- (void)setColor:(id)arg1;

@end

