//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FxOnScreenControl_v2.h"

@class NSMutableArray, PAEOSC;

@interface PAEOSCManager : NSObject <FxOnScreenControl_v2>
{
    id <PROAPIAccessing> _apiManager;
    NSMutableArray *_OSCs;
    PAEOSC *_focus;
    long long _focusPart;
    PCVector2_79efa81a _mousePosition;
    PCVector2_79efa81a _mouseDownPosition;
}

@property(readonly) id api; // @synthesize api=_apiManager;
- (id).cxx_construct;
- (long long)focusPart;
- (id)focus;
- (void)notifyDidUnfocus:(id)arg1;
- (void)notifyDidFocus:(id)arg1;
- (PCVector2_79efa81a)mouseDownPosition;
- (PCVector2_79efa81a)mousePosition;
- (void)keyUp:(double)arg1 positionY:(double)arg2 keyPressed:(unsigned short)arg3 modifiers:(unsigned long long)arg4 forceUpdate:(char *)arg5 didHandle:(char *)arg6 time:(double)arg7;
- (void)keyDown:(double)arg1 positionY:(double)arg2 keyPressed:(unsigned short)arg3 modifiers:(unsigned long long)arg4 forceUpdate:(char *)arg5 didHandle:(char *)arg6 time:(double)arg7;
- (void)mouseUp:(double)arg1 positionY:(double)arg2 activePart:(long long)arg3 modifiers:(unsigned long long)arg4 forceUpdate:(char *)arg5 time:(double)arg6;
- (void)mouseDragged:(double)arg1 positionY:(double)arg2 activePart:(long long)arg3 modifiers:(unsigned long long)arg4 forceUpdate:(char *)arg5 time:(double)arg6;
- (void)mouseExitedWithPositionX:(double)arg1 positionY:(double)arg2 modifiers:(unsigned long long)arg3 forceUpdate:(char *)arg4 time:(double)arg5;
- (void)mouseMovedWithPositionX:(double)arg1 positionY:(double)arg2 activePart:(long long)arg3 modifiers:(unsigned long long)arg4 forceUpdate:(char *)arg5 time:(double)arg6;
- (void)mouseEnteredWithPositionX:(double)arg1 positionY:(double)arg2 modifiers:(unsigned long long)arg3 forceUpdate:(char *)arg4 time:(double)arg5;
- (void)mouseDown:(double)arg1 positionY:(double)arg2 activePart:(long long)arg3 modifiers:(unsigned long long)arg4 forceUpdate:(char *)arg5 time:(double)arg6;
- (void)drawEntireCanvasForSelectionWithWidth:(long long)arg1 height:(long long)arg2;
- (void)drawOSC:(long long)arg1 height:(long long)arg2 activePart:(long long)arg3 time:(double)arg4;
- (unsigned long long)drawingCoordinates;
- (void)addOSC:(id)arg1;
- (void)dealloc;
- (id)initWithAPIManager:(id)arg1;

@end

