//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ProAppsFxSupport/PAEOSC.h>

@interface PAEPointOSC : PAEOSC
{
    PCVector2_79efa81a _grab;
    BOOL _fixed;
    id <associatedOSC> _associatedOSC;
    BOOL _snapped;
    long long _currentState;
    PCPtr_e070f502 *_textures;
}

- (id).cxx_construct;
- (void)mouseMoved:(const PCVector2_79efa81a *)arg1 activePart:(int)arg2 modifiers:(unsigned long long)arg3 forceUpdate:(char *)arg4 time:(double)arg5;
- (void)mouseUp:(const PCVector2_79efa81a *)arg1 activePart:(int)arg2 modifiers:(unsigned long long)arg3 forceUpdate:(char *)arg4 time:(double)arg5;
- (void)mouseDragged:(const PCVector2_79efa81a *)arg1 activePart:(int)arg2 modifiers:(unsigned long long)arg3 forceUpdate:(char *)arg4 time:(double)arg5;
- (void)mouseDown:(const PCVector2_79efa81a *)arg1 activePart:(int)arg2 modifiers:(unsigned long long)arg3 forceUpdate:(char *)arg4 didHandle:(char *)arg5 time:(double)arg6;
- (void)drawForSelectionWithWidth:(int)arg1 height:(int)arg2 activePart:(int)arg3 paramAPI:(id)arg4 oscAPI:(id)arg5 atTime:(double)arg6;
- (void)drawForDisplayWithWidth:(int)arg1 height:(int)arg2 activePart:(int)arg3 paramAPI:(id)arg4 oscAPI:(id)arg5 atTime:(double)arg6;
- (float)currentRadius;
- (unsigned long long)currentState;
- (void)setAssociatedOSC:(id)arg1;
- (void)setFixed:(BOOL)arg1;
- (void)dealloc;
- (id)initWithAPIManager:(id)arg1;

@end

