//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProAppsFxSupport/PAEQualifierIndicatorLayer.h>

@class NSColor;

@interface PAEQualifierSpreadIndicatorLayer : PAEQualifierIndicatorLayer
{
    NSColor *_color;
}

- (void)_customDrawInContext:(struct CGContext *)arg1 bounds:(struct CGRect)arg2 image:(id)arg3;
- (id)_imageForButton;
@property(copy, nonatomic) NSColor *color;
- (void)dealloc;

@end

