//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <TLKit/TLKDragEdgesHandler.h>

@interface TLKClipTrimmerDragClipHandler : TLKDragEdgesHandler
{
    double _slipDraggingClipWidth;
}

- (double)draggingClipWidth;
- (BOOL)shouldAutoscroll:(id)arg1;
- (id)cursorAtPoint:(struct CGPoint)arg1 dispatcher:(id)arg2;
- (id)cursorNameAtPoint:(struct CGPoint)arg1 dispatcher:(id)arg2;
- (BOOL)stopTrackingWithCommit:(BOOL)arg1;
- (BOOL)startTracking:(id)arg1;
- (void)selectItem:(id)arg1;
- (id)clickedItem:(id)arg1;
- (id)partToDrag:(id)arg1;

@end

