//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <TLKit/TLKDebugLayer.h>

@class CATextLayer, NSString;

@interface TLKDebugBadgeLayer : TLKDebugLayer
{
    CATextLayer *_titleLayer;
}

@property(readonly, nonatomic) CATextLayer *titleLayer; // @synthesize titleLayer=_titleLayer;
- (void)_sizeToFit;
@property(copy, nonatomic) NSString *title;
- (void)setupAppearance;
- (void)dealloc;
- (id)init;

@end

