//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "TLKOperationPipingDestination.h"
#import "TLKOperationPipingSource.h"

@class NSArray, NSMutableArray, PCChangeLog, TLKDataSourceProxy, TLKLayoutDatabase;

@interface TLKFetchItemsFromDataSourceOperation : NSOperation <TLKOperationPipingSource, TLKOperationPipingDestination>
{
    NSMutableArray *_itemFetchResults;
    BOOL _syncHeightOnly;
    PCChangeLog *_inputChangeLog;
    PCChangeLog *_outputChangeLog;
    TLKDataSourceProxy *_dataSourceProxy;
    TLKLayoutDatabase *_database;
    double _defaultItemHeight;
    NSMutableArray *_insertedDataSourceItems;
    NSMutableArray *_updatedDataSourceItems;
    NSMutableArray *_dataSourceItemsNeedingLayoutOnly;
    NSMutableArray *_insertedItemFetchResults;
    NSMutableArray *_updatedItemFetchResults;
}

@property(readonly, nonatomic) NSMutableArray *updatedItemFetchResults; // @synthesize updatedItemFetchResults=_updatedItemFetchResults;
@property(readonly, nonatomic) NSMutableArray *insertedItemFetchResults; // @synthesize insertedItemFetchResults=_insertedItemFetchResults;
@property(readonly, nonatomic) NSMutableArray *dataSourceItemsNeedingLayoutOnly; // @synthesize dataSourceItemsNeedingLayoutOnly=_dataSourceItemsNeedingLayoutOnly;
@property(readonly, nonatomic) NSMutableArray *updatedDataSourceItems; // @synthesize updatedDataSourceItems=_updatedDataSourceItems;
@property(readonly, nonatomic) NSMutableArray *insertedDataSourceItems; // @synthesize insertedDataSourceItems=_insertedDataSourceItems;
@property(readonly, nonatomic) NSArray *itemFetchResults; // @synthesize itemFetchResults=_itemFetchResults;
@property(nonatomic) BOOL syncHeightOnly; // @synthesize syncHeightOnly=_syncHeightOnly;
@property(nonatomic) double defaultItemHeight; // @synthesize defaultItemHeight=_defaultItemHeight;
@property(retain, nonatomic) TLKLayoutDatabase *database; // @synthesize database=_database;
@property(retain, nonatomic) TLKDataSourceProxy *dataSourceProxy; // @synthesize dataSourceProxy=_dataSourceProxy;
@property(readonly) PCChangeLog *outputChangeLog; // @synthesize outputChangeLog=_outputChangeLog;
@property(copy) PCChangeLog *inputChangeLog; // @synthesize inputChangeLog=_inputChangeLog;
- (void)fetchPropertiesForDataSourceContainerItem:(id)arg1 intoFetchResult:(id)arg2;
- (void)fetchPropertiesForDataSourceItem:(id)arg1 intoFetchResult:(id)arg2;
- (void)fetchPropertiesForUpdatedDataSourceItems;
- (void)fetchPropertiesForInsertedDataSourceItems;
- (void)ignoreUpdatedDataSourceItemsWithoutEnclosingContainers;
- (void)ignoreInsertedDataSourceItemsWithoutEnclosingContainers;
- (void)_addConnectedItemsForAddedItems:(id)arg1;
- (void)pruneItemsWithNoContainerInModelFromArray:(id)arg1;
- (void)pruneItemsExistingInModelFromArray:(id)arg1;
- (void)pruneItemsNotInModelFromArray:(id)arg1;
- (void)collectDataSourceItemsFromInputChangeLog;
- (BOOL)inputChangeLogHasNoItemObjects;
- (void)fetchPropertiesFromDataSource;
- (void)main;
- (void)dealloc;
- (id)init;

@end

