//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "TLKOperationPipingDestination.h"
#import "TLKOperationPipingSource.h"

@class PCChangeLog, TLKLayoutDatabase, TLKTimelineView;

@interface TLKItemLayerContentsOperation : NSOperation <TLKOperationPipingSource, TLKOperationPipingDestination>
{
    PCChangeLog *_inputChangeLog;
    PCChangeLog *_outputChangeLog;
    TLKLayoutDatabase *_database;
    TLKTimelineView *_timelineView;
}

@property(nonatomic) TLKTimelineView *timelineView; // @synthesize timelineView=_timelineView;
@property(retain, nonatomic) TLKLayoutDatabase *database; // @synthesize database=_database;
@property(readonly) PCChangeLog *outputChangeLog; // @synthesize outputChangeLog=_outputChangeLog;
@property(copy) PCChangeLog *inputChangeLog; // @synthesize inputChangeLog=_inputChangeLog;
- (void)main;
- (id)_expandItemsToItemFragments:(id)arg1;
- (id)_allItemFragmentsWithUpdatedItems:(id)arg1;
- (id)modifiedItemFragments;
- (void)_findThroughEditDependenciesForItems:(id)arg1 intoSet:(id)arg2;
- (void)dealloc;
- (id)init;

@end

