//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TLKItemContentsLayerMock : NSObject
{
    BOOL _hidden;
    BOOL _splitEdit;
    BOOL _audioComponent;
    struct CGRect _audioLayerFrame;
    struct CGRect _videoLayerFrame;
}

@property(nonatomic) BOOL audioComponent; // @synthesize audioComponent=_audioComponent;
@property(nonatomic) BOOL splitEdit; // @synthesize splitEdit=_splitEdit;
@property(nonatomic) BOOL hidden; // @synthesize hidden=_hidden;
@property(nonatomic) struct CGRect videoLayerFrame; // @synthesize videoLayerFrame=_videoLayerFrame;
@property(nonatomic) struct CGRect audioLayerFrame; // @synthesize audioLayerFrame=_audioLayerFrame;

@end

