//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TLKItemContentsLayerMock : NSObject
{
    BOOL _hidden;
    BOOL _splitEdit;
    BOOL _audioComponent;
    struct CGRect _audioLayerFrame;
    struct CGRect _videoLayerFrame;
}

@property(nonatomic) BOOL audioComponent; // @synthesize audioComponent=_audioComponent;
@property(nonatomic) BOOL splitEdit; // @synthesize splitEdit=_splitEdit;
@property(nonatomic) BOOL hidden; // @synthesize hidden=_hidden;
@property(nonatomic) struct CGRect videoLayerFrame; // @synthesize videoLayerFrame=_videoLayerFrame;
@property(nonatomic) struct CGRect audioLayerFrame; // @synthesize audioLayerFrame=_audioLayerFrame;

@end

