//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface TLKLayoutMetrics : NSObject <NSCopying>
{
    double _baseSpineItemHeight;
    double _baseAnchoredItemHeight;
    double _baseSplitItemHeight;
    double _audioWaveFormProportion;
    double _itemHeightAdjustment;
    double _splitItemSpacingHeight;
    struct CGSize _itemSpacing;
    int _clipDisplayMode;
    struct {
        unsigned int showClipTitlesOnly:1;
        unsigned int RESERVED:31;
    } _tlkLayoutFlags;
}

- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) BOOL showClipTitlesOnly;
@property(readonly, nonatomic) double spineItemHeight;
- (double)anchoredItemHeightForItemType:(int)arg1 containmentMask:(int)arg2;
- (double)splitItemHeightForItemType:(int)arg1 containmentMask:(int)arg2;
@property(nonatomic) int displayMode; // @synthesize displayMode=_clipDisplayMode;
@property(nonatomic) double splitItemSpacingHeight; // @synthesize splitItemSpacingHeight=_splitItemSpacingHeight;
@property(nonatomic) struct CGSize itemSpacing; // @synthesize itemSpacing=_itemSpacing;
@property(nonatomic) double itemHeightAdjustment; // @synthesize itemHeightAdjustment=_itemHeightAdjustment;
@property(nonatomic) double audioWaveFormProportion; // @synthesize audioWaveFormProportion=_audioWaveFormProportion;
@property(nonatomic) double baseSplitItemHeight; // @synthesize baseSplitItemHeight=_baseSplitItemHeight;
@property(nonatomic) double baseAnchoredItemHeight; // @synthesize baseAnchoredItemHeight=_baseAnchoredItemHeight;
@property(nonatomic) double baseSpineItemHeight; // @synthesize baseSpineItemHeight=_baseSpineItemHeight;

@end

