//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSMutableSet, NSSet, PCChangeLog, TLKLayoutContext, TLKLayoutGraph;

@interface TLKLayoutAnchorsOperation : NSOperation
{
    TLKLayoutGraph *_layoutGraph;
    TLKLayoutContext *_layoutContext;
    long long _layoutRegion;
    NSSet *_itemComponents;
    PCChangeLog *_outputChangeLog;
    NSMutableSet *_processedItemComponents;
}

@property(readonly, nonatomic) NSMutableSet *processedItemComponents; // @synthesize processedItemComponents=_processedItemComponents;
@property(readonly, nonatomic) PCChangeLog *outputChangeLog; // @synthesize outputChangeLog=_outputChangeLog;
@property(readonly, nonatomic) NSSet *itemComponents; // @synthesize itemComponents=_itemComponents;
@property(readonly, nonatomic) long long layoutRegion; // @synthesize layoutRegion=_layoutRegion;
@property(readonly, nonatomic) TLKLayoutContext *layoutContext; // @synthesize layoutContext=_layoutContext;
@property(readonly, nonatomic) TLKLayoutGraph *layoutGraph; // @synthesize layoutGraph=_layoutGraph;
- (struct CGRect)_applyPrimaryComponentConstraintForItemComponentFragment:(id)arg1 proposedFrame:(struct CGRect)arg2;
- (struct CGRect)_applyConstraintsForItemComponentFragment:(id)arg1 proposedFrame:(struct CGRect)arg2;
- (id)_keepSecondaryComponentsWithPrimaryForItemComponentFragments:(id)arg1;
- (struct CGRect)_calculatedFrameForLaneFragment:(id)arg1;
- (struct CGRect)_calculatedFrameForItemComponentFragment:(id)arg1;
- (id)_makeFragmentForItemComponent:(id)arg1 inLayoutContext:(id)arg2 changeLog:(id)arg3;
- (struct CGRect)_constrainRectToLayoutRegion:(struct CGRect)arg1;
- (void)main;
- (void)dealloc;
- (id)initWithItemComponents:(id)arg1 inLayoutRegion:(long long)arg2 layoutContext:(id)arg3 layoutGraph:(id)arg4;

@end

