//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TLKit/TLKAbstractPrecisionEditorVerticalLinesLayer.h>

@class CALayer, NSDictionary;

@interface TLKPrecisionEditorVerticalLinesLayer : TLKAbstractPrecisionEditorVerticalLinesLayer
{
    CALayer *_rootLayer;
    NSDictionary *_mappingTable;
    int _layerState;
}

- (int)layerState;
- (void)setLayerState:(int)arg1;
- (void)dealloc;
- (id)init;

@end

