//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

#import "TLKLayerState.h"

@class NSDictionary, NSString;

@interface TLKPrecisionEditorEditButtonLayer : CALayer <TLKLayerState>
{
    NSDictionary *_mappingTable;
    int _layerState;
    struct CGRect _originalBounds;
}

@property(readonly, nonatomic) struct CGRect originalBounds; // @synthesize originalBounds=_originalBounds;
@property(nonatomic) int layerState; // @synthesize layerState=_layerState;
- (struct CGSize)preferredFrameSize;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

