//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMapTable, TLKLayoutContext, TLKRangeSelectionBackgroundLayer;

@interface TLKRangeSelection : NSObject
{
    int _displayMode;
    TLKLayoutContext *_backgroundLayoutContext;
    NSMapTable *_layoutContexts;
    TLKRangeSelectionBackgroundLayer *_backgroundLayer;
    struct CGRect _frame;
}

@property(nonatomic) int displayMode; // @synthesize displayMode=_displayMode;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(nonatomic) TLKRangeSelectionBackgroundLayer *backgroundLayer; // @synthesize backgroundLayer=_backgroundLayer;
@property(nonatomic) NSMapTable *layoutContexts; // @synthesize layoutContexts=_layoutContexts;
@property(nonatomic) TLKLayoutContext *backgroundLayoutContext; // @synthesize backgroundLayoutContext=_backgroundLayoutContext;
@property(readonly, nonatomic) NSArray *rangeSelectionFragments;
- (id)debugDescription;
- (void)dealloc;
- (id)init;

@end

