//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class PCChangeLog, TLKLayerManager;

@interface TLKReloadLayersOperation : NSOperation
{
    PCChangeLog *_inputChangeLog;
    TLKLayerManager *_layerManager;
}

@property(retain, nonatomic) TLKLayerManager *layerManager; // @synthesize layerManager=_layerManager;
@property(copy, nonatomic) PCChangeLog *inputChangeLog; // @synthesize inputChangeLog=_inputChangeLog;
- (void)_addInputChangeLogRecordsToLayerManagerQueue;
- (void)main;
- (void)dealloc;

@end

