//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProThemeColor.h"

@interface TLKThemeColor : NSProThemeColor
{
}

+ (unsigned long long)themeIndex;
+ (id)accessoryItemAVUnSelectedColor;
+ (id)accessoryItemAudioUnSelectedColor;
+ (id)accessoryItemSecondarySelectedColor;
+ (id)accessoryItemSelectedColor;
+ (id)edgeAllowedColor;
+ (id)edgeNotAllowedColor;
+ (id)guideLineColor;
+ (id)itemRulerTickColor;
+ (id)itemTextColor;
+ (id)leftEdgeBumperOverlayColor;
+ (id)selectedItemTextColor;
+ (id)selectionMarqueeGradientBottomColor;
+ (id)selectionMarqueeGradientDisabledBottomColor;
+ (id)selectionMarqueeGradientDisabledTopColor;
+ (id)selectionMarqueeGradientTopColor;
+ (id)selectionMarqueeInnerGlowGradientBottomColor;
+ (id)selectionMarqueeInnerGlowGradientDisabledTopColor;
+ (id)selectionMarqueeInnerGlowGradientTopColor;
+ (id)slimAVClipBorderColor;
+ (id)slimAudioClipBorderColor;
+ (id)slimContainerClipBorderColor;
+ (id)slimGapClipBorderColor;
+ (id)slimGeneratorClipBorderColor;
+ (id)slimMotionPlaceholderClipBorderColor;
+ (id)slimTitleClipBorderColor;
+ (id)slimTransitionlipBorderColor;
+ (id)soloAudioShadowColor;
+ (id)soloVideoShadowColor;
+ (id)timelineBackgroundColor;
+ (id)timelineBackgroundDisabledColor;
+ (id)timelineGuidelineSnappingHeavyColor;
+ (id)timelineGuidelineSnappingLightColor;
+ (id)videoFilmstripBorderColor;

@end

