//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <TLKit/TLKTimelineView.h>

@interface TLKTimelineView (ClientLayerSupport)
- (void)layoutSublayers:(id)arg1 forItem:(id)arg2;
- (void)layoutSublayersOfVideoLayer:(id)arg1 audioLayer:(id)arg2 forItem:(id)arg3;
- (id)badgeLayersForItem:(id)arg1 currentBadges:(id)arg2;
@end

