//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <TLKit/TLKTimelineHandler.h>

@class TLKTransitionPlaceholderLayer;

@interface TLKTransitionPlaceholderHandler : TLKTimelineHandler
{
    TLKTransitionPlaceholderLayer *_rolledOverLayer;
    BOOL _enableRolloverState;
}

@property(nonatomic) BOOL enableRolloverState; // @synthesize enableRolloverState=_enableRolloverState;
- (void)exitRollover:(id)arg1;
- (BOOL)enterRollover:(id)arg1;
- (BOOL)stopTracking:(id)arg1;
- (id)initWithView:(id)arg1;

@end

