//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class TLKPointArray;

@interface TLKUsedRegion : NSObject <NSCopying>
{
    TLKPointArray *_minYPath;
    TLKPointArray *_maxYPath;
    struct CGRect _bounds;
}

@property(copy, nonatomic) TLKPointArray *maxYPath; // @synthesize maxYPath=_maxYPath;
@property(copy, nonatomic) TLKPointArray *minYPath; // @synthesize minYPath=_minYPath;
- (id)pointsOnEdge:(unsigned int)arg1;
- (void)insetRectEdge:(unsigned int)arg1 byAmount:(double)arg2;
- (void)unionRect:(struct CGRect)arg1;
- (void)_outsetPath:(id)arg1 inLocationRange:(struct _TLKRange)arg2 toYValue:(double)arg3;
- (long long)_comparePoint:(struct CGPoint)arg1 withPoint:(struct CGPoint)arg2 isFlipped:(BOOL)arg3;
- (struct CGRect)appendRect:(struct CGRect)arg1 toEdge:(unsigned int)arg2;
- (struct CGRect)_boundingBoxForLocationRange:(struct _TLKRange)arg1 inPointArray:(id)arg2;
@property(readonly, nonatomic) BOOL isEmpty;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (void)_setBounds:(struct CGRect)arg1;
@property(readonly, nonatomic) struct CGRect bounds;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithCapacity:(unsigned long long)arg1;
- (id)init;

@end

