//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, TLKVerticalIndexTableKey;

@interface TLKVerticalIndexTableRow : NSObject
{
    NSMutableArray *_layoutGraphNodes;
    TLKVerticalIndexTableKey *_key;
}

@property(copy, nonatomic) NSArray *layoutGraphNodes; // @synthesize layoutGraphNodes=_layoutGraphNodes;
@property(readonly, nonatomic) TLKVerticalIndexTableKey *key; // @synthesize key=_key;
- (id)findNodesIntersectingRange:(CDStruct_e83c9415)arg1 inArray:(id)arg2;
- (id)layoutGraphNodesIntersectingRange:(CDStruct_e83c9415)arg1;
- (void)sortUsingComparator:(CDUnknownBlockType)arg1;
- (void)removeLayoutGraphNode:(id)arg1;
- (void)addLayoutGraphNode:(id)arg1;
- (unsigned long long)countOfLayoutGraphNodes;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithVerticalIndexTableKey:(id)arg1;

@end

