//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PROAPIAccessing.h"

@class NSMutableArray, NSMutableDictionary;

@interface PROLegacyPluginManager : NSObject <PROAPIAccessing>
{
    NSMutableDictionary *_pluginRegistry;
    NSMutableArray *_pluginProtocols;
    NSMutableArray *_pluginSearchDirectories;
    struct __CFDictionary *_apiRegistry;
}

+ (id)pluginManager;
- (id)init;
- (void)dealloc;
- (int)addPluginProtocol:(id)arg1;
- (int)addPluginSearchDirectory:(id)arg1;
- (int)setPluginSearchDirectories:(id)arg1;
- (int)setApiObject:(id)arg1 forProtocol:(id)arg2;
- (int)setApiObjects:(id)arg1 forProtocols:(id)arg2;
- (id)apiForProtocol:(id)arg1;
- (int)removeApiForProtocol:(id)arg1;
- (int)scanForPlugins;
- (void)localizeKey:(id)arg1 withDefault:(id)arg2 forPlugin:(id)arg3 fromBundle:(id)arg4;
- (int)registerPluginWithDictionary:(id)arg1 withClassName:(id)arg2 withBundle:(id)arg3 withProtocolName:(id)arg4;
- (int)registerBundle:(id)arg1 withPluginDictionaryList:(id)arg2;
- (int)registerBundleDynamic:(id)arg1;
- (int)loadPluginClass:(Class *)arg1 withName:(id)arg2 fromBundlePath:(id)arg3;
- (int)scanForPluginsInDirectory:(id)arg1;
- (int)getNumPluginsForProtocol:(id)arg1;
- (int)getPluginDisplayNames:(id)arg1 forProtocol:(id)arg2;
- (int)getPluginClassNames:(id)arg1 forProtocol:(id)arg2;
- (int)getPluginGroupNames:(id)arg1;
- (int)getPluginGroupNames:(id)arg1 forProtocol:(id)arg2;
- (int)getPluginClassNames:(id)arg1 forGroupName:(id)arg2;
- (int)getPluginClassNames:(id)arg1 forGroupName:(id)arg2 forProtocol:(id)arg3;
- (int)getPluginDisplayNames:(id)arg1 forGroupName:(id)arg2;
- (int)getPluginDisplayNames:(id)arg1 forGroupName:(id)arg2 forProtocol:(id)arg3;
- (int)getPluginInfoDictionaries:(id)arg1 forProtocol:(id)arg2;
- (int)getBundlePath:(id *)arg1 forPluginClassName:(id)arg2;
- (int)getPluginClass:(Class *)arg1 forPluginClassName:(id)arg2;
- (int)getPluginClass:(Class *)arg1 forPluginDisplayName:(id)arg2;
- (int)getPluginClass:(Class *)arg1 forPluginDisplayName:(id)arg2 forProtocol:(id)arg3;

@end

