//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol FFPlayerVideoScopesModuleViewDelegate
- (void)drawScopeViewWithFrame:(id)arg1 forRate:(double)arg2 atTime:(CDStruct_1b6d18a9)arg3;
- (id)menuForVideoScopeOptions;
- (BOOL)validateUserInterfaceItem:(id)arg1;
@end

