//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProPreferencesModule.h"

#import "NSOpenSavePanelDelegate.h"

@class LKTableView, NSArrayController;

@interface PEAppStoragePreferencesModule : NSProPreferencesModule <NSOpenSavePanelDelegate>
{
    LKTableView *_locationsList;
    NSArrayController *_locationsArrayController;
}

- (BOOL)panel:(id)arg1 validateURL:(id)arg2 error:(id *)arg3;
- (BOOL)panel:(id)arg1 shouldEnableURL:(id)arg2;
- (void)clearCustomStorageLocationButton:(id)arg1;
- (void)setCustomStorageLocationButton:(id)arg1;
- (id)init;

@end

