//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProPreferencesModule.h"

#import "NSOpenSavePanelDelegate.h"

@class LKButton, NSMatrix, NSString;

@interface PEAppImportPreferencesModule : NSProPreferencesModule <NSOpenSavePanelDelegate>
{
    NSMatrix *_importLocationRadioButtonMatrix;
    LKButton *_addFolderKeywordsCheckBox;
    LKButton *_addTagKeywordsCheckBox;
    LKButton *_optimizeMediaCheckBox;
    LKButton *_createProxyMediaCheckBox;
    LKButton *_createStillCacheCheckBox;
    LKButton *_autoColorBalance;
    LKButton *_autoStabilization;
    LKButton *_autoFaceDetection;
    LKButton *_findPeopleConsolidateResults;
    LKButton *_createSmartCollectionsCheckBox;
    LKButton *_autoEmptyTracksDetection;
    LKButton *_autoRelatedTracksDetection;
    LKButton *_autoCleanupAudio;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)findPeopleEnabled;
- (id)titleForIdentifier:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (BOOL)isResizable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

