//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSArray, NSButton, NSTextField;

@interface PEBackgroundTaskView : NSView
{
    NSArray *_tasks;
    double _progress;
    BOOL _paused;
    BOOL _cancelled;
    NSButton *_pauseResumeButton;
    NSButton *_cancelButton;
    NSView *_progressView;
    NSTextField *_displayNameTextField;
}

- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)configureWithTasks:(id)arg1;
- (id)_progressLayer;
- (void)_updateProgress;
- (void)_updateIsPaused;
- (void)togglePauseResume:(id)arg1;
- (void)cancel:(id)arg1;
@property(getter=isPaused) BOOL paused; // @synthesize paused=_paused;
@property(nonatomic) double progress; // @synthesize progress=_progress;

@end

