//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "FFModalProgress.h"

@class NSButton, NSDate, NSMutableArray, NSProgressIndicator, NSRecursiveLock, NSWindow;

@interface PEModalProgress : NSWindowController <FFModalProgress>
{
    id _titleText;
    id _statusText;
    NSProgressIndicator *_progressIndicator;
    NSRecursiveLock *_lock;
    BOOL _isPastStartup;
    NSMutableArray *_statusStrings;
    int _progressStatus;
    NSDate *_requestDate;
    NSWindow *_targetWindow;
    BOOL _allowCancel;
    BOOL _hasCancelled;
    double _maxValue;
    NSButton *_cancelButton;
}

+ (void)releaseSharedInstance;
+ (id)sharedInstance;
+ (void)initialize;
@property(retain, nonatomic) NSWindow *targetWindow; // @synthesize targetWindow=_targetWindow;
@property(retain, nonatomic) NSDate *requestDate; // @synthesize requestDate=_requestDate;
- (void)showIfTime;
- (void)endModalProgress;
- (BOOL)updateModalProgress:(id)arg1 currentValue:(double)arg2 maxValue:(double)arg3 allowCancel:(BOOL)arg4;
- (void)beginModalProgress:(id)arg1 titleText:(id)arg2 showType:(int)arg3 targetWindow:(id)arg4;
- (void)cancelAction:(id)arg1;
- (void)awakeFromNib;
- (void)_refreshStatus;
- (void)_hideSheet;
- (void)_showSheet;
- (id)_statusDisplay;
- (void)_clearRequestDate;
- (void)setIsPastStartup:(BOOL)arg1;
- (void)dealloc;
- (id)init;

@end

