//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class FFAnchoredObject, FFAnchoredSequence, FFContext, FFTimecodeDisplayObject, NSArray, NSColor, NSDictionary, NSImage, NSMutableDictionary, NSMutableParagraphStyle;

@interface PEPlayerTimecodeWindowView : NSView
{
    long long _windowNumber;
    NSArray *_displayObjects;
    FFAnchoredObject *_rootItem;
    FFAnchoredSequence *_rootItemSequence;
    FFContext *_currentContext;
    BOOL _recalcFontSize;
    long long _timeCodeWidth;
    int _timeThirdDigitGap;
    NSImage *_moreFilesIcon;
    NSColor *_timeCodeProjectColor;
    NSDictionary *_textAttributesTimeTest;
    NSDictionary *_textAttributesBodyTest;
    NSDictionary *_textAttributes;
    NSDictionary *_textAttributesTime;
    NSMutableParagraphStyle *_timeCodeParamgraphStyle;
    NSMutableParagraphStyle *_timeTextParamgraphStyle;
    id _delegate;
    NSMutableDictionary *_viewOptionsDictionary;
    BOOL _showNames;
    BOOL _showRoles;
    BOOL _showProjectTime;
    BOOL _showSourceTimes;
    BOOL _dataAlreadyFetched;
    BOOL _addingRemovingColumn;
    BOOL _displayingOnlyTimecode;
    struct CGSize _lastSize;
    double _lastFontSize;
    FFTimecodeDisplayObject *_lastSelectedObject;
    BOOL _observingContext;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) BOOL observingContext; // @synthesize observingContext=_observingContext;
@property(nonatomic) BOOL addingRemovingColumn; // @synthesize addingRemovingColumn=_addingRemovingColumn;
- (void)setViewOptionDictionary:(id)arg1;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)noRecalcFontSizeOnNextDraw;
- (void)drawRect:(struct CGRect)arg1;
- (void)setLastNameWidth:(long long)arg1;
- (long long)lastNameWidth;
- (void)setLastRolesWidth:(long long)arg1;
- (long long)lastRolesWidth;
- (void)setLastLineHeight:(long long)arg1;
- (long long)lastLineHeight;
- (void)setLastFontSize:(double)arg1;
- (double)lastFontSize;
- (void)setLastSize:(struct CGSize)arg1;
- (struct CGSize)lastSize;
- (void)setFontSize:(double)arg1;
- (double)calcNewFontSizeFromOptimumWidths:(struct CGRect)arg1;
- (double)optimumRolesWidthUsingCurrentDisplayObjects;
- (void)fetchDataFromContextAndContainer:(id)arg1 atTime:(CDStruct_1b6d18a9)arg2;
- (void)drawBottomFadedEdge:(struct CGRect)arg1 backColor:(double)arg2;
- (void)drawProjectNameDiverLines:(struct CGRect)arg1 ypos:(int)arg2 lineHeight:(int)arg3;
- (id)selectedItemsForContext:(id)arg1 selectionImplicit:(char *)arg2;
- (id)newTimecodeAttributedStringForString:(id)arg1 valueColor:(id)arg2 withDefaultAttributes:(id)arg3 projectTimecodeLine:(BOOL)arg4;
- (struct _NSRange)subFrameRange:(id)arg1;
- (struct _NSRange)rangeOfLeadingZeros:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)updateTimelineObjectIfShow:(id)arg1;
- (void)didCloseMenu:(id)arg1 withEvent:(id)arg2;
- (id)menuForEvent:(id)arg1;
- (void)copyAllToPasteboard:(id)arg1;
- (void)copyItemToPasteboard:(id)arg1;
- (void)copyStringOrStringsToPasteBoard:(BOOL)arg1;
- (void)copyTimecodeToPasteboard:(id)arg1;
- (void)timeRateChangedForContext:(id)arg1;
- (void)_storyPresentationChanged:(id)arg1;
- (void)_notifySequenceEdited:(id)arg1;
- (id)currentProjectName;
- (void)selectionInvalidated:(id)arg1;
- (void)setTimelineContext:(id)arg1 newRootItem:(id)arg2 windowNumber:(long long)arg3;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)localInitVariables;
- (long long)nameWidth;
- (long long)timeCodeWidth;
- (long long)rolesWidth;

@end

