//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSMenuDelegate.h"
#import "NSWindowDelegate.h"

@class NSLayoutConstraint, NSMenu, NSMutableDictionary, NSString, PEPlayerTimecodeWindowView;

@interface PEPlayerTimecodeWindowController : NSWindowController <NSWindowDelegate, NSMenuDelegate>
{
    long long _windowNumber;
    BOOL _initialized;
    BOOL _playerisInFullScreen;
    PEPlayerTimecodeWindowView *_timecodeImageView;
    NSMenu *_timecodeWindowMenu;
    NSLayoutConstraint *_minWidthConstraint;
    NSLayoutConstraint *_minHeightConstraint;
    struct CGRect _contentFrameOnStartingDrag;
    struct CGRect _windowFrameOnStartingDrag;
    NSMutableDictionary *_options;
    BOOL _displayTimecodeProjectTimecode;
    BOOL _displayTimecodeSourceTimecodes;
    BOOL _displayTimecodeClipNames;
    BOOL _displayTimecodeClipRoles;
    long long _HUDStyle;
    BOOL _observingContext;
}

@property(nonatomic) BOOL observingContext; // @synthesize observingContext=_observingContext;
@property(nonatomic) NSLayoutConstraint *minHeightConstraint; // @synthesize minHeightConstraint=_minHeightConstraint;
@property(nonatomic) NSLayoutConstraint *minWidthConstraint; // @synthesize minWidthConstraint=_minWidthConstraint;
- (void)_playerDidExitFullScreen:(id)arg1;
- (void)_playerWillEnterFullScreen:(id)arg1;
- (id)videoModule;
- (void)windowDidEndLiveResize:(id)arg1;
- (struct CGSize)windowWillResize:(id)arg1 toSize:(struct CGSize)arg2;
- (void)windowWillStartLiveResize:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)stopObservingContext;
- (void)startObservingContext;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)useMoreTranslucidWindowStyle:(id)arg1;
- (void)useSolidWindowStyle:(id)arg1;
- (void)useTranslucidWindowStyle:(id)arg1;
- (void)useBlurWindowStyle:(id)arg1;
- (void)actionSetDisplayTimecodeClipRoles:(id)arg1;
- (void)actionSetDisplayTimecodeClipNames:(id)arg1;
- (void)actionSetDisplayTimecodeSourceTimecodes:(id)arg1;
- (void)actionSetDisplayTimecodeProjectTimecode:(id)arg1;
- (void)actionSetNoCheckInTimecodeMenu:(id)arg1;
- (void)setHUDStyle:(long long)arg1;
- (long long)HUDStyle;
@property(nonatomic) BOOL displayTimecodeClipRoles;
@property(nonatomic) BOOL displayTimecodeClipNames;
@property(nonatomic) BOOL displayTimecodeSourceTimecodes;
@property(nonatomic) BOOL displayTimecodeProjectTimecode;
- (void)awakeFromNib;
- (void)windowDidLoad;
- (void)windowDidResize:(id)arg1;
- (void)windowDidMove:(id)arg1;
- (void)_saveWindowRect;
- (void)windowWillClose:(id)arg1;
- (void)showWindow:(id)arg1;
- (void)updateLocalCacheFromOptions;
- (void)setInitialOptions;
- (void)setWithNewOptions:(id)arg1;
- (void)_rebuildViewForNewValues;
- (void)setMinSizeForOptions;
- (id)initTimecodeWindow:(long long)arg1 objectOptions:(BOOL)arg2 options:(id)arg3;
- (void)saveOptionsToDefaults;
- (id)timecodeOptions;
- (id)optionsDictionaryNameForDisplay;
- (id)windowDisplayString:(int)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

