//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 11 2021 20:53:35).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProCore/PCCaptionProtocol-Protocol.h>

@class NSAttributedString;

@protocol PCMutableCaptionProtocol <PCCaptionProtocol>
- (void)setFontDecoration:(long long)arg1 inRange:(struct _NSRange)arg2;
- (void)setFontStyle:(long long)arg1 inRange:(struct _NSRange)arg2;
- (void)setFontWeight:(long long)arg1 inRange:(struct _NSRange)arg2;
- (void)setBackgroundColor:(struct CGColor *)arg1 inRange:(struct _NSRange)arg2;
- (void)setTextColor:(struct CGColor *)arg1 inRange:(struct _NSRange)arg2;
- (void)setTimeRange:(CDStruct_e83c9415)arg1;
- (void)setAttributedString:(NSAttributedString *)arg1;
@end

